### ISSUE TITLE
🚀 Feature: TUS protocol resumable support

### ISSUE THREAD

**Issue by droplinxuser** [stonith404/pingvin-share#100]
### 🔖 Feature description

Upload and Download resumable support using:
https://tus.io/

### 🎤 Pitch

Be able to bypass Cloudflare 100MB upload limit also.

**Comment by stonith404** [comment]
We've already implemented chunk uploads that bypasses the Cloudflare request size limit and allows resumable uploads. Why do you think we should implement the TUS protocol?

**Comment by droplinxuser** [comment]
Oh sorry if it's already implemented.
Can be close now.
Thanks!

**Comment by droplinxuser** [comment]
TUS has much better support though compare to Dropzone I think.
Like uploads or download will resume even on network disconnect.
