### ISSUE TITLE
❓ Question: Files will be kept indefinitely as long as they are downloaded at least once every month?

### ISSUE THREAD

**Issue by droplinxuser** [stonith404/pingvin-share#101]
### 🙋‍♂️ Question

Does this web app support retaining the files if it's downloaded at least once every month?
Only delete the file if it hasn't been downloaded for more than a month.

Some free file hosting have that feature.

**Comment by stonith404** [comment]
At the moment the share gets deleted when the user deletes the share manually or the expiration date is due. If you think this isn't enough feel free to create a feature request :)
