### ISSUE TITLE
🚀 Feature:  Let's Encrypt SSL

### ISSUE THREAD

**Issue by codedbean** [stonith404/pingvin-share#104]
### 🔖 Feature description

Include the ability to create an SSL certificate for the application when running the application for the first time. This would help anyone to run the application securely and be able to enable SMTP without having to through vigorous steps of setting up SSL to be able to send email notifications.

### 🎤 Pitch

This would help out users who are new to development to run the application securely to test the email notifications using SMTP without going through several steps in creating an SSL manually.

**Comment by stonith404** [comment]
I'm not sure if I want to implement this directly into Pingvin Share because this could easily be done with a reverse proxy. You just could add Nginx to the Docker Compose stack and setup a SSL certificate in it.

**Comment by sebastian-b00** [comment]
@BotVue if you are new on Docker, I recommend you to use Caprover, it uses docker, nginx and allow to generate Let's encrypt certificates easily.
It have something like a "app store", but you can also deploy others apps that are not in that.
https://caprover.com/docs/get-started.html

**Comment by stonith404** [comment]
@BotVue The problem with the `self-signed certificate` occurred while Pingvin Share tried to connect to the SMTP server. This hasn't something to do with the SSL certificate of your Pingvin Share instance but with the certificate of the SMPT server. I think this error can occur when you've entered the wrong host or port.

Could you try if it works on the [SMTP checker website](https://www.smtper.net/) with the exact same SMTP configuration?

**Comment by stonith404** [comment]
@BotVue Which SMTP port do you use?

**Comment by sebastian-b00** [comment]
> I checked out the SMTP checker and it seems like it only works if I uncheck "Use Secured Connection", but if it's checked SMTP fails on me. I might have to change the protocol somehow to make it work. All my certificates for SSL are signed and generated using https://zerossl.com.

Maybe you can try with something like smtp2go

**Comment by stonith404** [comment]
Is the issue completed for you?
