### ISSUE TITLE
🚀 Feature: Send Invitation Code/Email

### ISSUE THREAD

**Issue by BotVue** [stonith404/pingvin-share#105]
### 🔖 Feature description

Have the ability to send either a code or an email to new users that an Administrator creates in the backend to invite new accounts to log in or complete the account setup.

### 🎤 Pitch

This would simplify the invite process when you want to send an invite securely to the user who requests access without having to share their account login information.

**Comment by stonith404** [comment]
That's a good idea👍

**Comment by stonith404** [comment]
Added in f9840505b82fcb04364a79576f186b76cc75f5c0 and will be released soon.

**Comment by stonith404** [comment]
Released in `v0.11.0`
