### ISSUE TITLE
🚀 Feature: S3 Object Storage

### ISSUE THREAD

**Issue by codedbean** [stonith404/pingvin-share#106]
### 🔖 Feature description

Have the option to add an S3 Object Storage option to store files on decentralized storage. These are the two sites that I personally have used. 

https://www.storj.io/

https://filebase.com/

### 🎤 Pitch

To expand storage options if someone would like to use decentralized storage to secure the files more or to use it as a backup alongside the local storage that the app already using.

**Comment by iUnstable0** [comment]
that'd be great!

**Comment by stonith404** [comment]
Do you guys think it will be sufficient to mount the S3 storage to your server? Like described in [this article](https://www.howtogeek.com/devops/how-to-mount-an-s3-bucket-locally-on-linux/)

**Comment by stonith404** [comment]
@BotVue Okay👍 Do you think we could close the issue?
