### ISSUE TITLE
🐛 Bug Report: Docker pull failed to register layer Proxmox

### ISSUE THREAD

**Issue by Madchristian** [stonith404/pingvin-share#107]
### 👟 Reproduction steps

Try to run the docker-compose.yml in a LXC Container on Proxmox

Pulling pingvin-share (stonith404/pingvin-share:)...
latest: Pulling from stonith404/pingvin-share
bb263680fed1: Already exists
90145816ab6f: Pull complete
...
4bab91e1b38d: Extracting [==================================================>]  73.57MB/73.57MB
2e83afd1ce5b: Download complete
014663f7e52a: Download complete
243295fd4d31: Download complete
4f4fb700ef54: Download complete
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /opt/app/backend/node_modules/buffer-equal-constant-time/.npmignore: invalid argument

### 👍 Expected behavior

Pull Complete

### 👎 Actual Behavior

4bab91e1b38d: Extracting [==================================================>]  73.57MB/73.57MB
2e83afd1ce5b: Download complete
014663f7e52a: Download complete
243295fd4d31: Download complete
4f4fb700ef54: Download complete
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /opt/app/backend/node_modules/buffer-equal-constant-time/.npmignore: invalid argument

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
I've never used Proxmox before so I can't help you with that, sorry. 

[Here](https://forum.proxmox.com/threads/docker-failed-to-register-layer-applylayer-exit-status-1-stdout-stderr-unlinkat-var-log-apt-invalid-argument.119954/) is some link to a forum where someone might had the same issue.

If this doesn't help, I would google something like this:
`ERROR: failed to register layer: ApplyLayer exit status 1 stdout: stderr: lchown buffer-equal-constant-time/.npmignore: invalid argument`

**Comment by hakrishi** [comment]
I too have the same issue. @Madchristian did you find a solution?

**Comment by jl-678** [comment]
This is interesting. I am running Docker in an LXC container with Pingvin with no issues. I originally built my container based off the LXC image [here](https://tteck.github.io/Proxmox/https://tteck.github.io/Proxmox/). I wonder if it relates to the unprivileged thing linked in the Proxmox Forum post.

**Comment by hakrishi** [comment]
The link posted leads me to a 404 page @jl-678. Which image is it? I'm using Ubuntu 22.04.

**Comment by jl-678** [comment]
Sorry about that. I fixed the link. The image build is based on Debian 11, and the LXC container is configured with "Unprivileged = No".
