### ISSUE TITLE
🚀 Feature: OAuth

### ISSUE THREAD

**Issue by nicobleiler** [stonith404/pingvin-share#109]
### 🔖 Feature description

Implementation of an OAuth integration to be able to use custom OAuth providers like authentik.

### 🎤 Pitch

The ability to have central user management over OAuth would be really nice if you already have multiple applications with the same users.

**Comment by stonith404** [comment]
That's definitely something I want to implement 👍

**Comment by SISheogorath** [comment]
I would recommend to go for [OIDC (which obviously includes the usage of oauth)](https://developer.okta.com/blog/2019/10/21/illustrated-guide-to-oauth-and-oidc) as part of this effort.

**Comment by stonith404** [comment]
I've never implemented OAuth2 before in NestJS. I'm looking forward to implement this in the future but I prioritize easier issues at the moment as I have many exams currently. If someone has experience in implementing OAuth2 in NestJS, feel free to create a PR :)
