### ISSUE TITLE
🚀 Feature: Put a copy icon in share link view

### ISSUE THREAD

**Issue by coaz** [stonith404/pingvin-share#111]
### 🔖 Feature description

Like other plataforms do, When a share icon previes it will be nice to have a copy to clipboard icon.

### 🎤 Pitch

with this option, non experimented users can have the sare link more easy.

**Comment by stonith404** [comment]
I don't really understand your feature suggestion. Could you please provide a more detailed description?

**Comment by coaz** [comment]
thank you. It already exist the copy icon to copy from clipboard. It doesnt work in a non secure window.
