### ISSUE TITLE
🐛 Bug Report: Proxmox Docker Compose failing to start

### ISSUE THREAD

**Issue by hakrishi** [stonith404/pingvin-share#114]
### 👟 Reproduction steps

Hi there,

I am running a Debian 11 LXC Proxmox container and am experiencing errors when attempting to start the container.

The `Unprivileged Container `option is set to `No` so it does indeed have the necessary permissions. 

Many thanks

Rishi

### 👍 Expected behavior

Container should start as normal without errors

### 👎 Actual Behavior

Errors when starting the container:
```
Starting pingvin_pingvin-share_1 ... error

ERROR: for pingvin_pingvin-share_1  Cannot start service pingvin-share: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: permission denied: unknown

ERROR: for pingvin-share  Cannot start service pingvin-share: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: permission denied: unknown
ERROR: Encountered errors while bringing up the project.
```

### 🌐 Browser

Brave

**Comment by stonith404** [comment]
Does this only occur in the latest release?

**Comment by hakrishi** [comment]
I'm using Docker and modified the version from 3.8 to 3.0 in the compose file as 3.8 did not work and failed with the below error:
```
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

So in response to your question, no I'm not using the latest version due to the above error. Thanks

**Comment by stonith404** [comment]
I don't use Proxmox so I can't really help you with that. I've found a comment on Stackoverflow, maybe this can can help you: https://stackoverflow.com/a/68292877/14058016

Regarding to the docker compose version issue, you probably use the command `docker-compose` (v1) instead of `docker compose` (v2), don't you? It should be fine to use the old version of docker compose but I didn't test it.
