### ISSUE TITLE
❓ Question:  Uploads

### ISSUE THREAD

**Issue by krintek** [stonith404/pingvin-share#115]
### 🙋‍♂️ Question

When will the expired uploads get deleted from the server? I cannot create the same link name even though the last upload expired! I also manually deleted the file from the server but couldn't create a new link with same name! 

![Screenshot_20230306-111255](https://user-images.githubusercontent.com/87629857/223028397-3e68fd32-e10d-4eeb-8ece-4f41f2431b14.jpg)
![Screenshot_20230306-111341](https://user-images.githubusercontent.com/87629857/223028414-aca93141-f40f-4306-9618-a4b207308aa3.jpg)
![Screenshot_20230306-111449](https://user-images.githubusercontent.com/87629857/223028546-9ed8c8ed-cf44-4b1a-823d-00357e4f561e.jpg)

**Comment by stonith404** [comment]
The expired shares should get [deleted every hour with a cron job](https://github.com/stonith404/pingvin-share/blob/main/backend/src/jobs/jobs.service.ts#L17). If you delete the files the share still exists because it is still in the database.
