### ISSUE TITLE
❓ Question: What is a suitable replacement for the "app icon" in Unraid template?

### ISSUE THREAD

**Issue by blaine07** [stonith404/pingvin-share#116]
### 🙋‍♂️ Question

On Unraid, the Pingvin-Share Icon, for the container itself in the Unraid Template, was pointing to: 

https://github.com/stonith404/pingvin-share/blob/main/frontend/public/icons/icon-512x512.png?raw=true

With the recent theming changes it seems that is no long there.

What is a suitable replacement for the "app icon" in Unraid template?

Thank you!

**Comment by stonith404** [comment]
The icons were moved inside the `img` folder. Instead of `/frontend/public/icons` it is now `/frontend/public/img/icons`.

Let me know if this fixed your issue :)

**Comment by blaine07** [comment]
Thanks for prompt response. Will change it and report back in a bit. Any idea if in Unraid it needs the “raw=true” part?

**Comment by vadarr** [comment]
This fixed it for me, turn on advanced mode. put that in the icon URL section.

https://github.com/stonith404/pingvin-share/blob/main/frontend/public/img/icons/icon-512x512.png?raw=true

**Comment by blaine07** [comment]
Got it working. Thank you guys!

**Comment by stonith404** [comment]
Nice, can we close this issue?
