### ISSUE TITLE
🐛 Bug Report: Unable to upload multiple files at once

### ISSUE THREAD

**Issue by mooyg** [stonith404/pingvin-share#118]
### 👟 Reproduction steps

Try to select multiple files and uploading them

### 👍 Expected behavior

Automatically upload all the files time by time

### 👎 Actual Behavior

Only uploads the first file and aborts all the rest

### 🌐 Browser

Chrome

**Comment by mooyg** [comment]
For most of the files 
![image](https://user-images.githubusercontent.com/61348580/223314669-54dc92de-1a5f-43c8-a3fd-2f44ef4a2bda.png)
this is what it looks like I guess it's not handled currently on the server

**Comment by stonith404** [comment]
Thanks for your report! Which reverse proxy do you use?

**Comment by iUnstable0** [comment]
@mooyg Its probably your proxy settings that restrict the max upload size, if you're using nginx then set this
client_max_body_size to something bigger, default value is 1MB if I could remember

**Comment by stonith404** [comment]
Yeah closing this because this is probably a reverse proxy issue. Feel free to reopen it if the issue still occurs without reverse proxy.
