### ISSUE TITLE
ERROR: failed to register layer: ApplyLayer exit status 1 stdout: stderr: 

### ISSUE THREAD

**Issue by shayp2007** [stonith404/pingvin-share#119]
Hey there,

trying to install pingvin on proxmox 7.3-6 in ubuntu 22.10 LXC containernand when docker image is pulled via docker compose. i get the following error:

ERROR: failed to register layer: ApplyLayer exit status 1 stdout: stderr: lchown /opt/app/backend/node_modules/buffer-equal-constant-time/.npmignore: invalid argument

have read that making the container unprivileged may fix the issue but i am reluctant to do so due to the nature and use of the application. Is this a bug or is there a fix for this?

thanks.

**Comment by stonith404** [comment]
Thanks for your report. This issue already exists, please refer to #107.
