### ISSUE TITLE
More granular expiration input.

### ISSUE THREAD

**Issue by stautonico** [stonith404/pingvin-share#12]
I wrote issue #8  and realized after I opened PR #11 that it would make much more sense to have even more granular expiration selection.

Something like this:
![image](https://user-images.githubusercontent.com/36276517/195465973-0f1c754f-9532-4474-bb32-c1779d83f4d6.png)

Based on the source code, it shouldn't be too hard to implement. Maybe I can replace PR #11 with a feature like this?

These lines could essentially stay exactly the same:
https://github.com/stonith404/pingvin-share/blob/cde22f85ee785363bb0149347a2187c9166f4cb6/backend/src/share/share.service.ts#L38-L43

Pretty much the only thing that would need to change would be:
https://github.com/stonith404/pingvin-share/blob/b30269344db456a83b846247725fa9ea242e3d94/frontend/src/components/share/CreateUploadModalBody.tsx#L102-L115

and a little bit of frontend logic.

It could even be a little more advanced, giving a preview of the exact time the share would expire:

![image](https://user-images.githubusercontent.com/36276517/195466472-6313254d-e5da-4651-ac41-f453724dd3e9.png)

What do you think?

**Comment by stautonico** [comment]
I plan on replacing my personal sharing service that I host on my website with this one, so I'm personally invested in making this tool as feature complete as I can haha

**Comment by stonith404** [comment]
That sounds even better! If you have time it would be really nice if you can do that:) 
How would you solve the expiration "never" with this solution?

**Comment by stautonico** [comment]
I was thinking about putting a checkbox that says something like "Never expires" and when clicked, it either greys out or just hides the time selection inputs. Definitely **NOT** just entering 0 into the fields, that's not very intuitive.

**Comment by stonith404** [comment]
👍 That's probably the best solution

**Comment by stautonico** [comment]
I wrote the first PR during a boring class, but I have a feeling like this one is going to take a little longer. I'll start it tomorrow or Friday probably.

**Comment by stonith404** [comment]
These boring classes can make you creative. I built almost the whole project in boring classes.
Take your time and if you need anything just write me :)

**Comment by stonith404** [comment]
Should I close #11 ?

**Comment by stautonico** [comment]
Yeah since I'm going to re-write it anyway
