### ISSUE TITLE
Cannot Pull docker image

### ISSUE THREAD

**Issue by cyber9** [stonith404/pingvin-share#123]
root@Docker1:~# docker pull stonith404/pingvin-share:v0.12.1
v0.12.1: Pulling from stonith404/pingvin-share
3f9582a2cbe7: Pull complete 
94e5d5746476: Pull complete 
11587a4aecf2: Pull complete 
d1ed1db27c1b: Pull complete 
8f4c41bcb791: Pull complete 
b08dabf715fc: Pull complete 
b89c60bc4dc6: Pull complete 
07756ffae312: Pull complete 
272f066a26ba: Pull complete 
c01b3e81b3b6: Pull complete 
ba1f271d6f15: Pull complete 
80b0b396146e: Pull complete 
8fe6e92334d0: Extracting [==================================================>]  70.05MB/70.05MB
6f362cfa7c8f: Download complete 
6592ea8f09d7: Download complete 
dafbc927f451: Download complete 
4f4fb700ef54: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: failed to Lchown "/opt/app/backend/node_modules/buffer-equal-constant-time/.npmignore" for UID 718322462, GID 454177323 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /opt/app/backend/node_modules/buffer-equal-constant-time/.npmignore: invalid argument

I have attempted to pull several versions of this. no luck. I would like to try Pingvin-share but cannot get it to pull. Can you help?

**Comment by bacardiman04** [comment]
Getting the same error

**Comment by stonith404** [comment]
This issue was already raised before #107. Maybe you find a solution there or you can participate in the discussion.
