### ISSUE TITLE
🚀 Feature: Ability to Manage User Uploads and Delete Files

### ISSUE THREAD

**Issue by Rabenherz112** [stonith404/pingvin-share#124]
### 🔖 Feature description

I would like to be able to manage all uploads made by users, allowing me to delete any files that are inappropriate, excessively large, or otherwise undesirable for hosting on my server.

### 🎤 Pitch

Upon implementation of this feature, administrators can access a dedicated section to managing user uploads. From there, they can sort and search through all uploaded files, allowing them to identify any large or unnecessary files, or locate files associated with a particular user. Unwanted files can then be selected and deleted to preserve storage space and ensure that the platform remains clean.

This feature would be especially important for public sites where administrators need to maintain site security and ensure that all uploaded files comply with legal requirements. With the ability to manage user uploads, administrators can ensure site security and safeguard against malicious files as well as help prevent any illegal content from being hosted on their platform.

**Comment by stonith404** [comment]
Thanks for your feature suggestion. I'll look forward to implement this in the future, but this could take some time.

**Comment by johnnny1337** [comment]
This would be awesome! An addon to this would be if we could see the IP of the uploader and maybe geolocation as admins.

**Comment by joel72265** [comment]
even a History page that displays the following information below would be great

Date (Upload) |  Filename  |  Users Name  |  Size |  Download count

**Comment by stonith404** [comment]
This was implemented by @SFGrenade and will be released ASAP. If you have any additional suggestions for this feature, feel free to create a new feature request.
