### ISSUE TITLE
🚀 Feature: Share view UI improvements

### ISSUE THREAD

**Issue by Hukuma1** [stonith404/pingvin-share#126]
### 🔖 Feature description

<img width="713" alt="image" src="https://user-images.githubusercontent.com/54511555/224564973-5d0c578a-ec54-4884-b811-6af224f48dc5.png">

1. 'Sort by' default options. Right now it seems to default to last uploaded showing top-to-bottom. Would be really nice to be able to set it to alphabetical order, for example. Workaround right now is to upload the files in reverse order. (This won't work if the user is uploading a whole batch of files though, instead of one-by-one.) Not sure if an expansion of sort ability under for Size category would also be useful to some?

2. Preview button opens a modal instead of a new tab. Maybe still leave an option for people to allow the choice between modal/new tab. But modal seems cleaner for previews without sending the person to another screen. (On the note of preview, it seems `.PSD` shows up as being able to be previewed, but fails to open. In Chrome at least. It's probably incorrectly tagging it as being supported?)

3. `Download all` button seems to have a hard-coded value of pingvin-share in the zip file name. Maybe pull the name from the admin options in case the user changed the service name? Or maybe even simplify it further to `shareName-all-files.zip` if not even just `shareName.zip`?

`pingvin-share-michaels-prom-photos.zip`
`michaels-prom-photos-all-files.zip`
`michaels-prom-photos.zip`

### 🎤 Pitch

Just opinions on improvements from daily driving this great piece of software! Nothing above stated as fact. ;)

**Comment by stonith404** [comment]
Good points! 
For point one do you think the user should be able to select how the list should be sorted or is it enough that the files are sorted in  alphabetical order?

You're right a modal would be nicer, I could add a modal with the preview and below a button to open it in a new tab. `.PSD` should not be supported as the browser does it not support natively, I'll look into it.

Point three is already fixed in f55aa805167f31864cb07e269a47533927cb533c :)

**Comment by Hukuma1** [comment]
For the sort, I think it's a fast win if it goes alphabetical to begin with. Just seems like a more typical sort option in my opinion. And if further down the road you want to give people the option to sort by reverse alphabetical order or sort by size, maybe it could be implemented like in Nextcloud? It just adds little carrots right in the UI for people to adjust/override the sorting:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/54511555/224569126-20e8a448-e04d-436c-afb9-3371e7e4594c.png">

**Comment by Hukuma1** [comment]
`.txt` is not showing the preview button for some reason. That one definitely should work in a browser.

**Comment by Hukuma1** [comment]
I agree the way you have it now is best! But why not code `PSD` to be hidden instead? Is that possible? So instead of whitelisting a bunch of known working ones, we hide the ones we know don't work?

**Comment by stonith404** [comment]
That's true but there are so many `image` mime types: https://mimetype.io/all-types/#image. But I think I could black list the most common mime types that aren't supported like `PSD`

**Comment by stonith404** [comment]
Added in the newest release.
