### ISSUE TITLE
🐛 Bug Report: Uploading 0 byte files causes a hang

### ISSUE THREAD

**Issue by Hukuma1** [stonith404/pingvin-share#127]
### 👟 Reproduction steps

https://user-images.githubusercontent.com/54511555/224586912-f92ed4eb-0dad-4de9-b186-37315691920e.mp4

### 👍 Expected behavior

Upload like normal files?

### 👎 Actual Behavior

Spinning wheel of death. Even though these files are obviously empty garbage, it should still allow an upload? The only use case here is imagine if the filename is what had the relevant information, not what's actually inside the file. We do not see Pingvin popup the share link modal, nor are any files copied into the shared directory that gets made. The folder is made, however, and possibly that means it's also in the database. It also does NOT show up in the shares if I refresh. So this might possibly cause ghost shares in the database. (preventing you from making a share with the same name due to a database conflict)

If there's a mix of normal files (aka >0 bytes) and one that isn't, it'll cause this break as well.

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Thanks for your report. This was fixed in f82099f36eb4699385fc16dfb0e0c02e5d55b1e3.

**Comment by stonith404** [comment]
Fixed in the newest release.

**Comment by Hukuma1** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/54511555/225083816-e2a67e00-4824-4253-82a7-62a2d1d405c4.png">


```
[Nest] 260  - 03/14/2023, 5:04:30 PM   ERROR [ExceptionsHandler] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
03/14/2023 10:04:30 AM
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
03/14/2023 10:04:30 AM
    at new NodeError (node:internal/errors:399:5)
03/14/2023 10:04:30 AM
    at Function.from (node:buffer:326:9)
03/14/2023 10:04:30 AM
    at FileService.create (/opt/app/backend/dist/src/file/file.service.js:51:31)
03/14/2023 10:04:30 AM
    at async FileController.create (/opt/app/backend/dist/src/file/file.controller.js:31:16)
```

**Comment by Hukuma1** [comment]
Windows. Right-Click -> New -> Text Document or Bitmap image

Here are my test files: https://we.tl/t-lmrRZcvS50

**Comment by stonith404** [comment]
Oh, I see it's again an issue only in chrome :/ I'll look into it

**Comment by Hukuma1** [comment]
https://www.w3schools.com/browsers/

Not a fan of Google either, but at 80% market share yeah, Chrome should be supported. :/

Btw the new modals previews are 🔥🔥🔥!!

**Comment by stonith404** [comment]
Yeah sure, every modern browser must be supported. It's just that I forget sometimes to test everything in chrome too.  
On my roadmap are Cypress tests, with them I would be able to test the app easily in all browsers but currently I don't have the time for it.

Thanks :) It was a really good suggestion to add modals because a user can now preview files much faster.

**Comment by stonith404** [comment]
Btw. I've just released the fix but it can take up to an hour to finish the build of the image.

**Comment by Hukuma1** [comment]
Works great. Thanks for the fix!
