### ISSUE TITLE
🐛 Bug Report: I couldn't run Pingvin

### ISSUE THREAD

**Issue by krintek** [stonith404/pingvin-share#129]
### 👟 Reproduction steps

I just created a docker-compose stack in Portainer,

![image](https://user-images.githubusercontent.com/87629857/224719688-0893989c-493f-4c32-9aba-05bf65b48e23.png)

The logs are present below,

[_pingvin_logs.txt](https://github.com/stonith404/pingvin-share/files/10957967/_pingvin_logs.txt)

### 👍 Expected behavior

It should open the homepage of Pingvin.

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/87629857/224719274-2b29c50c-c617-466f-a0ff-f57c331c3174.png)

### 🌐 Browser

Brave Browser

**Comment by krintek** [comment]
![image](https://user-images.githubusercontent.com/87629857/224725802-814d9d4c-0985-4b94-9fe3-087b51050b60.png)

stonith404/pingvin-share:v0.11.1 is working perfectly fine!

But the latest version isn't working properly, please fix it soon!

**Comment by krintek** [comment]
> That's a strange issue. It might be an issue with the package `sharp` that was added in the latest release: https://stackoverflow.com/questions/67580821/nodejs-illegal-instruction-core-dumped-error-after-using-sharp-library
> 
> Which CPU does your server have?

Intel Core Duo

**Comment by stonith404** [comment]
It's really difficult to debug for me as I can't reproduce this. Could you try the following steps?
1. Create a fresh installation of Pingvin Share (this will remove your data if you don't back it up)
```bash
cd pingvin-share
docker compose down
rm -rf data
docker compose pull
docker compose up -d
```
2. Try to install the stand-alone installation and check if this works

**Comment by krintek** [comment]
It still shows the same error, thanks for helping! Guess I have to stop using your service cause of my shitty CPU. Hope your project touch the peak :)

**Comment by stonith404** [comment]
So the stand alone installation didn't work either? Sorry that I can't help you further here... Thanks for your patience and for your raised issues!

**Comment by Hukuma1** [comment]
The issue is Sharp library uses some instructions not supported by the Intel Core Duo probably. Since prior versions of Pingvin Share didn't have Sharp for custom logo creation, it worked on that older machine.

You could try testing this by exec'ing into the Pingvin container and trying to downgrade Sharp package like the link above suggested?

**Comment by Hukuma1** [comment]
Do you use Portainer to manage your Docker containers by any chance? The console button is really handy in these types of situations.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/54511555/225075834-803f410f-4f35-4aad-888f-91d492dda6bf.png">

The only other alternative would be if @stonith404 uses an older Sharp version. But regardless, he would still would a) need to know what the last version would support your CPU, and b) if using the older version still allows him to use the features in Pingvin Share.

**Comment by krintek** [comment]
Yea I use Portainer! 
Unfortunately I couldn't even use the console since it shows the same error of logs in a fancy way lol

I'm searching for a mini PC, I really like Pingvin I can't be without it so probably getting an old PC [Dell Optiplex 3070 i3-9100T]

**Comment by stonith404** [comment]
@krintek A Raspberry PI is awesome if you need a mini PC. I'm running Pingvin Share, Nextcloud and many more services on a Raspberry Pi 4 8GB. As long as you don't have much traffic a Raspberry Pi is enough.

**Comment by krintek** [comment]
Raspberry Pi nowadays costs a kidney lol I live in India, here the Dell Optiplex 3070 i3 costs $185. I think it would work well with 32GB RAM and 2TB Pcie Gen 3 SSD. You finally made me a reason to buy a new mini PC after 13 years lol.

**Comment by specoff** [comment]
Core Quad 6600 - same error. Bad, very bad.

**Comment by Ectalite** [comment]
I'm getting the same error on latest version (0.15.0) on my Synology DS713+ with an INTEL Atom D2700.
