### ISSUE TITLE
❓ Question: Is there a recommended Nginx reverse proxy configuration file for pingvin?

### ISSUE THREAD

**Issue by sebasdt** [stonith404/pingvin-share#130]
### 🙋‍♂️ Question

Hi,

I've been struggling to get nginx proxy manager working, so would like to use the original nginx proxy.
Do you have a recommended/example config for proxying pingvin?

**Comment by sebasdt** [comment]
Thanks, man!
that answers my question.
Googled arround mixed some configs together and this was the result.
As you said can't guarantee it will work on your setup may differ from mine and its just a template.
Here is my config with SSL:
`server {
    listen 80;
    server_name Your_domain.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name Your_domain.com;

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/Your_domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/Your_domain.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/Your_domain.com/fullchain.pem;

    #added security, should be more than enough. Also should disallow indexing the page on search engines.
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
    ssl_prefer_server_ciphers on;

    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Content-Security-Policy "frame-ancestors 'self'";
    add_header X-Frame-Options DENY;
    add_header Referrer-Policy same-origin;

    # Add X-Robots-Tag header for indexing
    add_header X-Robots-Tag "noindex, nofollow, nosnippet" always;

    location = /robots.txt {
      add_header Content-Type text/plain;
      return 200 "User-agent: *\nDisallow: /\n";
    }
    # Set longer timeouts for uploads and downloads
    client_max_body_size 100M;
    client_body_timeout 60s;
    client_header_timeout 60s;
    keepalive_timeout 60s;
    send_timeout 60s;


    location / {
        proxy_pass http://pingvin.Ip:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
`

Should I close the issue or would you like to add more notes/comments?

**Comment by stonith404** [comment]
Nice! So if it works you can close this issue else just add another comment :)

**Comment by sebasdt** [comment]
Thank you for this awesome project! Good luck!
