### ISSUE TITLE
❓ Question: Change port on Docker.

### ISSUE THREAD

**Issue by Xmonpl** [stonith404/pingvin-share#131]
### 🙋‍♂️ Question

How do i change a port from 3000 to another port in docker instance? Maybe env variable or smth?

**Comment by Xmonpl** [comment]
yes.. i know XD!

**Comment by WaxenSs** [comment]
Hey, I have the same problem as you, can you explain how you did it?

**Comment by Xmonpl** [comment]
Bro this issue is my brain dead and you too, look haha ![image](https://github.com/stonith404/pingvin-share/assets/31248347/f4e55b18-9384-49a9-94bc-c88fa5144fe6)
