### ISSUE TITLE
🐛 Bug Report: bool config variable can't be changed

### ISSUE THREAD

**Issue by newargus** [stonith404/pingvin-share#133]
### 👟 Reproduction steps

Bug concerning Admin interface to handle boolean value due to defautvalue feature

### 👍 Expected behavior

Error in recent change made on frontend on component "AdminConfigInput.tsx", line 27.
 
booleanValue:
        configVariable.value ?? configVariable.defaultValue == "true",

should be: 
booleanValue: (configVariable.value==null) ?  configVariable.defaultValue == "true" : configVariable.value=="true" 

### 👎 Actual Behavior

If value has been set 1 time, you cannot change it again, due to wrong type given in component initialisation.
Test to evaluate as booelan is missing.

### 🌐 Browser

All browser

**Comment by stonith404** [comment]
Thanks for your report! I've just fixed it in 0e5c67327092e4751208e559a2b0d5ee2b91b6e3. Usually I wouldn't recommend you to run a Pingvin Share version that isn't released yet. But without your report this bug would probably have landed in production.

**Comment by newargus** [comment]
Thanks.. Good work by the way! Very inspiring dev.
