### ISSUE TITLE
❓ Question: Is there a way to mirgate from and to standalone and docker?

### ISSUE THREAD

**Issue by sebasdt** [stonith404/pingvin-share#134]
### 🙋‍♂️ Question

Hi there, 

I saw last week that it supports both standalone applications and Docker containers. I was wondering if there is a way to migrate applications from standalone to Docker, and vice versa, without having to reconfigure everything from scratch. 

Thank you for your help!

**Comment by stonith404** [comment]
All data is stored inside the `backend/data` and `frontend/public/img` folder.

Migrate from standalone to Docker Compose:
1. Download the Docker Compose file like in the installation instructions
2. Copy the `backend/data` folder into the same folder as your Docker Compose file
3. Copy  the `frontend/public/img` inside the `data` folder which you have previously copied
4. Follow the rest of the Docker installation instructions

At the end it should look like this:
```
├── data
│   ├── img
│ 
└── docker-compose.yml
```

Migrate from Docker Compose to standalone:
1. Clone the repo
2. Replace the `frontend/public/img` folder with the `data/img` folder from your Docker Compose project
3. Replace the `backend/data` folder with the `data` folder and remove the `img` folder in it
5. Follow the rest of the standalone instructions

**Comment by sebasdt** [comment]
Thank you,

I will give it a try somewhere this week.

**Comment by sebasdt** [comment]
Oh yes sorry It worked for me!
