### ISSUE TITLE
❓ Question: How to change default color schema to light?

### ISSUE THREAD

**Issue by coaz** [stonith404/pingvin-share#136]
### 🙋‍♂️ Question

Default color schema is dark. I want to modify it to light. How can I do it? Configuration page doesnt have this.

**Comment by stonith404** [comment]
You can change it on the account page. You can't change the theme globally for every user, by default it uses the system theme.
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/58886915/228145972-f760745d-97ea-42b1-8476-72558e504470.png">

<img width="697" alt="image" src="https://user-images.githubusercontent.com/58886915/228145982-e7543779-bcff-44dd-92b9-71a4f21fc2c9.png">

**Comment by coaz** [comment]
Thank you, my question is how to change system color to light. I can’t find
it in “Configuration”

**Comment by stonith404** [comment]
Like I said you can't change the color schema globally, only per user.
To change it click the settings gear -> My Account -> Scroll down to "color schema"
 See my screenshots above.

**Comment by coaz** [comment]
In a past version, I remember that light was the system schema but now,
there is a black schema. How can I put that color for system ?

**Comment by stonith404** [comment]
By default it still uses the system color schema. But as I said earlier you can change it per user to "light", "dark" or "system".

**Comment by coaz** [comment]
Actually, system color schema is dark. I want to change system schema to
light. Cans you guide me to do that?

With this form, all users will have as default light and then, each user
can change it to dark

**Comment by stonith404** [comment]
As I said before you **can't change the default color scheme globally for every user**. By default it uses the clients system theme. 

I don't know which OS you're using but you can easily google e.g `change system theme windows` to get a guide to change your system theme.

**Comment by coaz** [comment]
Thank you, now I understood. System color is "server color", I think it was
related with next js. I use Ubuntu Server 18.

I already change default color in pingvin modifying file usePrevefernces.ts
on /frontend/src/hook

from
const defaultPreferences = [
  {
    key: "colorScheme",
    value: "system",
  },
];

to
const defaultPreferences = [
  {
    key: "colorScheme",
    value: "light",
  },
];

**Comment by stonith404** [comment]
Yes this should work 👍
