### ISSUE TITLE
How to change where to store the data

### ISSUE THREAD

**Issue by xzakier** [stonith404/pingvin-share#137]
Idle is this is a bug or I am doing something wrong, but I used the docker compose to deploy it and I just edited the volume :

version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "./root/vv/filehost:/opt/app/backend/data"
      - "./root/vv/filehost/images:/opt/app/frontend/public/img"

I think the path for the uploaded files should be now ./root/vv/filehost but for some reason it's still on ./data any help?

note:  i am using rclone to mount my onedrive to ./root/vv/filehost but that make no difference because the goal from rclone is to make the cloud storage as a local drive and its working as local applications i use but its not working with pingvin-share

**Comment by stonith404** [comment]
There shouldn't be a file size limit. Do you get any errors?

**Comment by stonith404** [comment]
Closing this because there was no response. Feel free to reopen it, if the issue still occurs.

**Comment by adamzvolanek** [comment]
I will perhaps re-word or add to the question. Is it possible to have the `(../data)/uploads` directory be located as a separate volume? Meaning currently my `/data` and `/data/uploads` are a part of the same volume in my docker container. I would like the ability to have the container/docker data stored in `/data` but have the `uploads` directory be on a separate disc.


For context: I have a dedicated ssd for all of my dockers' configuration, image(s), and databases, however my bulk storage is on a separate physical disc.

**Comment by stonith404** [comment]
@adamzvolanek Okay I see. This should be possible by changing the volumes like this:
```yml
volumes:
      - "/your-ssd/pingvin-share/pingvin-share.db:/opt/app/backend/data/pingvin-share.db" # make sure to create the file before starting the container 
      - "/your-ssd/pingvin-share/images:/opt/app/frontend/public/img"
      - "/external-ssd/pingvin-share-uploads:/opt/app/backend/data/uploads"
```

**Comment by adamzvolanek** [comment]
> ```yaml
> volumes:
>       - "/your-ssd/pingvin-share/pingvin-share.db:/opt/app/backend/data/pingvin-share.db" # make sure to create the file before starting the container 
>       - "/your-ssd/pingvin-share/images:/opt/app/frontend/public/img"
>       - "/external-ssd/pingvin-share-uploads:/opt/app/backend/data/uploads"
> ```

When you mention to create the file before starting the container, can it be as simple as `touch /your-ssd/pingvin-share/pingvin-share.db`? What permissions?

I was hoping to be able to deploy the pingvin-share straight from docker-compose to full-use without additional file modifications but maintain the upload directory to be separate from the server's primary share location for security reasons.

**Comment by stonith404** [comment]
@adamzvolanek Yeah exactly `touch /your-ssd/pingvin-share/pingvin-share.db` should be sufficient. I'm not really sure about the permissions but I would try to create the file with the same user as you run the docker commands.
