### ISSUE TITLE
❓ Question: ¿How can I create a new field in upload modal and populate it to database?

### ISSUE THREAD

**Issue by coaz** [stonith404/pingvin-share#141]
### 🙋‍♂️ Question

I want to add a new field called "Allow to download?" wich is a boolean. I already create that field in showCreateUploadModal.tsx and it displays in the form. 
I also modify the Share table in database to have this field.

When I send the file, all the other information of the share is passing to database but not this field. What i´m missing? 

I log the share.service.js file before create the registry in the database and i get this:

0|pingvin-share-backend  | {
0|pingvin-share-backend  |   id: 'UxMzU1N',
0|pingvin-share-backend  |   expiration: 'never',
0|pingvin-share-backend  |   recipients: [],
0|pingvin-share-backend  |   security: undefined
0|pingvin-share-backend  | }

Can you help me?

![imagen](https://user-images.githubusercontent.com/27463067/229871214-eb35ef8b-51d2-4764-8242-d31be075e1cb.png)

![imagen](https://user-images.githubusercontent.com/27463067/229871430-269b0110-b1d3-4d55-ba7f-7aa835908caa.png)

**Comment by coaz** [comment]
I modify this files

**Comment by stonith404** [comment]
Okay, so does it work now?

**Comment by stonith404** [comment]
Does the property even get sent to the backend? You can test it by analyzing the request body in the browser dev tools.

**Comment by coaz** [comment]
No, it doesn’t. Field info doesn’t populate to the database.

In log file I see the same info.

**Comment by coaz** [comment]
Already update that function in frontend. Also modify shares.type.ts in
front end.

[image: imagen.png]

**Comment by stonith404** [comment]
I'm out of ideas. I can't really help you without seeing the whole code.

**Comment by coaz** [comment]
What if I need to create one extra field in upload form and save it in
share table.

What should I do? Can you guide me?

**Comment by stonith404** [comment]
I apologize for being slow to respond as I am currently on holiday.
I greatly appreciate your interest in the project, but unfortunately, I do not have the time to provide assistance with custom modifications. I volunteer my time to work on Pingvin Share for free, and when multiple people require assistance with modifying the project, it becomes difficult for me to balance my time effectively. Thank you for your understanding :)

**Comment by coaz** [comment]
Thank you @stonith404.  Dont worry. The idea of an open source project is that the community help each others to improve it. I think other people can also help answering questions.

To add a custom field I change this files in the frontend. Then I run the command "npm run build" there:

src/types/share.type.ts
src/components/share/FileList.tsx
src/components/upload/modals/showCreateUploadModal.tsx
src/services/share.service.ts

After that, i modify this files in the backend. 

src/share/dto/share.dto.ts
src/share/dto/createShare.dto.ts
src/share/share.service.ts
prisma/schema.prisma

After that in prisma folder I run this command: "npx prisma db push" and back in backend I run this command "npm run build". 

Now this field is working.
