### ISSUE TITLE
🚀 Feature: S3 API support

### ISSUE THREAD

**Issue by YunchaoZheng** [stonith404/pingvin-share#142]
### 🔖 Feature description

Adding another choice to store uploaded files beside local disk

# AWS S3 API
- Storing uploaded files in S3 bucket and fetching them if called. 
- Docs of [AWS s3 JavaScript SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html). 
- Passing S3 secrets by ENVIRONMENT VARIABLE

Typically, here are variables that required on most occasions
```env
ACCESS_KEY_ID=
SECRET_ACCESS_KEY=
BUCKET_NAME=
S3_ENDPOINT=
```
AWS, Cloudflare, Google cloud, Azure ... etc. support S3 API compatible

### 🎤 Pitch

This is quite useful if deploying on cloud edge platforms. Since cloud platforms basically provide quite limited disk space.

**Comment by pierrbt** [comment]
@YunchaoZheng, well this would totally change the way to upload files, isn't this a bit unnecessary, the goal of this is to self-host an instance, but create a S3 next to a vps to host it is a bit too complex isn't it ?

**Comment by stonith404** [comment]
Yeah it's true. If you use S3 you don't really own your files and this is one of the most key feature of Pingvin Share. What do you think @YunchaoZheng?

**Comment by YunchaoZheng** [comment]
Yes, true indeed. Before the time I was thinking that implement of S3 would bring benefit for deploying on Paas platform. 

Yes, it's quite opposite to Pingvin' Zen. 

Maybe we should leave the storage part to the vps manager.

Thank you for commenting : )  
@pierrbt @stonith404

**Comment by dillfrescott** [comment]
I think this would be a useful optional feature to have and it wouldn't complicate things for the self-hoster either.
