### ISSUE TITLE
🚀 Feature: I hope to have the registration function turned on and off

### ISSUE THREAD

**Issue by wisonlau** [stonith404/pingvin-share#146]
### 🔖 Feature description

Hope to make a management background, there is a super administrator, can manage all users, as well as configure website parameters, such as limit registration, limit upload and so on.

### 🎤 Pitch

Make the function more powerful

**Comment by stonith404** [comment]
This is already implemented, isn't it? An admin can already manage users, enable/disable the registration and limit the share size. What do you want to have implemented?
