### ISSUE TITLE
❓ Question:Whether Share Recipients Message can include share password?

### ISSUE THREAD

**Issue by meowth1006** [stonith404/pingvin-share#147]
### 🙋‍♂️ Question

Whether Share Recipients Message can include share password?
Available variables:
{creator} - The username of the creator of the share
{shareUrl} - The URL of the share
{desc} - The description of the share
{expires} - The expiration date of the share
There are currently no password variables.

**Comment by stonith404** [comment]
I don't really get your question. Do you want to request a new feature that allows to include the share password in the email?

**Comment by meowth1006** [comment]
Thanks for your reply. Yes, although I can enter the share password manually in the description, it would be more convenient if it could include the share password variable in the email.

**Comment by stonith404** [comment]
Okay. Would you mind to create a new issue with the feature template, so we can track and discuss the feature better?
