### ISSUE TITLE
🚀 Feature: healthcheck route / endpoint

### ISSUE THREAD

**Issue by keanrawr** [stonith404/pingvin-share#149]
### 🔖 Feature description

Have a lightweight `<HOSTNAME>/healthcheck` route or endpoint to monitor uptime.

### 🎤 Pitch

Since pingvin is fairly lightweight I currently use the hostname to check if my instance of pingvin is up, but it'd be simpler to have a dedicated health route or endpoint that I could point my monitoring service towards.

> Disclaimer: I'm mainly a python dev, so could be that this is already implemented and I didn't find it in the source code.

PS: I'm really loving the project 😄

**Comment by keanrawr** [comment]
> Thanks :) What should the health check endpoint return in your opinion?

In its most basic form a health check endpoint simply returns a 200 status and some simple string, like "ok".

But it can return more detailed reports like an indicator that the connection to the database is up and available.

**Comment by stonith404** [comment]
Added in 5132d177b8ab4e00a7e701e9956222fa2352d42c and will be released in the next release :)

**Comment by stonith404** [comment]
Added in `v0.15.0`
