### ISSUE TITLE
🐛 Bug Report: Completely filled PVC, cannot logout

### ISSUE THREAD

**Issue by gogo199432** [stonith404/pingvin-share#151]
### 👟 Reproduction steps

My data volume was completely filled up with uploads by accident. Incidentally this was done through a different user so as admin I cannot manage their files.

### 👍 Expected behavior

To be able to logout and free up space.

### 👎 Actual Behavior

When I tried to log out, the app returned 500 error because it was unable to properly modify the DB, I assume because it didn't have any free space to do it. 

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Please share the logs. You can get them with `docker compose logs`.

**Comment by gogo199432** [comment]
Sadly I don't have the logs anymore since I "fixed" the issue on my end by moving the uploads folder to a much bigger drive. You can probably reproduce it by giving a relatively small drive, like 100MB to the app and then upload something very close to, or at 100MB. It should start having issues editing the DB since it needs a couple of KBs for the WAL.

My suggestion would be to keep a couple of MB-s reserved from the whole drive for the DB.

**Comment by stonith404** [comment]
Yeah, good point. Maybe we just could disallow an upload if not more than 2MB are available.
