### ISSUE TITLE
❓ Question: Is there a way to pause, stop or cancel the current upload? 

### ISSUE THREAD

**Issue by sebasdt** [stonith404/pingvin-share#156]
### 🙋‍♂️ Question

Hi!

So I've had this thought for a while now I haven't found a way to at least cancel the current upload process..
The way I do it is just close the Pingvin-share website tab, it doesn't seem the right thing to do. 

Not sure if Pingvin removes the uploaded files after an upload did not complete.

It would be convenient if these features would be added or explained why it's not yet implimented.

**Comment by stonith404** [comment]
Currently not, but there is an open issue #153. That's definitely a must-have feature.
