### ISSUE TITLE
🚀 Feature: Define the number of characters in the link

### ISSUE THREAD

**Issue by ro78** [stonith404/pingvin-share#157]
### 🔖 Feature description

Allow admin to specify how much random characters to use when creating the share link

### 🎤 Pitch

Today, it seems that the link created randomly contains 7 random letters/numbers. Would be nice to be able to define, in the admin part, the minimum numer of characters, to make it harder to "bruteforce".

**Comment by pierrbt** [comment]
If you want your share to be secured, can't you just add a password to it @ro78  ?

**Comment by pierrbt** [comment]
@stonith404 I think this can be closed due to inactivity
