### ISSUE TITLE
🚀 Feature: Auto-delete file after expiration (or option to force delete after expiration)

### ISSUE THREAD

**Issue by ro78** [stonith404/pingvin-share#158]
### 🔖 Feature description

Automatically delete files of expired shares, or add an option during upload to delete files when the share is expired.

### 🎤 Pitch

I tried to create a 1 minute share, and after the expiration, even if the link can't be used anymore, the files are still on the disk.

It would be nice to automatically delete files of expired shares, or add an option during upload (when we define the expiration period) to have a checkbox to ask for file deletion after expiration.

**Comment by stonith404** [comment]
The expired shares get completely removed every hour as you can see  [in the code](https://github.com/stonith404/pingvin-share/blob/main/backend/src/jobs/jobs.service.ts#LL20C1-L20C1). Do you think this is enough or should there be an option to change the interval for deleting expired shares?

**Comment by pierrbt** [comment]
I think this issue can be closed
