### ISSUE TITLE
Alternative to file-hosting services

### ISSUE THREAD

**Issue by JediMaster25** [stonith404/pingvin-share#16]
Does this work as an alternative to file-hosting services like mega, Keep2share, 1fichier, Uploaded, Rapidgator, Mediafire, Fileflash, etc?

And if not could you implement the necessary features? Like premium accounts, automatic monero payment to get a subscription, etc. With a different price depending on the subscription time. For example $5 for a month, $10 for three months or $30 for a year.

- [Verifying a payment in Monero in an automatic manner, without a third-party or a full node](https://monero.stackexchange.com/a/12888)

**Comment by stonith404** [comment]
Yes this could be an alternative to them. I'm not really sure what you mean with premium accounts and automatic Monero payments, could you clarify that?

**Comment by JediMaster25** [comment]
This services often have a limited speed rate and number of files for free users and then have a premium subscription for a given number of months that allow users to download files without limits.

The automatic payments means that the website itself would check when someone makes a payment through monero, or any other of the private cryptocurrencies, so that they get a subscription when they make the payment without the need for manual verification.

**Comment by JediMaster25** [comment]
Also if you implement this for this project I can offer you a 100 € bounty.

[Premium subscription and automatic and private crypto payment](https://git.disroot.org/hirrolot19/jedi-archives/issues/8)

I'm offering a bounty of 1k € for all completing the issues here

[Turn stash-box into a file-hosting archive](https://git.disroot.org/hirrolot19/jedi-archives/milestone/183)

**Comment by stonith404** [comment]
Sorry I'm not interested. Your suggestions are against the philosophy of the project. Pingvin Share shouldn't cost any money for the hoster or the downloader.
But of course you can fork the project and implement it by your own.
