### ISSUE TITLE
🚀 Feature: Pastebin

### ISSUE THREAD

**Issue by Monkey999Human** [stonith404/pingvin-share#161]
### 🔖 Feature description

I am an enthusiastic user of the Pingvin Fileshare application, and I wanted to take a moment to express my appreciation for the fantastic work you and your team have done in creating such a useful and user-friendly file sharing platform.

While using Pingvin Fileshare, I have come across a feature that I believe would greatly enhance the overall functionality and convenience of the application. I would like to propose the addition of a Pastebin feature to Pingvin Fileshare.

The Pastebin functionality would allow users to easily share snippets of text, code, or any other form of text-based content with others. This feature is particularly useful for programmers, content creators, and collaborators who frequently need to share code snippets, configuration files, or any text-based information quickly and efficiently.

Thank you for your time and dedication to creating an exceptional product. I look forward to seeing how Pingvin Fileshare continues to evolve and provide an outstanding user experience.

**Comment by stonith404** [comment]
Thanks :) I think #145 is similar to your request. That's a good idea but I would like to prioritize other issues first, as I want to optimize the file sharing functionality before adding something like this. But that's definitely something that would be nice for the future!

**Comment by webysther** [comment]
Use https://privatebin.info/ for this, privatebin don't work good when talk about file share, so pingvin make sense. IMHO the focus need to be a better file share, I got limited bandwith and prefer to see improviments in this area, which is the main focus of the project.

**Comment by stonith404** [comment]
Good point, Pingvin Share should keep the focus on file sharing and stay as simple as possible. There are many other self-hosted Pastabin alternatives.

**Comment by Monkey999Human** [comment]
Hi @stonith404,

Thank you for considering the addition of a Pastebin feature to Pingvin Fileshare. I understand your priority is to optimize the file sharing functionality first, which makes sense.

Regarding the suggestion of using an external Pastebin service, I agree that there are several self-hosted Pastebin alternatives available. However, the reason I proposed adding Pastebin functionality to Pingvin Fileshare was to consolidate both file and text sharing within the same platform. This would offer users a seamless experience and eliminate the need to rely on multiple services.

Nonetheless, I appreciate your consideration and look forward to future improvements in Pingvin Fileshare's file sharing capabilities.

Best regards,

**Comment by pierrbt** [comment]
@Monkey999Human 
Hello,
I personally think that the pastebin feature is a great idea, but we have currently so many things to work on that it's a bit difficult to add a whole new system right now.

However, we should implement that feature later, or if someone wants to create a PR, but it's a massive change, so if no one try to add this, it might take a while.

**Comment by pierrbt** [comment]
@stonith404 Maybe we could add a need-help label because I don't think I'll have time to implement such a feature soon, taking into consideration all the others features and fixes already active

**Comment by stonith404** [comment]
To be honest this is a huge feature that would require a big refactoring like adding tables to the database and refactoring the whole frontend, only for this feature. I think we should keep the focus on file sharing. 
That's a reason why I don't like Nextcloud, they add many features that aren't related to storing files. I don't want that Pingvin Share gets too overblown.

I hope you can understand my points.
