### ISSUE TITLE
🚀 Feature: Add size and description in "My shares" list.

### ISSUE THREAD

**Issue by zikapanam** [stonith404/pingvin-share#164]
### 🔖 Feature description

![image](https://github.com/stonith404/pingvin-share/assets/120712878/66503fb8-57bc-4047-8cc2-684701803007)
I would like pingvin-share to display size and description as well of the share in "My shares" list.

### 🎤 Pitch

I think it could be useful to handle user space quota when it will be implemented. Also, the description is useful to know if a share can be safely removed or has be still shared.

**Comment by pierrbt** [comment]
Hello @zikapanam, I'm starting working on this

**Comment by pierrbt** [comment]
First preview : 
![image](https://github.com/stonith404/pingvin-share/assets/83456236/faccc02a-8e61-4593-a186-9993c2efdcd0)
![image](https://github.com/stonith404/pingvin-share/assets/83456236/54330d34-47cd-442b-864b-fc937e8bd428)

@stonith404, I've already talked about it in the discussions, but the share object only contains limited information, can you explain me why ? : 

```js
{
    "id": "M3Njk1N",
    "expiration": "2023-07-01T14:16:18.935Z",
    "description": "Hello les petits potes",
    "views": 0,
    "createdAt": "2023-06-23T14:56:29.167Z",
    "recipients": []
}
```

**Comment by pierrbt** [comment]
This is what this new feature looks like. Tell me what you think about it (@zikapanam @stonith404) : 
![image](https://github.com/stonith404/pingvin-share/assets/83456236/9ce73ffb-d56a-465f-8959-3d7f50362480)
![image](https://github.com/stonith404/pingvin-share/assets/83456236/65d6c705-0dc4-4f5a-ac4d-25cc3bec747e)
![image](https://github.com/stonith404/pingvin-share/assets/83456236/495d836b-e75e-4bfb-ba30-3f3e13c8efff)

If you are ok with this design I'll make a PR.

**Comment by pierrbt** [comment]
@zikapanam, the feature will be merged soon, following the #174 pr. But we'll have to wait the next release to have it on stable platforms

**Comment by stonith404** [comment]
I'll close this as soon as it is released. I think next week I should have time to release this.

**Comment by pierrbt** [comment]
This can be closed
