### ISSUE TITLE
🐛 Bug Report: Memory leak when uploading files with Chrome

### ISSUE THREAD

**Issue by zikapanam** [stonith404/pingvin-share#165]
### 👟 Reproduction steps

When i upload a video file of 5,4 GB (5 385 542 788 Bytes), i get this error in chromium :

![image](https://github.com/stonith404/pingvin-share/assets/120712878/534b0f43-9b72-478e-b878-aee28b2e1e03)

### 👍 Expected behavior

I put the max size to 10 GB on my pingvin-share instance. So i would expect to be able to upload 10GB file size.

### 👎 Actual Behavior

The 5GB video file i tried to upload two times didn't upload. I was forced to quit chromium and restart it.

I tried two times with a size of 1,6 GB (1 587 954 608 Bytes) video file and it worked each time. I could also download the file successfully from pingvin-share instance.

I'm on Linux Ubuntu 22.04

### 🌐 Browser

chromium Version 114.0.5735.106 (Build officiel) snap (64 bits)

**Comment by iUnstable0** [comment]
Have you tried uploading with different web browser?

**Comment by zikapanam** [comment]
I've just tried one time with Firefox on ubuntu 22.04 and it works. No error or problem.

**Comment by stonith404** [comment]
Looks like a memory leak. I'll look into it, thanks for reporting :)

**Comment by stonith404** [comment]
I also tried to reproduce it in a chromium browser but I don't have the issue. Is it maybe a chromium related issue, does it work for you now?

**Comment by iUnstable0** [comment]
Try turning off hardware acceleration. @zikapanam

**Comment by zikapanam** [comment]
Sorry for the delay, I've just checked that i have the hardware acceleration activated.

I plan to make a new test without hardware acceleration soon.

Thanks for your work and your advise,
++

**Comment by zikapanam** [comment]
Ok, the bug has vanished with or without hardware acceleration.

Pingvin-share Version 0.15.0 with chromium Version 116.0.5845.110 (Build officiel) snap (64 bits)

**Comment by stonith404** [comment]
Thanks for trying it again. Maybe it was a Chromium related issue that was fixed by them because I didn't really change anything in the upload logic. 
I'll close the issue for now. If you encounter the bug again feel free to reopen the issue again :)

**Comment by Lacni135** [comment]
Hi, when uploading a large file i'm getting somewhat the same issue.
The memory used by the browser grows until my ram is exceeded and a SBOX_FATAL_MEMORY_EXCEEDED pops and crashed the upload. From a quick search its looking like the memory is not getting cleared? or the garbage collector is not doing it's job.
Found this with a quick google search that might be useful:
https://stackoverflow.com/questions/66065824/sbox-fatal-memory-exceeded-when-uploading-a-file-in-chunks

**Comment by stonith404** [comment]
@Lacni135 Thanks for your report. It's a strange issue because I don't have any memory leaks if I test it. Which browser (with browser version) and OS are you using?

**Comment by Lacni135** [comment]
@stonith404 Using the latest Brave browser (chromium 116.5845.114) on windows 10.

**Comment by Lacni135** [comment]
After some testing i think I've identified the cause...
I was passing through a reverse proxy i setup (local->internet (dns)->back to local) and this seems to be causing the issue (no idea why though) accessing the site through localhost:3000 doesn't have the memory leak.

**Comment by stonith404** [comment]
Hm okay.

> accessing the site through ip:3000

Did you access Pingvin Share over a local IP or public IP when you didn't encounter the bug? 
Because maybe the cause is, that the bug only occurs if the upload speed isn't really fast. Because when you upload a file to localhost it's extremely fast.

**Comment by Lacni135** [comment]
I didn't encounter it when I used my local IP.

**Comment by stonith404** [comment]
I was able to reproduce the bug. I'll try to debug it further as soon as I have the time.

**Comment by stonith404** [comment]
I tried 3 hours to fix it but I didn't find any solution. I hope someone else can help to fix this...

The memory leak must happen in the [for loop on the upload page](https://github.com/stonith404/pingvin-share/blob/main/frontend/src/pages/upload/index.tsx#L70)

**Comment by axiomen** [comment]
I see this is closed, but I have a memory leak with Firefox while uploading large files. I don't have it with Edge.
