### ISSUE TITLE
🐛 Bug Report: Error: Command was killed with SIGKILL (Forced termination)

### ISSUE THREAD

**Issue by bplajzer** [stonith404/pingvin-share#166]
### 👟 Reproduction steps

Hi, first of all I would like to thank you since the project seems very interesting and helpful for file transfer. However, I have one problem when trying to launch I am not able to get the application to work. Can you take a peek to see if I'm doing everything correctly - or if it's an app error?

Docker logs:
![obraz](https://github.com/stonith404/pingvin-share/assets/9624712/80014b61-e8dc-4a8b-ae5d-7ee69a0dde08)

My setup looks like this:
host -> nginx-proxy-manager -> pingvin-share

Image:
![obraz](https://github.com/stonith404/pingvin-share/assets/9624712/1b2c7f03-3cb1-4f85-bce8-24d7e6a131af)

Docker-compose:
  pingvin-share:
    container_name: cld-pingwin
    image: stonith404/pingvin-share:latest
    expose:
      - 3000
    volumes:
      - "./pingwin/:/opt/app/backend/data"
      - "./pingwin/images:/opt/app/frontend/public/img"
    restart: unless-stopped

### 👍 Expected behavior

work

### 👎 Actual Behavior

fail to start container

### 🌐 Browser

firefox but not related to this

**Comment by stonith404** [comment]
Thanks for your report! I've never seen that error before and I can't reproduce this. 
Could you try the following steps?
1. Start again with a clean installation: 
```
rm -rf ./pingwin/ 
docker compose down
docker compose up
```
2. Test if it works, else remove the volumes  from your Docker Compose file temporarily and repeat step one.

Let me know if this works for you :) Please also share your operating system and CPU.

**Comment by bplajzer** [comment]
Thanks for fast reply, now that you've written it, it sparked another idea and I've found the cause.
The problem was the memory limit of the container - after changing this value everything started to work - currently the container takes 170mb of ram and the limit was set to 150.

For some reason I didn't include this bit of code in the description of the request - sorry

![obraz](https://github.com/stonith404/pingvin-share/assets/9624712/b92d8c7d-0d30-4cd9-b1af-456fe3d9ce6f)

**Comment by bplajzer** [comment]
fixed

**Comment by stonith404** [comment]
Glad that it works :)
