### ISSUE TITLE
🐛 Bug Report: unable to upload files larger than around 1 mb

### ISSUE THREAD

**Issue by notasandwich532** [stonith404/pingvin-share#168]
### 👟 Reproduction steps

when i try to upload a file larger than around 1mb it fails to upload and gets stuck retrying to upload it. 
![image](https://github.com/stonith404/pingvin-share/assets/136726991/14948f27-6fe8-473f-b9ec-b9eea21de242)
I get the same thing if i do it from my phone on firefox or bromite. 
[pingvin.log](https://github.com/stonith404/pingvin-share/files/11759951/pingvin.log)
here are the logs for the docker container
[docker-comepose.txt](https://github.com/stonith404/pingvin-share/files/11759954/docker-comepose.txt)
and my docker compose yml file
is there any other logs i could give here?

### 👍 Expected behavior

it should upload files larger than 1mb

### 👎 Actual Behavior

fails to upload and gets stuck retrying

### 🌐 Browser

firefox

**Comment by notasandwich532** [comment]
> 
yes, that could be the issue since i have no idea what im doing when it comes to nginx. 
![2023-06-15_22-04](https://github.com/stonith404/pingvin-share/assets/136726991/94b94384-4e10-45c5-b268-a7cc38bfc645)
here is the nginx config im using (got it off someone on discord) what way would you recommend setting up? 
![image](https://github.com/stonith404/pingvin-share/assets/136726991/661015e3-369e-4cfb-8f9d-d6087464af51)
this is what i get in /var/log/nginx/error.log (many lines of that) 
the red boxes are all just my domain
![image](https://github.com/stonith404/pingvin-share/assets/136726991/88ad13d2-ce37-4428-8148-eb0e0854687d)
and that is what i get in access.log

**Comment by notasandwich532** [comment]
i just realised this was an nginx issue and i needed to add a client_max_body_size line to it. could you close this issue? tho i am having some very weird upload issues with speed and it failing over the internet and lan, so i might test it a little more and make a bug report or something later.

**Comment by stonith404** [comment]
Nice! Yes sure, feel free to create other issues if you encounter other problems :)
