### ISSUE TITLE
🚀 Feature: Access share from webroot or /s

### ISSUE THREAD

**Issue by pierrbt** [stonith404/pingvin-share#175]
### 🔖 Feature description

Try to access a share from the webroot of the website, instead of using /share. The /share would stay usable but the link would be shorter that way.

### 🎤 Pitch

The link would be really smaller, and easier to write.

**Comment by pierrbt** [comment]
The miedleware should check this share Id exists to not display a empty share instead of 404 page when the path is not correct

**Comment by stonith404** [comment]
Good idea but this could get really complicated because we have to disallow routes like `share` or `account` because these are all routes.

My idea would be add a route called `s`. This would simplify the link too. E.g `share.example.com/s/myShare` would redirect to `share.example.com/share/myShare`. What do you think?

**Comment by pierrbt** [comment]
Yes, a /s path would be shorter ans very easy to implement.
But like there is not so much pages, a direct access wouldn't be that hard.

I've never used a middleware and Next in general, but, if the request does not match any page, it can looks for a share, and if it does not exixts, it sends to the 404 page

**Comment by stonith404** [comment]
The problem is (as far as I know) that we can't get all routes of the frontend in the middleware therefore we would have to hard code every route and this could get really annoying if we add more pages in the future.

**Comment by pierrbt** [comment]
Yes, you're right. I understand that this can leads to future problems. A /s path would still be shorter.

Link shorteners redirects from root but they are stable apps, so non way there is newer paths
