### ISSUE TITLE
🐛 Bug Report: Portainer Cannot find module 'next/dist/server/next-server'

### ISSUE THREAD

**Issue by codsec** [stonith404/pingvin-share#176]
### 👟 Reproduction steps

When im trying to install on my Asustor NAS, i used Portainer -> Docker -> pingvin

following this tutorial:
https://youtu.be/ZuYx7-xiNtQ

### 👍 Expected behavior

should work

### 👎 Actual Behavior

![image](https://github.com/stonith404/pingvin-share/assets/44205014/966a6090-74a0-4cd6-96cc-704c55885dc3)
![image](https://github.com/stonith404/pingvin-share/assets/44205014/44b78c1a-c8a8-413c-9c50-aa35b794adcb)

but my logs show this and i already have the nodejs installed in my NAS(not sure is is needed):
[_pingvinshare_logs.txt](https://github.com/stonith404/pingvin-share/files/11885383/_pingvinshare_logs.txt)

### 🌐 Browser

Chrome

**Comment by codsec** [comment]
> That's strange. Could you share your server specs and your docker compose file?

Im using a asustor 3304t and in the compose file i did exacly what the guy did on the tutorial video(https://youtu.be/ZuYx7-xiNtQ)

**Comment by stonith404** [comment]
I've just followed the tutorial and it works for me. Did you try to delete the container and start a fresh installation of Pingvin Share? 
Can you also try to run another Docker container and verify that the other container works? So we can make sure that the issue is not your setup.

**Comment by codsec** [comment]
> @codsec any news ?

No :/

**Comment by codsec** [comment]
> I've just followed the tutorial and it works for me. Did you try to delete the container and start a fresh installation of Pingvin Share? Can you also try to run another Docker container and verify that the other container works? So we can make sure that the issue is not your setup.

Yes i did the instalation from 0 3 times, same errors

**Comment by stonith404** [comment]
@codsec Nice!
Setting up a service with a domain isn't really Pingvin Share related. The easiest way is to use [Nginx Proxy Manager](https://nginxproxymanager.com/) in my opinion. There are many tutorials on Youtube and Google.

**Comment by codsec** [comment]
> @codsec Nice! Setting up a service with a domain isn't really Pingvin Share related. The easiest way is to use [Nginx Proxy Manager](https://nginxproxymanager.com/) in my opinion. There are many tutorials on Youtube and Google.

ok, well i have some questions, about big files, 1GB or more actually, they are slow for uploading? or is just my server?

and btw, in some cases like this would be good if we can know that % of the uploading and other thing, if i put 10days expire, the file will be deleted from my server or just the link to share? because if the file is no deleted how can i deleted manually the files that wont be used anymore?
![image](https://github.com/stonith404/pingvin-share/assets/44205014/c7efbb60-7f7a-4fcb-a8f6-17bc748bb473)

**Comment by stonith404** [comment]
The file upload shouldn't be that slow. When you're sure that it's an issue related to Pingvin Share, feel free to create a bug report. You could try to install another upload application to verify that only Pingvin Share is that slow.

Feel free to create a feature request for displaying the percentage :)

The files can't be downloaded if the share is expired but they still exist on the server for a short time. A job runs every hour that deletes all files of an expired share permanently from the server.
