### ISSUE TITLE
🐛 Bug Report: Share token required

### ISSUE THREAD

**Issue by babsz02** [stonith404/pingvin-share#177]
### 👟 Reproduction steps

Hello,
I use Piongvin share as a Wetransfert but also to auto host a presentation video.
I include the video link in my prospecting emails but a token probeleme appears after a while.

https://transfert.bastienmarchand.fr/api/shares/demo-timelapse/files/526782ce-47dd-47a1-83ad-22dfc3fe3e30?download=false

Can you help me?

### 👍 Expected behavior

Video should be available all the time

### 👎 Actual Behavior

![Capture d’écran 2023-06-29 à 10 05 28](https://github.com/stonith404/pingvin-share/assets/45185204/bb360a60-0868-4090-8c92-d4ec7ac09e2b)

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Could you explain the reproduction steps more precisely? If I click on your link I don't get the error.

**Comment by pierrbt** [comment]
@babsz02

**Comment by babsz02** [comment]
Sorry for my late reply,
It's really weird because the beug doesn't reappear.
I'll let you know if it happens again.
Thank you for your reactivity

**Comment by stonith404** [comment]
Okay, feel free to reopen the issue if the bug occurs again
