### ISSUE TITLE
❓ Question: is it auto-generate the share link ?

### ISSUE THREAD

**Issue by Zixim** [stonith404/pingvin-share#180]
### 🙋‍♂️ Question

Is there a way to auto-generate the share link, without having to click on the `generate` button ?

**Comment by pierrbt** [comment]
No, but it's easy to click the Generate button isn't it ? Do you think it would be better to auto-generate a link when we enter the page and then have the ability to change it ?

**Comment by Zixim** [comment]
You're right, it **is** pretty simple to click that button, at the same time it's an extra manipulation which could easily be eliminated.
Any non-technical user would be wondering why they need to click this in order to share a file.
Why not autopopulate the field, with a random English word of at least 6 letters. Similar to those randomly generated passphrases.

**Comment by stonith404** [comment]
Yeah right, we could remove the generate button and generate a link if the modal gets opened. how do you like this idea @pierrbt?

But I wouldn't take an English word but like now a random string.

**Comment by pierrbt** [comment]
Maybe we could keep the Generate link in he wants to create another one or reset it after a bad manipulation. But yes it could generate at the modal opening.

**Comment by pierrbt** [comment]
This issue can now be set on **waiting-for-release**

**Comment by stonith404** [comment]
Released :)
