### ISSUE TITLE
🚀 Feature: Customize primary color

### ISSUE THREAD

**Issue by Skillou** [stonith404/pingvin-share#183]
### 🔖 Feature description

Hello it is possible to let the user change the color with a simple variable or multiples variables ?

And u put a color picker who will fill this variable ?
So its a easy way to have custom color etc

### 🎤 Pitch

It can be more cool to customise is own web app.

**Comment by pierrbt** [comment]
Do you mean the UI color palette ?

**Comment by codsec** [comment]
> Do you mean the UI color palette ?

Yeah that would be cool, and add to the bar the toggle button for switch dark/light theme would be nice too, since is not everyone that goes to config tab

**Comment by stonith404** [comment]
@codsec Don't you think it's a bit unnecessary to add a button to change the theme in the header? I think very few users want to change the theme often. Additionally the system theme gets used by default. But maybe you can change my mind :)

**Comment by pierrbt** [comment]
@Skillou and @codsec : 

I also think that it's not the most useful feature, but anyway, if you want to try changing the theme, I think that that `mantine.style.ts` will help you with this. You can try changing the hex values from this file on a personal fork and then you'll see if it works (I'm not sure) and then if it works, you could try to create a new combo box in the config with presets themes. You can then PR the changes, it's as you want but I think there is more important things to work on right now.

PS, here is what the `mantine.style.ts` file looks like : 

```ts
import { MantineThemeOverride } from "@mantine/core";

export default <MantineThemeOverride>{
  colors: {
    victoria: [
      "#E2E1F1",
      "#C2C0E7",
      "#A19DE4",
      "#7D76E8",
      "#544AF4",
      "#4940DE",
      "#4239C8",
      "#463FA8",
      "#47428E",
      "#464379",
    ],
  },
  primaryColor: "victoria",
  components: {
    Modal: {
      styles: (theme) => ({
        title: {
          fontSize: theme.fontSizes.lg,
          fontWeight: 700,
        },
      }),
    },
  },
};
```

**Comment by pierrbt** [comment]
@Skillou, @codsec If none of you want to try to customize this file to change the theme, I think we can close this issue.

**Comment by stonith404** [comment]
Yeah, in think it makes sense to create your own fork if you want to customize the pages and theme of Pingvin Share,
