### ISSUE TITLE
🚀 Feature: Option to only unified the file without compression

### ISSUE THREAD

**Issue by webysther** [stonith404/pingvin-share#188]
### 🔖 Feature description

Control the compression level to reduce resource usage: pay bigger on storage to pay less in CPU.

This can be done only with .env for compression level, example: `COMPRESSION_LEVEL` on:

https://github.com/stonith404/pingvin-share/blob/46305ed1881fcebbd8e868ebe7b67bd6e6d16ddc/backend/src/share/share.service.ts#L107

### 🎤 Pitch

On have compressed files maybe don't make sense use compression, like images, videos or others correlated formats.

**Comment by pierrbt** [comment]
Yes this is quite an exciting feature, it would be useful to change the compression rate, we would need to add a new field in the db, and then add another input field in the frontend with a Native Select Input.

**Comment by webysther** [comment]
> Yes this is quite an exciting feature, it would be useful to change the compression rate, we would need to add a new field in the db, and then add another input field in the frontend with a Native Select Input.

I think initially can be done with a env var used in docker

**Comment by pierrbt** [comment]
Well, not everyone use docker, and it'll be easier to change it directly in the config panel. It's not really a big change, but it requires time

**Comment by stonith404** [comment]
> Well, not everyone use docker, and it'll be easier to change it directly in the config panel. It's not really a big change, but it requires time

Exactly and additionally we shouldn't mix config variables that are configurable through the frontend with environment variables. It could lead to confused users that don't know where to change these settings.

**Comment by webysther** [comment]
> > Well, not everyone use docker, and it'll be easier to change it directly in the config panel. It's not really a big change, but it requires time
> 
> Exactly and additionally we shouldn't mix config variables that are configurable through the frontend with environment variables. It could lead to confused users that don't know where to change these settings.

This maybe can be splited in two tasks, one for the environment variables and another to use the frontend.

**Comment by pierrbt** [comment]
Don't you think an input field in the website settings is enough ?

**Comment by webysther** [comment]
> Don't you think an input field in the website settings is enough ?

I think its, 0 for compression level means 'only agregate' like *.tar and should work fine for most users, so no more further advanced options.

**Comment by stonith404** [comment]
Released :)

**Comment by webysther** [comment]
Thanks a lot!
