### ISSUE TITLE
🐛 Bug Report: Confusion between GB and GiB

### ISSUE THREAD

**Issue by ThowZzy** [stonith404/pingvin-share#193]
### 👟 Reproduction steps

Go to `/admin/config/share` and set a number of "bytes" (Max Size). Once that's done check `/upload` and you will see it's not the right number. Unless my maths are off.

### 👍 Expected behavior

Having the right limit of GB or GiB.

### 👎 Actual Behavior

Edit: It should say "GiB" on the upload page instead, otherwise its confusing when trying to set a specific limit.

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
I think it should be correct. Can you give me an example of a number that is converted wrongly?

**Comment by pierrbt** [comment]
@ThowZzy

**Comment by ThowZzy** [comment]
When I want to set a limit of "20GB", that's what I'm doing:
![image](https://github.com/stonith404/pingvin-share/assets/61882536/89afc72f-a5ee-4fe4-bc28-911d295cf85d)

(If I set this number of bytes, I will have something like 18,62GB of limit on the upload page)

But its not right, so I need to use "20GiB" instead:
![image](https://github.com/stonith404/pingvin-share/assets/61882536/369e32b2-e4ab-4b1e-9ae4-00f7e3e55620)

"Octets" = "Bytes" btw

**Comment by stonith404** [comment]
You're right, thank you. I'll update this ASAP

**Comment by stonith404** [comment]
Released :)
