### ISSUE TITLE
Copy to clipboard button not working

### ISSUE THREAD

**Issue by Smallinger** [stonith404/pingvin-share#20]
Hey the button, copy to clipboard are not working.
i got the notification "Your link was copied to the keyboard."
but if i paste it anywahre my clipboard is empty.

![NVIDIA_Share_29-10-2022_23-20-33](https://user-images.githubusercontent.com/8080568/198852748-61d67e0c-49bb-4219-8b9d-1265fc877b96.png)

![NVIDIA_Share_29-10-2022_23-24-28](https://user-images.githubusercontent.com/8080568/198852927-d251279e-f2e6-429f-8f5a-5b460c973f87.png)

ok after changing my webserver to force HTTPS it is working.

**Comment by stonith404** [comment]
Hey, thanks for your report! For me it's working with Firefox on MacOS. Which OS and browser do you use?

**Comment by Smallinger** [comment]
found out it was because the server was not forcing HTTPS and i visit the website on HTTP and the APP_URL=was HTTPS i use Windows 11 with the browser "Brave"

**Comment by stonith404** [comment]
Okay, so it works now when you force https?

**Comment by Smallinger** [comment]
yep its working then.
