### ISSUE TITLE
🚀 Feature: Admin account to see full upload history

### ISSUE THREAD

**Issue by joel72265** [stonith404/pingvin-share#201]
### 🔖 Feature description

Thank you for making a good sharing platform

Please create a Upload history page/section showing all the uploads in chronological order, accessible by the Administrator
- page should display upload name, size, date, username, download count 

### 🎤 Pitch

- good for security
- can identify duplicate, incomplete uploads
- can also have a mass purge option

**Comment by pierrbt** [comment]
Duplicate of #124 but it's an interesting feature
