### ISSUE TITLE
🐛 Bug Report: Share with expiry set to never doesn't get created correctly

### ISSUE THREAD

**Issue by mgesquinosinx** [stonith404/pingvin-share#213]
### 👟 Reproduction steps

Hello,

I installed your project on a Debian 11 server using Docker by copying the basic configuration from docte-compose.yml (without ClamAV).
Then, I configured a virtual host as a reverse proxy using Apache.

1. I ran Certbot to create an SSL certificate for the domain.
2. I configured the administration as follows:
      - Registration prohibited
      - SMTP activation and text modifications
      - Changed the address using my SSL-certified domain
3. I performed several tests with a file size less than 20KB:
    - Created a share link by modifying the expiration date to '1 year' => Test successful
    - Created a share link by setting the expiration date to 'never expires' => No errors when pressing the 'share' button, but the link is neither visible nor accessible.

Thank you in advance for your help

### 👍 Expected behavior

The link "never expire" should be visible in the panel or accessible from the URL.

### 👎 Actual Behavior

The link is not working, and it does not appear in the list of links. However, upon checking the server's upload folder, it is indeed present.

### 🌐 Browser

Chrome

**Comment by mgesquinosinx** [comment]
No, actually. When I press 'share', the 'share ready' window appears correctly (although it displays a strange expiration date at the same time. I'll add a screenshot to illustrate my point). However, when I go to the 'my shares' tab, the list is empty (see screenshot) 

<img width="1792" alt="Capture d’écran 2023-07-27 à 21 35 11" src="https://github.com/stonith404/pingvin-share/assets/122803086/5e890654-32f5-4496-b974-6dabdc34fd2e">
<img width="1792" alt="Capture d’écran 2023-07-27 à 21 36 57" src="https://github.com/stonith404/pingvin-share/assets/122803086/50e672c1-7562-4fa1-9a43-5f771a03abcd">

Thank you for your help! :)

**Comment by stonith404** [comment]
No problem:)
> although it displays a strange expiration date at the same time

Why is it strange? Is it not that date that you entered?

>Created a share link by modifying the expiration date to '1 year' => Test successful
Created a share link by setting the expiration date to 'never expires' => No errors when pressing the 'share' button, but the link is neither visible nor accessible.

Sorry I don't really get it. Does the bug occur only when you set the expiration to `never` or does it occur no matter what you choose for the expiration?

**Comment by mgesquinosinx** [comment]
> Why is it strange? Is it not that date that you entered?
> > Exactly, I can set any expiration, but it won't be displayed.

> Sorry I don't really get it. Does the bug occur only when you set the expiration to never or does it occur no matter what you choose for the expiration?
Yep, the bug is only present when I choose the 'never expire' option. If I don't select this option, I don't have any problemes

**Comment by stonith404** [comment]
Hm okay that's strange, I can't reproduce it. Could you please look in the logs (`docker compose logs`) if you find any errors and if yes please share it. And to be sure, you're using the latest version of Pingvin Share?

**Comment by mgesquinosinx** [comment]
Hello,

No error message in the logs. It's as if the file is created and deleted immediately (related to the announced expiration?). I am indeed on the latest version of Pingvin Share (I pulled the latest push this morning to make sure).

I tested creating a non-expiring link on the server's original domain with the port, as well as on the final domain. The bug is still present.

I also tried another browser other than Chrome => same problem on Firefox :/

**Comment by stonith404** [comment]
That's strange, I can't reproduce it. 
If possible, could you share me the whole Pingvin Share folder (including the data and the docker compose file) as a zip? You can do it like this:
1. Copy the `pingvin-share` folder to `pingvin-share-debug`
2. Modify the port of Pingvin Share in the `docker-compose.yml` in the `pingvin-share-debug` folder to something else
3. Start it with `docker compose up -d` and open the copy of Pingvin Share in your browser.
4. Remove sensitive informations:
       - Remove any shares that contain files that you don't want to share with me
       - Change your user email and password to something random 
       - If you use SMTP change the email and password to something random
5. Zip the `pingvin-share-debug` folder and send it  to me on Discord (stonith404)

This would help me a lot to debug it because it's extremely difficult to help you we something that I can't reproduce. Thanks :)

**Comment by stonith404** [comment]
@Nykoos Not yet, because I can't reproduce it :/

**Comment by stonith404** [comment]
Has anyone Pingvin Share publicly hosted, so I can try to create a share on your instance?

**Comment by Nykoos** [comment]
Add me on Discord I can send you a link @nykoos

@stonith404

**Comment by stonith404** [comment]
@Nykoos I can't add you, you have to do it.

**Comment by stonith404** [comment]
Should be fixed. It usually takes an hour until the image is pushed.

**Comment by mgesquinosinx** [comment]
Perfect! Everything is working for me. Sorry for not replying earlier. Thanks for the quick response! :D
