### ISSUE TITLE
🐛 Bug Report: Not all logo images get overwritten with custom logo

### ISSUE THREAD

**Issue by McFex** [stonith404/pingvin-share#224]
### 👟 Reproduction steps

Upload a custom logo.

### 👍 Expected behavior

It should change all Logos on the site and the favicon.

### 👎 Actual Behavior

The upload only changes the logo.png file in /opt/app/frontend/public/img (which shows in firefox as favicon, although the favicon.ico stays the penguin).
All icons in the icon directory also stay the penguin.
The website still shows only penguins.

I even made my own icons directory and tried overwriting the complete img directory+subdirectory (icons) by putting it into the container with docker cp command, which seems to work, cause when I copy it back from the container it shows my files.
But still the site only shows penguins. I already tried empty cache and it is not working in three browsers I tried.
Also restarting the container did not help.

I am running the container on unraid from the community apps.

### 🌐 Browser

firefox, waterfox, Edge

**Comment by McFex** [comment]
Maybe the latest release has not hit the unraid docker container yet?
Because in the 17.3 release the logo problem is listed as fixed in the changelog.

**Comment by rivolity** [comment]
Your problem is fixed in the latest image
he is an example in my self-hosted server, I've changed the icon, and it's OK for me.
![image](https://github.com/stonith404/pingvin-share/assets/39197760/9b1c49ca-9d72-4a62-9284-7c8981e67008)

**Comment by stonith404** [comment]
@McFex which version are you using? You can see it on the admin page on the bottom.

**Comment by McFex** [comment]
I am using the unraid docker container from CA.
I checked the admin page: Version is 0.17.4.

Just so that I understand it correctly:
ALL logos are supposed to change, right?
And in order to keep the best possible quality the logo you want to upload should be 512x512?

Could it be a permissions issue?

**Comment by McFex** [comment]
What happened?

First time really was buggy with all the issues I described.

Then I removed container and image from unraid.
Added the container again - this time I mapped the img-folder outside of the container to see what happens to the images/icons/favicon without having to use docker cp.
When I uploaded my logo this time it changed all images the way it should.
Maybe when I added the container the first time the CA docker was still on a lower release, and when I trashed it and added it again it was already the newer version.
Sorry again, but I wouldn't have posted the bug report, if I had not tried to fix it without success for some time.

**Comment by McFex** [comment]
I'd say the issue is solved.

**Comment by stonith404** [comment]
Thanks for your detailed description. It might be that your Docker Compose file was outdated because in the current `docker-compose.yml` the image folder is mapped outside the container:
```yml
version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img" # <--
```
I hope this works for you now seamlessly, if not feel free to create a new issue or reopen it :)

**Comment by McFex** [comment]
Thank you for your help and even more for this awesome peace of software! :)
 

-- 
Viel Spaß bei allem was du tust!!!

Liebe Grüße,
Felix

 
 

Gesendet: Montag, 07. August 2023 um 08:30 Uhr
Von: "Elias Schneider" ***@***.***>
An: "stonith404/pingvin-share" ***@***.***>
Cc: "McFex" ***@***.***>, "State change" ***@***.***>
Betreff: Re: [stonith404/pingvin-share] 🐛 Bug Report: Not all logo images get overwritten with custom logo (Issue #224)


 

Thanks for your detailed description. It might be that your Docker Compose file was outdated because in the current docker-compose.yml the image folder is mapped outside the container:


version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img" # <--


I hope this works for you now seamlessly, if not feel free to create a new issue or reopen it :)
