### ISSUE TITLE
🚀 Feature: full links

### ISSUE THREAD

**Issue by arabianq** [stonith404/pingvin-share#225]
### 🔖 Feature description

It would be great if, in addition to short links, we could also use full ones.

For example, I upload a file called video.mp4 and get two links: mydomain.com/s/AAABBB and mydomain.com/s/AAABBB/video.mp4

### 🎤 Pitch

A couple of times it happened that I needed to use a full link (in my scripts), but currently it may not be possible with all file types (and existing full links can become very lengthy). It would be great to have such functionality.

**Comment by stonith404** [comment]
I'm not sure if I understand your request correctly but you mean file links, don't you? 

File links already exist:
![Screenshot 2023-08-07 at 08 32 21](https://github.com/stonith404/pingvin-share/assets/58886915/4b71d0ce-468b-4af2-aba0-d75a0cdf5b0e)

If you're writing a script you can construct the file links like this:
1. Get the share token
```
POST 
https://pingvin-share.dev.eliasschneider.com/api/shares/<shareId>/token
```
2. Get all files of the share 
```
GET
Cookie Header share_<shareId>_token=<shareToken>
https://pingvin-share.dev.eliasschneider.com/api/shares/<shareId>
```
Response looks like this:
```json
{
    "id": "<shareId>",
    "files": [
        {
            "id": "<fileId>",
            "name": "menu-icon.svg",
            "size": "217"
        }
    ],
...
}
```
3. Construct the file link
```
https://pingvin-share.dev.eliasschneider.com/api/shares/<shareId>/files/<fileId>
```

I hope this helps.

**Comment by arabianq** [comment]
Overall, this is really what I need.
But I hope someday it will be possible to get a file with the correct name and extension using wget.

**Comment by stonith404** [comment]
I understand that it would be easier to get the file by name but the problem is that a share can have multiple files with the same name.

**Comment by arabianq** [comment]
Understood. In this case, I close the issue
