### ISSUE TITLE
❓ Question: local link / share?

### ISSUE THREAD

**Issue by outopik** [stonith404/pingvin-share#228]
### 🙋‍♂️ Question

hi, i just manage to install pingvin-share on my Qnap (I'm new to docker, container station here) and i have 2 issues
1- The link it create is http://localhost:3000 but it don't work i have to use the real address http://192.168.1.51:3000 to make it work, is it ok or i have made a mistake?
2- How can i use it outside of my local network?

**Comment by stonith404** [comment]
Hey
1. I'm not sure if I understand your question correctly but you can change the `App URL` in the admin settings.
2. This isn't really Pingvin Share specific so I can't really help you with that. You can either use Cloudflare Tunnels or port forwarding. You can find many tutorials on Google by searching e.g "How do I make a server accessible over the internet"

**Comment by outopik** [comment]
Ok, because from what I've seen everywhere, everyone seems to "sell" the software as a file host (like wetransfer for example)
So this is for local sharing?

**Comment by stonith404** [comment]
No, it can be used to share files locally but the main purpose of Pingvin Share is to share files around the world, like WeTransfer. 
Maybe you're confused because of my answer:
> This isn't really Pingvin Share specific so I can't really help you with that. You can either use Cloudflare Tunnels or port forwarding. You can find many tutorials on Google by searching e.g "How do I make a server accessible over the internet"

You have to do this for every service that you self-host. Pingvin Share can't automatically update the configurations of your router to make Pingvin Share available outside your network.

**Comment by stonith404** [comment]
Sorry for my late answer. 
Yes this works. You probably want to add a domain in the future and for that you would need to add a reverse proxy but for the start it would work to simply do a port forwarding.
