### ISSUE TITLE
🐛 Bug Report: Downloads for non registered users impossible

### ISSUE THREAD

**Issue by kantmn** [stonith404/pingvin-share#233]
### 👟 Reproduction steps

When i upload a file as admin or user and send the link including the password to someone else he/she is not able to download it without creating an account?

### 👍 Expected behavior

There should be an option or automatically to allow downloads for non registered users
you cannot download a file when registration is closed as non known user.

### 👎 Actual Behavior

users without login can not download a file
only possible when using the option "allow non authenticated shares" which is not a good idea

### 🌐 Browser

Firefox, Structural issue not browser related

**Comment by shant1010** [comment]
same issue. Any resolution?
(fresh install via unRaid)

**Comment by shant1010** [comment]
Found a workaround:

1. Set compression to 0
2. restart server

**Comment by kantmn** [comment]
@shant1010 interesting, i can confirm once the compression is set to 0, there is no need for guests to signup/in to download
i did not have to restart the server, just edit the compression in the admin panel and go.

still looks like a bug :question:  but good to have a workarround

**Comment by stonith404** [comment]
Thanks for your report and workaround.
This is probably an unRaid specific issue because I can't reproduce it. Are there any errors in the logs? You can get the logs with `docker compose logs`

**Comment by kantmn** [comment]
i could not see anything weired in the logs, so i tried to reproduce the issue, was no longer able to.
i dont know why, but it is now working as expected, with compress to 9 and disabled "non auth. shares"

can you @shant1010 reproduce the issue? otherwise i would suggest to close this

**Comment by stonith404** [comment]
I'm closing this. If the bug occurs again feel free to reopen the issue.
