### ISSUE TITLE
🚀 Feature: Run container as non root user

### ISSUE THREAD

**Issue by adriadam10** [stonith404/pingvin-share#235]
### 🔖 Feature description

Add the posibility to run the server as non root user, like linuxserver.io images do

### 🎤 Pitch

It would be a great improvement to run the server as non root user to improve system security

**Comment by stonith404** [comment]
Good idea but I don't know how to do this :( If someone is an expert in Docker feel free to create a PR.

**Comment by rcjcarr** [comment]
I concur this would be a good idea. Some code has to interpret UID=XXXX GID=XXX parameters in the YML file.

**Comment by stonith404** [comment]
Thanks to @adriadam10 this will be released in the next release.

**Comment by stonith404** [comment]
Released in `v0.18.0`.
