### ISSUE TITLE
🐛 Bug Report: Firefox autocomplete issue... 

### ISSUE THREAD

**Issue by dieggito** [stonith404/pingvin-share#236]
### 👟 Reproduction steps

Using version 0.17.4 on latest firefox. After i choose firefox to save my login on pingvin domain.

### 👍 Expected behavior

The normal would be when i'm adding a new recepient email address on a new file share, the email field should be blank...

### 👎 Actual Behavior

when i'm adding a new recepient email address on a new file share, the email field is already completed by browsers autocomplete function with the saved pingvin user email address, and, the file password under email recepient is also completed by the pingvin user password...

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Should be fixed in the newest version `v0.17.5`. Feel free to reopen the issue if the bug still occurs.
