### ISSUE TITLE
🚀 Feature: Authelia and other SSO management

### ISSUE THREAD

**Issue by olaxe** [stonith404/pingvin-share#237]
### 🔖 Feature description

I am using the SSO Authelia and it will be amazing to rely on it to identify my users. I guess it will also work for other SSO applications.

### 🎤 Pitch

It will simplify the user management for my users.
Below, headers that can be retrieved to identify a user:
HTTP_REMOTE_USER (login)
HTTP_REMOTE_NAME (fullname)
HTTP_REMOTE_EMAIL

It will be nice to a place where to setup these so Pingvin Share can use it.

Thanks in advance for your consideration

**Comment by stonith404** [comment]
There is already an issue #109 for this request, Unfortunately I have no experience with implementing OAuth2 so we have to wait for someone that wants to work on this feature.
