### ISSUE TITLE
Feature Request : Different quotas for anonymous and signed in users

### ISSUE THREAD

**Issue by shulymn** [stonith404/pingvin-share#24]
Hello,

I'd like it if it was possible to put different settings when you're logged in and for when you're not logged in.
For example :

Logged in :
- 5GB max size
- Can change the expiration date

Logged off :
- 5mb max size
- Cannot change expiration date

Thanks ! 

Edit : Changed title/issue and made my requests into separate issues for easier tracking
<details>
  <summary>Initial text of the issue</summary>
Very good project I like it so far.
I've installed it on UnRAID and it works perfectly, if anyone needs help with that I'll be happy to help.
I've got a few requests if possible : 

My domain is shared between my and my friends so we can share files with each others
I'd ideally want to manage things this way : 

- Manual account creation by the admin only (first account ever created for example? I don't know if the accounts have an ID or something) 
- Accounts can be created with usernames or email (so we don't need to share emails)
- Share expiration/max size when not logged in is set and cannot be changed

I hope I'm not asking for too much
Thanks a lot for the work already done, I'll be following this project closely.
</details>

**Comment by stonith404** [comment]
Hey thanks for your feedback:)
Currently I'm working on admin functionalities, like managing configuration from the frontend, managing users, and audit the shares that were created. 

You're right, I'll add an username attribute!

I'm not really sure what you mean with "Share expiration/max size when not logged in is set and cannot be changed", could you explain this further?

**Comment by stonith404** [comment]
And if you have time, could you create two separate issues for the admin and email feedback, this would help me to track the tasks better :)

**Comment by shulymn** [comment]
Hello,

What I meant is I'd like it if it was possible to put different settings when you're logged in and for when you're not logged in.
For example : 

Logged in : 
- 5GB max size
- Can change the expiration date

Logged off : 
- 5mb max size
- Cannot change expiration date

Thanks a lot for taking my suggestions in account, I will create separate issues for the other topics, sorry I didn't do that first I'm not really used to github!

**Comment by stonith404** [comment]
Okay I see. There should be different quotas for anonymous and signed in users. This could get a bit complicated to implement and there are other features that I want to prioritize first. 
But definitely looking forward to implement this in the future :)

**Comment by Ju17091** [comment]
> Okay I see. There should be different quotas for anonymous and signed in users. This could get a bit complicated to implement and there are other features that I want to prioritize first.
> But definitely looking forward to implement this in the future :)


Hello,
Is a 2 factor authentication for the admin planned ? 
so that the admin account is better protected ? with an authentication app. like google authenticator or Authy
I would be happy if this could be implemented.

**Comment by stonith404** [comment]
Currently I don't plan to implement this feature. In my opinion Pingvin Share is only used by people that the hoster knows so quotas are not necessary. If I miss something or you have a good use case feel free to reopen the issue!
