### ISSUE TITLE
🚀 Feature: Improve upload indicator color with dark mode

### ISSUE THREAD

**Issue by McFex** [stonith404/pingvin-share#243]
### 🔖 Feature description

The color of the upload circle in dark mode is rather dark.
It does the opposite of what dark mode is supposed to do - ease your eyes.
I suggest to lighten that up (at least a little).

### 🎤 Pitch

Easy to see upload circle is essential to not click away accidentally while uploading.

**Comment by stonith404** [comment]
Yeah you're right.
I think this would be something that we could implement while improving the upload statistics. Would you mind to close this issue and leave a comment with your enhancement in the issue #199?
