### ISSUE TITLE
🐛 Bug Report: Logo isn't updated when uploading a new image file

### ISSUE THREAD

**Issue by sebstrgg** [stonith404/pingvin-share#246]
### 👟 Reproduction steps

When I upload a new logo I get a message that the upload was successful.

### 👍 Expected behavior

The logo would be updated to the file that have been uploaded.

### 👎 Actual Behavior

No change made in UI. Cleared cache, tried different browsers

### 🌐 Browser

Chrome/Firefox/Edge

**Comment by stonith404** [comment]
Are there any errors if you run `docker compose logs`? If not please verify, if the images have updated on the disk. The images should be in `data/images`, the `data` folder should be in the same folder as your Docker Compose file.

**Comment by leguennecj** [comment]
Hello,
Same problem. My images are on the data file

Do you want I share you logs on a private message ? @stonith404

**Comment by stonith404** [comment]
@leguennecj Thanks :) So the new and correct logos and in the data folder?

**Comment by leguennecj** [comment]
@stonith404 yes

**Comment by McFex** [comment]
Sometimes a little patience is also good. Had the same problem (https://github.com/stonith404/pingvin-share/issues/224) and I finally got it to work.

I wonder if there is more than one cache instance along the way from backend to frontend?
Especially inside once own network? Or maybe with cloudflare?

Cause in my case it surely felt like this - although it had worked and the images were changed (as I could check in the data folder) it at first only showed a changed favicon when I accessed the site locally but still no change to the main logo.

I gave it a subdomain and accessed it with pingvinshare.mydomain.com with the same browser, and now it didn't even show the favicon anymore.

I took my mobile to access the address through the mobile internet and - woopdidoo - favicon and logo were there.
All my local browsers (I tried three: opera, mozilla, chrome) still wouldn't show them.
After I saw it had worked on my mobile, I didn't much care about it anymore, so I can't be precise, but I'd say it took a day or so until I also saw the change finally in all my browsers.

Maybe this can help the thinking process on the problem ;) - if you still think it is one.
Maybe it is just what it is - and one just has to be patient for a day, before checking whether it worked or not.

**Comment by stonith404** [comment]
Thanks for your comment :) 

This is really strange it must be a caching issue but I have no clue where the image gets cached. Can you access Pingvin Share directly with the ip and port and try it again? So we can rule out that e.g the reverse proxy or Cloudflare is the cause.

**Comment by McFex** [comment]
Thanks for the other email, but no worries ;). I understand the beta status and I prefer development over convenience.

If you are talking to me, it eventually worked back then.

But since I just reinstalled the 17.5 version and my own icons are gone, although I did not delete the appdata folder, I guess I can be the guinea pig for this one :D.

I guess this is a bug, too, by the way, that it looses the icons although they are still there.
I kind of hoped it would automatically recognize the icon folder and just use those images.
Beta it is ;).

Ok, lets go:
Starting now.
Files in the folder still my own icons, but as pingvin doesn't seem to recognize them, I'll try and upload an icon again.

Will edit from now on.

**Comment by McFex** [comment]
@stonith404 Just wrote you an email to your websites address.

**Comment by leguennecj** [comment]
@stonith404 I have redeploy the stack and now it works like a charm !

Thanks for this great job

**Comment by stonith404** [comment]
@McFex Yeah it works for me:
<img width="998" alt="Screenshot 2023-09-22 at 13 21 49@2x" src="https://github.com/stonith404/pingvin-share/assets/58886915/7fbdbfdc-8b71-4335-9fee-af473855df84">

**Comment by stonith404** [comment]
Can you try to upload another logo? Then I can check your website again and check if the logo changes on my laptop.

**Comment by McFex** [comment]
Sorry saw your post just now, will do.

**Comment by stonith404** [comment]
:/ strange. Can your share your `docker-compose.yml`?

**Comment by McFex** [comment]
I am sorry, but i don't know how? I am on unraid. Not sure where to find the docker-compose.yml.

**Comment by stonith404** [comment]
I think I've found a solution. Could you try to use the `stonith404/pingvin-share:development` image and try it again?
