### ISSUE TITLE
🐛 Bug Report: User name and password does not save when my docker and pingvin restarts

### ISSUE THREAD

**Issue by cisco150** [stonith404/pingvin-share#247]
### 👟 Reproduction steps

When my docker and pingvin restarts or i restart the server on windows server 2022 the user name and password do not work i have to re do one ( user account )

### 👍 Expected behavior

When my docker and pingvin restarts or i restart the server on windows server 2022 the user name and password do not work i have to re do one ( user account )

### 👎 Actual Behavior

When my docker and pingvin restarts or i restart the server on windows server 2022 the user name and password do not work i have to re do one ( user account )

### 🌐 Browser

chrome

**Comment by stonith404** [comment]
Can you share your Docker Compose file?

**Comment by cisco150** [comment]
ok i re install it using you docker compase file. i did do it before but it was thru portainer.io could that have made the settings not save. also my dl are slow from my files im on a 1gb up and down speed

**Comment by stonith404** [comment]
Does it work now?

**Comment by stonith404** [comment]
Closing this due inactivity. Feel free to reopen it if the issue stills occurs.
