### ISSUE TITLE
Feature Request : Admin functionality

### ISSUE THREAD

**Issue by shulymn** [stonith404/pingvin-share#25]
Hello,

Splitting my requests as asked in my initial one

I'd like to be able to have full control of the accounts created. 
So, for example, the first account ever created would be the admin, account creation would be disabled, and I would be able to create account for people I know (That's how Jellyfin works for example).

Thanks !

**Comment by stonith404** [comment]
Thanks for your request! Admin functionality is planned and in development. There will be admin features, like 

- managing accounts
- audit shares
- configure configuration over the frontend instead in the `.env` file
