### ISSUE TITLE
🚀 Feature: Auto click Share after dragging & dropping file(s)

### ISSUE THREAD

**Issue by grand-lotus-iroh** [stonith404/pingvin-share#254]
### 🔖 Feature description

Once I drag and drop files I don't want to click the "Share" button. I think it would be a real time saver if I could just have that automatically clicked AFTER the files are uploaded. It would even more sweet if I could just pre-config and autofill the modal popup variables too so I can bypass that automatically.

### 🎤 Pitch

* Save time
* I'm rarely ever going to upload a file, just to delete the file
* Trying to stay true to "for seamless and efficient file sharing" motto.

**Comment by stonith404** [comment]
Released in `v0.18.0`.
