### ISSUE TITLE
🐛 Bug Report: It's a small bug, I think that the calculation of the share's size share possible in the general upload file is wrong.

### ISSUE THREAD

**Issue by lfac76** [stonith404/pingvin-share#259]
### 👟 Reproduction steps

On Share Configuration Page in Max Size (bytes) I put 53687091200 (50 * 1024 * 1024 * 1024), but in the Share upload page apears 53,7 GB. The software use 1000 and not 1024 to the division.

### 👍 Expected behavior

The page should display 50 GB and not 53,7 GB.

### 👎 Actual Behavior

Config:
![image](https://github.com/stonith404/pingvin-share/assets/83482904/32c1a784-3cfc-4606-99f6-74a85c6e556d)

Show wrong value:
![image](https://github.com/stonith404/pingvin-share/assets/83482904/104ea90d-0959-4905-aed1-a34f7c34a33b)

### 🌐 Browser

Any browser.

**Comment by stonith404** [comment]
Yeah I was confused by this too. After the issue #193 I changed the converter to use the standard definition (GB) instead of the binary definition (GiB). 

```
1'073'741'824 B =  1 GiB <-- Old versions of Pingvin Share
1'000'000'000 B = 1 GB <-- New Version
``` 

You can learn more in [this blog post](https://www.atatus.com/blog/what-is-a-kibibyte/).

**Comment by lfac76** [comment]
Sorry,

I don't understand. For my is something wrong. I configure my server to 1.000.000.000 bytes:

![image](https://github.com/stonith404/pingvin-share/assets/83482904/d6843afd-3adc-45cf-a0b0-32b4bc121c87)

The Upload page shows 1.0 GB:

![image](https://github.com/stonith404/pingvin-share/assets/83482904/8cb23b3e-5462-4400-b0ec-0f6a039d76a2)

But when I try to put a 0,98 GB file:

![image](https://github.com/stonith404/pingvin-share/assets/83482904/abb11a5b-0642-46bc-91fc-432cbca915b2)

This error appears:

![image](https://github.com/stonith404/pingvin-share/assets/83482904/de0d9de8-9fbb-4d84-9772-b9287fc54ab9)

I change the size to 1.073.741.824 and now shows 1,1 GB and I could upload the file of 0,98 GB. But the Pingvin Share is showing a diferent size of the file in in relation of Windows.

![image](https://github.com/stonith404/pingvin-share/assets/83482904/8112aca7-cc3d-49ef-bde6-7a1f8d8040c5)

**Comment by stonith404** [comment]
Windows is using "GiB" instead of GB.

In your case:
```
1059803702 bytes = 0.9870191123 GiB
1059803702 bytes = 1.059803702 GB 
```

So your file is 1.06 GB or 0.98 GiB. Windows actually uses GiB instead of GB. 

I know it's really confusing but you can read more in [this article](https://massive.io/file-transfer/gb-vs-gib-whats-the-difference).
