### ISSUE TITLE
Feature Request : Usernames instead of e-mails

### ISSUE THREAD

**Issue by shulymn** [stonith404/pingvin-share#26]
Hello, 

Splitting my requests as asked in my initial one

I'd like to be able for my users to only use usernames to create accounts/login, I don't really need to know their emails

Thanks !

**Comment by stonith404** [comment]
Thanks for your request :) My suggestion would be to add a second attribute to the user, so the user could login with email or username. What do you think?

**Comment by shulymn** [comment]
I think that would be perfect !
