### ISSUE TITLE
🐛 Bug Report: Invalid `prisma.config.update()`

### ISSUE THREAD

**Issue by antitiron** [stonith404/pingvin-share#260]
### 👟 Reproduction steps

Update stack with docker-compose.

### 👍 Expected behavior

It's work :)

### 👎 Actual Behavior

Don't start container.

Logs:

Running seed command `ts-node prisma/seed/config.seed.ts` ...
Environment variables loaded from prisma/.env
Listening on port 3000 url: http://0.0.0.0:3000
PrismaClientUnknownRequestError: 
Invalid `prisma.config.update()` invocation in
/opt/app/backend/prisma/seed/config.seed.ts:198:27
  195     value: existingConfigVariable.value,
  196   }) != JSON.stringify(existingConfigVariable)

→ 198   await prisma.config.update(
{
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))), transient: false })
    at zr.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:8480)
    at zr.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async migrateConfigVariables (/opt/app/backend/prisma/seed/config.seed.ts:198:7) {
  clientVersion: '5.0.0'
}
An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed/config.seed.ts

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Please see the[ note in the release notes](https://github.com/stonith404/pingvin-share/releases/tag/v0.18.0):

> ⚠️ Warning
As the Docker image doesn't use the root user anymore, you might change the data directory permissions.
This can be done with sudo chown -R your-user data

**Comment by antitiron** [comment]
Thanks.
But I have only one user on my VPS: root.

I created a second user, gave him permissions. Everything worked.

**Comment by svengo** [comment]
Just for the files: pingvin-share uses user id 1000 and group id 1000. So a `sudo chown -R 1000:1000 data` with `data` as the data directory will work. 

Since uid 1000 and gid 1000 is the default for the first user on most Linux systems, the data directory is owned by that user. Keep this in mind on a multi-user system.
