### ISSUE TITLE
🐛 Bug Report: The requested resource isn't a valid image for /img/logo.png received text/html; charset=utf-8

### ISSUE THREAD

**Issue by mariushosting** [stonith404/pingvin-share#262]
### 👟 Reproduction steps

Latest Docker version stop showing all logos image https://github.com/stonith404/pingvin-share/releases/tag/v0.18.0

with the following error message in the logs: The requested resource isn't a valid image for /img/logo.png received text/html; charset=utf-8

### 👍 Expected behavior

logos should be visible

### 👎 Actual Behavior

logos is not visible.

### 🌐 Browser

Chrome

**Comment by mariushosting** [comment]
![logoissue](https://github.com/stonith404/pingvin-share/assets/37554361/3a356e7a-7455-49ab-afa2-414fedf73c7a)

**Comment by stonith404** [comment]
This is probably because of the permission changes of the Docker container.

Please see the[ note in the release notes](https://github.com/stonith404/pingvin-share/releases/tag/v0.18.0):

> ⚠️ Warning
As the Docker image doesn't use the root user anymore, you might change the data directory permissions.
This can be done with sudo chown -R your-user data

**Comment by mariushosting** [comment]
> This is probably because of the permission changes of the Docker container.
> 
> Please see the[ note in the release notes](https://github.com/stonith404/pingvin-share/releases/tag/v0.18.0):
> 
> > ⚠️ Warning
> > As the Docker image doesn't use the root user anymore, you might change the data directory permissions.
> > This can be done with sudo chown -R your-user data

I already set up permissions but this not works.

**Comment by mariushosting** [comment]
Also this breaking change ruined all the users installations. Btw,, this is another issue. Right now no logo images are shown.

**Comment by mariushosting** [comment]
Also, it's better to use PUID and PGID environment variables for users.

**Comment by stonith404** [comment]
> I already set up permissions as per the instructions but this not works.
Can you share the http status code of the images in the network tab in the dev tools?

**Comment by stonith404** [comment]
> Also, it's better to use PUID and PGID environment variables for users.

I was unable to implement this because the user gets created while the image build, but feel free to create a PR if you know how to implement this.

**Comment by mariushosting** [comment]
![token](https://github.com/stonith404/pingvin-share/assets/37554361/519d2ad3-7f2f-410d-98e6-63d41d53dd54)

**Comment by mariushosting** [comment]
There is no issue uploading image etc. The only issues is there is no logo images available 
 https://pingvin.mariushosting.synology.me/s/k2NjkwN

**Comment by stonith404** [comment]
Thanks.
<img width="648" alt="Screenshot 2023-09-21 at 22 58 45@2x" src="https://github.com/stonith404/pingvin-share/assets/58886915/874c8898-9cde-40bb-96cc-5743edeb8df5">

Can you take a look at the Docker container logs? Are there any errors?

**Comment by mariushosting** [comment]
> Thanks. <img alt="Screenshot 2023-09-21 at 22 58 45@2x" width="648" src="https://user-images.githubusercontent.com/58886915/269756655-874c8898-9cde-40bb-96cc-5743edeb8df5.png">
> 
> Can you take a look at the Docker container logs? Are there any errors?
![error](https://github.com/stonith404/pingvin-share/assets/37554361/714deda1-3f53-4614-8735-58080a95674c)

**Comment by stonith404** [comment]
Do you use a custom logo?

**Comment by stonith404** [comment]
It seems like the image doesn't exist because https://pingvin.mariushosting.synology.me/img/logo.png returns 404.

Can you share me the output of `ls data/images` and your docker compose file?

**Comment by mariushosting** [comment]
> It seems like the image doesn't exist because https://pingvin.mariushosting.synology.me/img/logo.png returns 404.
> 
> Can you share me the output of `ls data/images` and your docker compose file?

Here is the compose:
https://mariushosting.com/synology-install-pingvin-with-portainer/

**Comment by stonith404** [comment]
Does it work with `v0.18.1`?

**Comment by mariushosting** [comment]
> Does it work with `v0.18.1`?

Unfortunately not. Fresh installation clean browsers, only 17.5 version works we have issue on a Synology NAS there is something related to this update. I can't replicate this in 17.5 only in 0.18.0 and the same in 0.18.1

**Comment by stonith404** [comment]
Strange, because I didn't change anything related to the logo in this release. Can you share me the output of `ls data/images`?

**Comment by mariushosting** [comment]
version: "3.9"
services:
  pingvin:
    container_name: Pingvin-Share
    image: stonith404/pingvin-share
    healthcheck:
     test: curl -f http://localhost:3000/ || exit 1
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 6090:3000
    volumes:
      - /volume1/docker/pingvin:/opt/app/backend/data:rw
      - /volume1/docker/pingvin/public:/opt/app/frontend/public/img:rw

**Comment by stonith404** [comment]
The images might not get copied correctly on the container startup. Can you try to copy them manually and let me know if this works? This can be done with:
```
docker compose exec pingvin-share cp -rn /tmp/img /opt/app/frontend/public
```

**Comment by mariushosting** [comment]
> The images might not get copied correctly on the container startup. Can you try to copy them manually and let me know if this works? This can be done with:
> 
> ```
> docker compose exec pingvin-share cp -rn /tmp/img /opt/app/frontend/public
> ```

Yes this works!

**Comment by stonith404** [comment]
Awesome. I have holidays now but I'll look into it in 2 weeks.

**Comment by ybizeul** [comment]
Probably related.

At first, no logo available, no big deal, I uploaded mine, then tried to update the site name but the the container crashed :
```
pingvin-pingvin-share-1  | The requested resource isn't a valid image for /img/logo.png received text/html; charset=utf-8
pingvin-pingvin-share-1  | The requested resource isn't a valid image for /img/logo.png received text/html; charset=utf-8
pingvin-pingvin-share-1  | [Nest] 44  - 09/30/2023, 3:43:39 PM   ERROR [ExceptionsHandler]
pingvin-pingvin-share-1  | Invalid `this.prisma.file.create()` invocation in
pingvin-pingvin-share-1  | /opt/app/backend/dist/src/file/file.service.js:65:36
pingvin-pingvin-share-1  |
pingvin-pingvin-share-1  |   62 if (isLastChunk) {
pingvin-pingvin-share-1  |   63     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
pingvin-pingvin-share-1  |   64     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
pingvin-pingvin-share-1  | → 65     await this.prisma.file.create(
pingvin-pingvin-share-1  | Error occurred during query execution:
pingvin-pingvin-share-1  | ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.), transient: false })
pingvin-pingvin-share-1  | PrismaClientUnknownRequestError:
pingvin-pingvin-share-1  | Invalid `this.prisma.file.create()` invocation in
pingvin-pingvin-share-1  | /opt/app/backend/dist/src/file/file.service.js:65:36
pingvin-pingvin-share-1  |
pingvin-pingvin-share-1  |   62 if (isLastChunk) {
pingvin-pingvin-share-1  |   63     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
pingvin-pingvin-share-1  |   64     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
pingvin-pingvin-share-1  | → 65     await this.prisma.file.create(
pingvin-pingvin-share-1  | Error occurred during query execution:
pingvin-pingvin-share-1  | ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.), transient: false })
pingvin-pingvin-share-1  |     at zr.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:8480)
pingvin-pingvin-share-1  |     at zr.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
pingvin-pingvin-share-1  |     at zr.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
pingvin-pingvin-share-1  |     at async FileService.create (/opt/app/backend/dist/src/file/file.service.js:65:13)
pingvin-pingvin-share-1  |     at async FileController.create (/opt/app/backend/dist/src/file/file.controller.js:32:16)
pingvin-pingvin-share-1  |
pingvin-pingvin-share-1  | The requested resource isn't a valid image for /img/logo.png received text/html; charset=utf-8
pingvin-pingvin-share-1  | The requested resource isn't a valid image for /img/logo.png received text/html; charset=utf-8
pingvin-pingvin-share-1  | The requested resource isn't a valid image for /img/logo.png received text/html; charset=utf-8
pingvin-pingvin-share-1  | node:internal/process/promises:289
pingvin-pingvin-share-1  |             triggerUncaughtException(err, true /* fromPromise */);
pingvin-pingvin-share-1  |             ^
pingvin-pingvin-share-1  |
pingvin-pingvin-share-1  | [Error: ENOENT: no such file or directory, open '../frontend/public/img/icons/icon-48x48.png'] {
pingvin-pingvin-share-1  |   errno: -2,
pingvin-pingvin-share-1  |   code: 'ENOENT',
pingvin-pingvin-share-1  |   syscall: 'open',
pingvin-pingvin-share-1  |   path: '../frontend/public/img/icons/icon-48x48.png'
pingvin-pingvin-share-1  | }
pingvin-pingvin-share-1  |
pingvin-pingvin-share-1  | Node.js v20.7.0
pingvin-pingvin-share-1  |
pingvin-pingvin-share-1 exited with code 0
```

Also, buttons on the top bar don't do anything

![image](https://github.com/stonith404/pingvin-share/assets/182035/508aeb3f-c2b7-4a55-821b-decf9effb10c)

**Comment by ybizeul** [comment]
On a brand new install, the `cp` did the job, but I had to use :
```
cp -rn /tmp/img/* /opt/app/frontend/public/img/
```

Possibly the `img/`directory was already there.

**Comment by EdozieJerry** [comment]
am also having the same problem with my code, image fail to display.

**Comment by PitchAbyss** [comment]
> This docker-compose.yaml works perfect:
> 
> ```yaml
> version: '3.8'
> services:
>   pingvin-share:
>     image: stonith404/pingvin-share
>     restart: unless-stopped
>     ports:
>       - 3000:3000
>     volumes:
>       - data:/opt/app/backend/data
>       - images:/opt/app/frontend/public/img
> volumes:
>   data:
>   images:
> ```

thankyou so much bro this worked :D

**Comment by PitchAbyss** [comment]
> This docker-compose.yaml works perfect:
> 
> ```yaml
> version: '3.8'
> services:
>   pingvin-share:
>     image: stonith404/pingvin-share
>     restart: unless-stopped
>     ports:
>       - 3000:3000
>     volumes:
>       - data:/opt/app/backend/data
>       - images:/opt/app/frontend/public/img
> volumes:
>   data:
>   images:
> ```

just one question if i try to change the location on left it breaks the image again

```
/home/pitchabyss/docker/pingvin-share/pingvin_share_data:/opt/app/backend/data
/home/pitchabyss/docker/pingvin-share/pingvin_share_images
```

**Comment by kyaroslav83** [comment]
> > This docker-compose.yaml works perfect:
> 
> > 
> 
> > ```yaml
> 
> > version: '3.8'
> 
> > services:
> 
> >   pingvin-share:
> 
> >     image: stonith404/pingvin-share
> 
> >     restart: unless-stopped
> 
> >     ports:
> 
> >       - 3000:3000
> 
> >     volumes:
> 
> >       - data:/opt/app/backend/data
> 
> >       - images:/opt/app/frontend/public/img
> 
> > volumes:
> 
> >   data:
> 
> >   images:
> 
> > ```
> 
> 
> 
> just one question if i try to change the location on left it breaks the image again
> 
> 
> 
> ```
> 
> /home/pitchabyss/docker/pingvin-share/pingvin_share_data:/opt/app/backend/data
> 
> /home/pitchabyss/docker/pingvin-share/pingvin_share_images
> 
> ```
> 
> 

You can try using the provided YAML file and modifying files in the Docker volume "/var/lib/docker/volumes/"

**Comment by PitchAbyss** [comment]
> > just one question if i try to change the location on left it breaks the image
> 
> You can try using the provided YAML file and modifying files in the Docker volume "/var/lib/docker/volumes/"

not so much knowledge of this i guess il pass or if u can help edit my code above i posted it would very helpful..thankyu

**Comment by kyaroslav83** [comment]
You need to SSH into your server, navigate to the /var/lib/docker/volumes/ directory, and locate the one with the "pingvinshare" images. Then, you can replace the existing files with your uploaded images.
```bash
# Connect to the remote server using SSH (example)
ssh root@192.168.10.100
# Change directory to the specified path with docker volumes
cd /var/lib/docker/volumes/*images/_data/
# List all files and directories in the current directory
ls -la
```
<img width="512" alt="CleanShot 2023-12-12 at 15 38 15@2x" src="https://github.com/stonith404/pingvin-share/assets/63350148/7551b325-b1d6-4a42-aca9-89655194beb5">

**Comment by PitchAbyss** [comment]
> You need to SSH into your server, navigate to the /var/lib/docker/volumes/ directory, and locate the one with the "pingvinshare" images. Then, you can replace the existing files with your uploaded images.
> 
> ```shell
> # Connect to the remote server using SSH (example)
> ssh root@192.168.10.100
> # Change directory to the specified path with docker volumes
> cd /var/lib/docker/volumes/*images/_data/
> # List all files and directories in the current directory
> ls -la
> ```
> 
> <img alt="CleanShot 2023-12-12 at 15 38 15@2x" width="512" src="https://private-user-images.githubusercontent.com/63350148/289861087-7551b325-b1d6-4a42-aca9-89655194beb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTQ0MDcsIm5iZiI6MTcwMjU5NDEwNywicGF0aCI6Ii82MzM1MDE0OC8yODk4NjEwODctNzU1MWIzMjUtYjFkNi00YTQyLWFjYTktODk2NTUxOTRiZWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIyNDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMmYzODM3YTdkNDNkM2U2OGExMzQ3NTZmZWNkNTJjZGE4MDAzOWY3MzE2MjU0NjMxMTkyZmMyNzMwNzJkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0a0j1UdqnRCbdmVcbC37Lwpp1QcWtEwvpGVvbfGYK0">

thankyou so much sir
