### ISSUE TITLE
🐛 Bug Report: Database read-only

### ISSUE THREAD

**Issue by asimicc** [stonith404/pingvin-share#263]
### 👟 Reproduction steps

I updated the app to the most recent version 0.18, docker container that belongs to the Pingvin share stopped working. 

### 👍 Expected behavior

Docker container to be up and healthy

### 👎 Actual Behavior

The docker container restarting loop because of the following error - ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))), transient: false })

To resolve the issue since it is a critical service for me, I had to downgrade the container to v0.17.5 which works correctly.

### 🌐 Browser

Chrome

**Comment by mariushosting** [comment]
this update 0.18.0 update just broke ALL the current installations. You need to manage permissions to fix but unfortunately also with the correct permissions you will not be able too see the Pingvin logo anymore.

**Comment by McFex** [comment]
Yes, I can confirm, my installation also broke:

```
PrismaClientUnknownRequestError: 
Invalid `prisma.config.update()` invocation in
/opt/app/backend/prisma/seed/config.seed.ts:198:27

  195     value: existingConfigVariable.value,
  196   }) != JSON.stringify(existingConfigVariable)
  197 ) {
→ 198   await prisma.config.update(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))), transient: false })
    at zr.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:8480)
    at zr.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async migrateConfigVariables (/opt/app/backend/prisma/seed/config.seed.ts:198:7) {
  clientVersion: '5.0.0'
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed/config.seed.ts

> pingvin-share-backend@0.18.0 prod
> prisma migrate deploy && prisma db seed && node dist/src/main

Listening on port 3000 url: http://0.0.0.0:3000
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"

16 migrations found in prisma/migrations


No pending migrations to apply.
Environment variables loaded from prisma/.env
Running seed command `ts-node prisma/seed/config.seed.ts` ...
```

**Comment by stonith404** [comment]
Please see the[ note in the release notes](https://github.com/stonith404/pingvin-share/releases/tag/v0.18.0):

> ⚠️ Warning
As the Docker image doesn't use the root user anymore, you might change the data directory permissions.
This can be done with sudo chown -R your-user data


I understand that releasing a breaking change like this is not ideal, but Pingvin Share is still in beta, and occasionally requires such changes to enhance the platform :/

I'm leaving this issue open because it's the third report about the same thing. It seems like closed issues aren't being searched before creating new ones.

**Comment by McFex** [comment]
No worries, development before convenience.
I just realized my docker was not working any more this morning and came here to find this issue right at the top.

Is it then best to completely uninstall (meaning also deleting the shares and complete datafolder) and then reinstall the docker from scratch?
Or does this

> This can be done with sudo chown -R your-user data

mean, that I can resolve this easily? I am not sure which "your-user data" you mean?

**Comment by mariushosting** [comment]
> @McFex A reinstallation is definitely not necessary.
> 
> `chown` changes the owner of a file or folder. `your-user` should be replaced with the actual username. It is the user that should be the new owner of the folder, basically the user name of the user that you are using for starting your docker containers. You can get the username by running `whoami`. The last argument (`data`) is the folder to which you want to change the permissions.
> 
> You have to run this command in the same folder as your `docker-compose.yml` file and replace `your-user` with your actual username.

This will not work on other systems like Synology or something different. You should add in the compose user: 1026:100 your own PUID and PGID not the username. Like other containers out there. Right now this version will be bugged for more then 80% of users. Hope in a future release that solve this issue.

**Comment by McFex** [comment]
@stonith404 I am running pingvin on docker in unraid.
I'll check with them which user starts the docker.

But you'll eventually get things going anyway, so patience might also be an option for me ;).

I don't have many or important shares anyway, so in the end reinstallation should do the trick.
I like fiddeling for temporary solutions, but when I figured out everything I actually prefer a fresh install, to rule out anything possibly unknowinlgy left behind.

**Comment by stonith404** [comment]
I think I'm rolling back these permission changes because they cause more problems than they solve.  

I mean it's a nice-to-have feature but not really necessary.

**Comment by McFex** [comment]
Good idea, I guess.

You have the better view on things, I am sure you'll make the right decission ;).

 

I was wondering if I could have just answered this email?

Or wuold it post my mail as a comment?

This is a test.
 

-- 
Don't be mad - still figuring stuff out..

McFex

 
 

Gesendet: Freitag, 22. September 2023 um 11:20 Uhr
Von: "Elias Schneider" ***@***.***>
An: "stonith404/pingvin-share" ***@***.***>
Cc: "McFex" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [stonith404/pingvin-share] 🐛 Bug Report: Database read-only (Issue #263)


 

I think I'm rolling back these permission changes because they cause more problems than they solve.

I mean it's a nice-to-have feature but not really necessary.

**Comment by Bartrpc** [comment]
> Yes, I can confirm, my installation also broke:
> 
> ```
> PrismaClientUnknownRequestError: 
> Invalid `prisma.config.update()` invocation in
> /opt/app/backend/prisma/seed/config.seed.ts:198:27
> 
>   195     value: existingConfigVariable.value,
>   196   }) != JSON.stringify(existingConfigVariable)
>   197 ) {
> → 198   await prisma.config.update(
> Error occurred during query execution:
> ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))), transient: false })
>     at zr.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:8480)
>     at zr.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
>     at zr.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
>     at async migrateConfigVariables (/opt/app/backend/prisma/seed/config.seed.ts:198:7) {
>   clientVersion: '5.0.0'
> }
> 
> An error occurred while running the seed command:
> Error: Command failed with exit code 1: ts-node prisma/seed/config.seed.ts
> 
> > pingvin-share-backend@0.18.0 prod
> > prisma migrate deploy && prisma db seed && node dist/src/main
> 
> Listening on port 3000 url: http://0.0.0.0:3000
> Environment variables loaded from prisma/.env
> Prisma schema loaded from prisma/schema.prisma
> Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
> 
> 16 migrations found in prisma/migrations
> 
> 
> No pending migrations to apply.
> Environment variables loaded from prisma/.env
> Running seed command `ts-node prisma/seed/config.seed.ts` ...
> ```
> 
> The conatiner imidiately shuts down after start.

same problem here

**Comment by stonith404** [comment]
The new image is pushed. Could you guys try it again?

**Comment by Bartrpc** [comment]
```shell
> pingvin-share-backend@0.18.1 prod
> prisma migrate deploy && prisma db seed && node dist/src/main
Listening on port 3000 url: http://0.0.0.0:3000
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
16 migrations found in prisma/migrations
No pending migrations to apply.
Environment variables loaded from prisma/.env
Running seed command `ts-node prisma/seed/config.seed.ts` ...
🌱  The seed command has been executed.
┌─────────────────────────────────────────────────────────┐
│  Update available 5.0.0 -> 5.3.1                        │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [NestFactory] Starting Nest application...
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] PrismaModule dependencies initialized +146ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] JwtModule dependencies initialized +15ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] ThrottlerModule dependencies initialized +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] AppModule dependencies initialized +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
Connected to the database
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] EmailModule dependencies initialized +124ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] ClamScanModule dependencies initialized +13ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +8ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] JobsModule dependencies initialized +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] FileModule dependencies initialized +9ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] UserModule dependencies initialized +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] ReverseShareModule dependencies initialized +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] AuthModule dependencies initialized +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [InstanceLoader] ShareModule dependencies initialized +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RoutesResolver] AuthController {/api/auth}: +81ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/signUp, POST} route +22ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/signIn, POST} route +3ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/signIn/totp, POST} route +3ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/resetPassword/:email, POST} route +3ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/resetPassword, POST} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/password, PATCH} route +3ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/token, POST} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/signOut, POST} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/totp/enable, POST} route +3ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/totp/verify, POST} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/auth/totp/disable, POST} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RoutesResolver] ShareController {/api/shares}: +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares, GET} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/:id, GET} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/:id/metaData, GET} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares, POST} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/:id, DELETE} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/:id/complete, POST} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/isShareIdAvailable/:id, GET} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/:id/token, POST} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RoutesResolver] FileController {/api/shares/:shareId/files}: +0ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/:shareId/files, POST} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/:shareId/files/zip, GET} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/shares/:shareId/files/:fileId, GET} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RoutesResolver] ReverseShareController {/api/reverseShares}: +0ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/reverseShares, POST} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/reverseShares/:reverseShareToken, GET} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/reverseShares, GET} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/reverseShares/:reverseShareId, DELETE} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RoutesResolver] ConfigController {/api/configs}: +0ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/configs, GET} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/:category, GET} route +2ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/configs/admin, PATCH} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/testEmail, POST} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/logo, POST} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RoutesResolver] UserController {/api/users}: +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/users/me, GET} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/users/me, PATCH} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/users/me, DELETE} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/users, GET} route +0ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/users, POST} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/users/:id, PATCH} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [RouterExplorer] Mapped {/api/users/:id, DELETE} route +1ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [NestApplication] Nest application successfully started +78ms
[Nest] 43  - 09/22/2023, 12:03:08 PM     LOG [ClamScanService] ClamAV is not active
``` 

I can confirm it works now. For Unraid users, turn on "Advanced View", search Pingvin, stop container and use "force update".

**Comment by Bartrpc** [comment]
Thak You @stonith404 :) <3

**Comment by McFex** [comment]
It is working locally, but my internet access now is broken - it behaves like it did, when I first forgot to put the api into the proxyconf in swag for pingvin.
The site shows up, but I can not click anything.

This is my proxyconf for pingvin:
`## Version 2023/05/31
# pingvin

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name flexshare.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app pingvin-share;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

    location ~ (/pingvin-share)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app pingvin-share;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    
    }

}
`

**Comment by McFex** [comment]
Yes it works. I edited my previous post. Sorry for that.

Opening in a private window in mozilla did also work, but still not my icons - did you see my icons or yours? Sorry for crossing the issues here, but I really want to know ;)

**Comment by asimicc** [comment]
@stonith404 works for me as well! Thank you for your efforts =)

**Comment by real-jiakai** [comment]
`docker compose down` 
`docker images`
`docker rmi pingvin-share-image-id`
`docker compose up -d`

and then pingvin-share site comes back.
