### ISSUE TITLE
🐛 Bug Report: Reverse Proxy with Traefik limits uploads to 1 GB

### ISSUE THREAD

**Issue by sirNugg3ts** [stonith404/pingvin-share#265]
### 👟 Reproduction steps

When I reverse proxy with Traefik, I get 1GB limitation on uploads

### 👍 Expected behavior

Should be limited by avaible space on mounted disk

### 👎 Actual Behavior

I get a warning that it can only handle 1GB files

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
This isn't really related to Pingvin Share but Traefik. I don't use Traefik so you have to find a solution by your self :/ Just google something like "traefik increase body size".

**Comment by sirNugg3ts** [comment]
It doesn't seem to be Traefik limit it.
For test I've put traefik limiting to 2 MB, and as expected bigger than 2mb will throw a 413 - Request too large.
But the website still advertises that files should not be any larger than 1GB

![imagem](https://github.com/stonith404/pingvin-share/assets/28486181/143dbe1d-a1f7-4a0f-af48-923b0f3275b1)

Is this a configurable parameter somewhere, or where does this value come from?

**Comment by sirNugg3ts** [comment]
I've been browsing your code and it seems this value is obtain from 
`config.get("share.maxSize")`

But I'm failing to understand where this value comes from, perhaps you could enlighten me a bit?

I would love to create a pull request where I make this configurable but I just need to understand how these configs work

**Comment by stonith404** [comment]
Oh, okay. You can this on the admin page: 
```
http://<your-domain>/admin/config/general
```

**Comment by sirNugg3ts** [comment]
But there's no field on the page for this config

**Comment by stonith404** [comment]
It's at the shares tab.

http://your-domain/admin/config/share

**Comment by sirNugg3ts** [comment]
My deepest apologies, have noticed it there.
