### ISSUE TITLE
🚀 Feature: I hope the author can provide SSL certificate support and encrypted file transmission.

### ISSUE THREAD

**Issue by Ceonta** [stonith404/pingvin-share#267]
### 🔖 Feature description

It is hoped that an interface for uploading certificates can be provided to turn http into https

### 🎤 Pitch

Encrypted file transfers

**Comment by idahoanchef** [comment]
Yes Please. Program works like a dream but I do need https before anyone is going to accept my shares.

**Comment by stonith404** [comment]
I don't plan to implement this, see #104 :

> I'm not sure if I want to implement this directly into Pingvin Share because this could easily be done with a reverse proxy. You just could add Nginx to the Docker Compose stack and setup a SSL certificate in it.
