### ISSUE TITLE
❓ Question:  How to set the local user PUID and GUID?

### ISSUE THREAD

**Issue by jeffxt** [stonith404/pingvin-share#269]
### 🙋‍♂️ Question

Hi - I noticed in your release [v0.18.1](https://github.com/stonith404/pingvin-share/releases/tag/v0.18.1) that local users are supported instead of the root user.  

How do I set this?  Do I have to set an environment variable for e.g., UID and GID?  

Thanks!

**Comment by stonith404** [comment]
This isn't possible but feel free to create a feature request. In `v0.18.0` the permissions were changed but there wasn't an option to set UID and GID.
