### ISSUE TITLE
🐛 Bug Report: RAM fills all the way up when downloading very large files

### ISSUE THREAD

**Issue by BBergle** [stonith404/pingvin-share#272]
### 👟 Reproduction steps

Download a 75G MKV file on Unraid 6.12.4 and my ram completely fills up until the program crashes.

On version [v0.18.1](https://hub.docker.com/layers/stonith404/pingvin-share/v0.18.1/images/sha256-58e87900f69d8dd5e9e3a39325f5a68e5441aac162ea4a96415ee2e4511f0329?context=explore)

### 👍 Expected behavior

File should download and RAM should not fill up

### 👎 Actual Behavior

The file downloads until RAM is full which causes the program to crash and the download stops

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Thanks for your report. Does it fill the RAM on the server or on the client?

**Comment by BBergle** [comment]
It fills it up on the server. The file was a 73G mkv movie and I have 64G of ram, when downloading that file the RAM fills up to 100% then the program crashes.

**Comment by stonith404** [comment]
Okay thanks. You mentioned `v0.18.1`, did it work work before?

**Comment by BBergle** [comment]
v0.18.1 was the first version I used. I run Unraid so it was in a docker container, when I tried to downgrade the container just kept crashing. I would have to do a reinstall I'm assuming which I'm willing to do if it'll help.

**Comment by stonith404** [comment]
Okay thanks. No downgrading isn't necessary because I didn't make any changes in the upload logic in `v0.18.0`. 

Does the RAM slowly increase while uploading the large file or does it spike at a specific point?

**Comment by BBergle** [comment]
Yes, it slowly increases in usage but only when downloading. I can upload large files fine.

**Comment by stonith404** [comment]
Thanks, I'll look into it

**Comment by stonith404** [comment]
I think I've found a fix. Could you try it again with the `stonith404/pingvin-share:development` image?

**Comment by BBergle** [comment]
Yes, I will test today and update you.

Thanks

**Comment by stonith404** [comment]
Should be fixed in `v0.18.2`. Feel free to reopen the issue if you still encounter the bug.
