### ISSUE TITLE
❓ Question: Where or how can I see if custom logo has been successfully updated?

### ISSUE THREAD

**Issue by sebasdt** [stonith404/pingvin-share#274]
### 🙋‍♂️ Question

It seems like my pingvin instance will not update the default logos to my own one.

In the logs, there's nothing to see and the site of course says "Upload successfully give some time to update"
It has been over 24 hours and still no change. even cleared my browsers cache to be sure.

**Q:**
Where or how can I see if custom logo has been successfully updated?

**Comment by dnielso5** [comment]
might be cached in your browser, load the page and hit ctrl + f5, that should force a refresh with updated content.

**Comment by sebasdt** [comment]
> might be cached in your browser, load the page and hit ctrl + f5, that should force a refresh with updated content.

I could see the browser console it cleared it's cache and requested some information.

The logos are still the same, tried to replace the logos inside the pingvin container. Still didn't do anything.

**Comment by dnielso5** [comment]
> 
> I could see the browser console it cleared it's cache and requested some information.
> 
> The logos are still the same, tried to replace the logos inside the pingvin container. Still didn't do anything.

So i just tested in mine and it updated after about 2 minutes. the only requirements i see are 1:1 ratio and be in PNG form. what file size is yours? mine was 2.4MB and 512 by 512

**Comment by dnielso5** [comment]
You should also check out issue #246 as it seems to be the same thing.

**Comment by stonith404** [comment]
Yeah currently there is a caching issue if the image gets updated. But I think I've found a solution. Could you try to use the `stonith404/pingvin-share:development` image and try it again?

**Comment by sebasdt** [comment]
Yup that did the trick!
Can I keep on using this image until the next stable update?

**Comment by stonith404** [comment]
@sebasdt Awesome :) Yeah sure you can use the development image.

**Comment by sebasdt** [comment]
Should this issue remain open or time to close it?

**Comment by stonith404** [comment]
Yeah because the issue gets tracked in #246 anyway.
