### ISSUE TITLE
🚀 Feature: Upload speeds and ETA

### ISSUE THREAD

**Issue by fvpv** [stonith404/pingvin-share#275]
### 🔖 Feature description

Hi! I'm going to start that this is so amazing, I've been looking for Pingvin for ages! Find this much cleaner and just works without hassle. This will be all over in no time

Feature request to be able to see upload speeds in real time and ETA in minutes until the upload completes. Option to be enabled via settings.
Thanks!

### 🎤 Pitch

In my use case I might have to upload 10+ Gbs at a time and I would want to know if the site is using my full upload banthwith or if there is a bottleneck anywhere, right now I just use task manager to check the upload speeds.

**Comment by stonith404** [comment]
I think this is related to #199. Feel free to participate in the discussion there :)
