### ISSUE TITLE
2 factor authentication

### ISSUE THREAD

**Issue by Ju17091** [stonith404/pingvin-share#28]
Hello,
Is a 2 factor authentication for the admin planned ? 
so that the admin account is better protected ? with an authentication app. like google authenticator or Authy
I would be happy if this could be implemented. 
Keep up the good work :)

**Comment by stonith404** [comment]
Hey, thanks for your suggestion :) 2FA would be awesome but I didn't really implement this feature before,  so I don't know yet how to do it. But looking forward for it!

**Comment by stautonico** [comment]
I can start working on implementing TOTP for the app, and then maybe we can implement support for hardware U2F keys (like the Yubikey or the Google Titan)?

**Comment by stonith404** [comment]
@stautonico that would be awesome! I would prioritize TOTP first, if possible. If you need any help I'm here :)

**Comment by stautonico** [comment]
@stonith404 Thanks. I've done TOTP 1000 times in all my projects, work and personal. I've never messed with NestJS before, so this is a good way to learn it for me :)

**Comment by Ju17091** [comment]
TOTP support would be great

**Comment by stautonico** [comment]
My bad on the icons, I'm not too familiar with react
