### ISSUE TITLE
🚀功能：

### ISSUE THREAD

**Issue by benzo970210** [stonith404/pingvin-share#283]
### 🔖 Feature description

I hope to add file preview function, including video playback, Word, Excel PPT image zip

### 🎤 Pitch

...

**Comment by stonith404** [comment]
There are already a few supported file formats:

- PDF
- Audio: MP3, WAV, OGG
- Video: MP4, WebM, OGG
- Images

I don't plan to support files that aren't natively supported by the browser as this would need a custom implementation or library for every file type. [See my comment](https://github.com/stonith404/pingvin-share/issues/49#issuecomment-1409931295)
