### ISSUE TITLE
🚀 Feature: Adding your icon to 2FAS

### ISSUE THREAD

**Issue by Imzxhir** [stonith404/pingvin-share#285]
### 🔖 Feature description

Not really a feature request for pingvin-share itself but I would appreciate if you could submit / fill out this form to add your icon to 2FAS.

The form is here if you want to fill it out: <https://2fas.com/your-branding/>

### 🎤 Pitch

In my opinion, this would be great as this is widely used 2FA Authentication app and it would be great if the pingvin-share icon was there rather than having no logo. I think that is all I have to say, I hope you consider my request.

**Comment by stonith404** [comment]
Good idea. I've just filled out the form. I'll update you when I get a response :)

**Comment by stonith404** [comment]
Should be added :)

**Comment by Imzxhir** [comment]
I would like to say the icon has not been added to the 2FAS app yet.

**Comment by stonith404** [comment]
@Imzxhir It might be that you have to disable and enable TOTP again because the issuer has changed. If this doesn't work it is probably not released yet by 2FAS.

**Comment by Imzxhir** [comment]
I have tried to disable and enable 2FA for Pingvin-Share but that did not show the icon either. I guess I will have to wait for 2FAS to update.
