### ISSUE TITLE
🐛 Bug Report: Locked share because the limit of views

### ISSUE THREAD

**Issue by AmadeusGraves** [stonith404/pingvin-share#287]
### 👟 Reproduction steps

* The user uploads a file
* The system shows the dialog to create a share
* The user establish a limit of views, for example 5 views limit
* The user changes again the limit of views to limitless
* The user clicks the button share
* The system shows the following error

![image](https://github.com/stonith404/pingvin-share/assets/18572939/9c302f27-af70-475a-b94f-b31331caf16d)

### 👍 Expected behavior

The system allow the user to share the file

### 👎 Actual Behavior

The system not allow the user to share the file because not has a limit of views  

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Fixed in `v0.21.3`
