### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by comassky** [stonith404/pingvin-share#29]
Hi,

The docker image (https://hub.docker.com/r/stonith404/pingvin-share) deployed yesterday does not contain the fix 

![image](https://user-images.githubusercontent.com/48486646/206142698-239d9dec-1608-46ff-a5cb-c4f9d1e7fd4c.png)

https://github.com/stonith404/pingvin-share/commit/4a016ed57db526ee900c567f7b7f0991f948c631

Is it possible to rebuild the docker image on DockerHub?

Thanks !

**Comment by comassky** [comment]
Hi, the only "issue" is that docker hub image is not up to date :)

If i build manually docker image it works ;)

Pingvin team just have to update (re-build) image on docker hub.

**Comment by stonith404** [comment]
Okay sorry, the image looked like something doesn't work. But yeah the new image with the patch was built and pushed :) Let me know if everything works now.

**Comment by comassky** [comment]
It works ;) Nice, and thanks !
