### ISSUE TITLE
❓ Question: "This link is already in use"

### ISSUE THREAD

**Issue by GuahBy** [stonith404/pingvin-share#293]
### 🙋‍♂️ Question

Hello, 

I was uploading when I suddenly had a crash, so the upload was not finished. 

I tried re-uploading the file I wanted to, then I had the error "Link already in use". I decided to go to my docker file and go to:
/pingvin-share/data/uploads/shares ,there I deleted the file I was uploading before the crash, but I still have the same error "Link is already in use". 

How can I fix this ? 

Thanks for taking the time to read. 

Gabriel

**Comment by stonith404** [comment]
The share is still in the database but after an hour unfinished shares should get deleted automatically. Can you try again?

**Comment by GuahBy** [comment]
> The share is still in the database but after an hour unfinished shares should get deleted automatically. Can you try again?

Hello, 

Thanks for the answer, I tried, but the error message is still here.

**Comment by stonith404** [comment]
Oh sorry, only the files of an unfinished get deleted, the database entry stays. I'll try to fix this.

**Comment by stonith404** [comment]
Unfinished shares should now get deleted after 24 hours.
