### ISSUE TITLE
🐛 Bug Report: ClamAV doesn't trigger in combination with a regular file

### ISSUE THREAD

**Issue by hugosxm** [stonith404/pingvin-share#299]
### 👟 Reproduction steps

Hi ! 

If you upload a malicious file AND a regular file, clamav does not 'trigger' 

Works as expected with ONE file at a time, failed with two or more :(

Also, if you upload a malicious file, it should not create the share at all, instead of creating it, giving you the link, and prompting after that the share got deleted. 

But I see that french and oauth login got added, so keep the good work ! I quite like this product ! 

### 👍 Expected behavior

It should say the same warning with one file : you share got deleted cause file xxx is malicious !

### 👎 Actual Behavior

It does nothing and let you download the crap file

### 🌐 Browser

Brave

**Comment by stonith404** [comment]
The [library](https://github.com/kylefarris/clamscan) the we use to communicate with ClamAV seems broken. There isn't really an alternative to this library. I currently don't really have the time to create a custom implementation but maybe someone wants to create a PR or I might have time in the future.
