### ISSUE TITLE
How do you enable Dark Mode :p

### ISSUE THREAD

**Issue by geekedtv** [stonith404/pingvin-share#3]
Just wondering haha, This looks incredible btw.

**Comment by stonith404** [comment]
Thanks for your feedback :) . Actually there should be a toggle but the GitHub actions pushed the update to the wrong Docker registry. This should be fixed now.
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/58886915/167911713-1e5ef19c-b2d8-457f-887d-f7e3657c47d0.png">
