### ISSUE TITLE
❓ Question: lay person's doubts

### ISSUE THREAD

**Issue by fallsdevil** [stonith404/pingvin-share#303]
### 🙋‍♂️ Question

I don't understand anything about programming and/or codes, tools like that.  However, I decided to try, but I'm having problems.

- My first question is: how do I make the url public?  for example, I don't want a "localhost" because I want to upload files to demonstrate some suggested feature for developers of a project here on Github.
- Another problem I'm facing is that when creating an account, I can't log in again, when I click the "sign in" button nothing happens.

As I said, I don't understand programming, I just wanted an alternative to imgur to host videos and photos to demonstrate something, so if anyone can help me or if it's not possible, I would like to know another alternative.

**Comment by stonith404** [comment]
Hey
The first question isn't really related to Pingvin Share because exposing a service to the internet is the same for every service. Maybe[ this Reddit thread](https://www.reddit.com/r/selfhosted/comments/id6jwu/exposing_a_home_server_to_the_internet_what_are/) can help you.

Regarding your second question, this is not expected :/ Could you share a screen recording?

**Comment by fallsdevil** [comment]
> Hey The first question isn't really related to Pingvin Share because exposing a service to the internet is the same for every service. Maybe[ this Reddit thread](https://www.reddit.com/r/selfhosted/comments/id6jwu/exposing_a_home_server_to_the_internet_what_are/) can help you.
> 
So, Pingvin Share is just sharing between devices connected to the same network?
> 
> Regarding your second question, this is not expected :/ Could you share a screen recording?

Apparently, it worked again, maybe it was some configuration I made.  But thanks anyway!

**Comment by dnielso5** [comment]
> So, Pingvin Share is just sharing between devices connected to the same network?

It can be, but no. Think of it this way. accessing a site/webpage needs a specific port number along with the computers IP address or host name. (for internal its usually done by 192.168.1.123:8080) where the 192.168.1.123 is the computers IP address where the website is running and :8080 is the port that website is using on that computer.

Your router, a gateway to the outside world blocks this port from being seen for security reasons. if you want to using a website (like pingvin) you need to go into the router settings (generally a setting tab called "WAN") in this look for "port forwarding" you put in the port number and the IP address you want it to go to.

When you forward a port you are saying "if someone uses my homes IP address (randomly assigned by your internet provider, lets say 56.34.123.200) and port 8080 i want the router to forward that traffic to this specific computer. this mean it would go 56.34.123.200:8080 -> 192.168.1.123:8080 -> website

I hope that helps.

**Comment by fallsdevil** [comment]
Got it, thanks for the help!

**Comment by stonith404** [comment]
Thanks @dnielso5 for the help
