### ISSUE TITLE
❓ Question: how to change the localhost domain of shared links

### ISSUE THREAD

**Issue by matukosan** [stonith404/pingvin-share#305]
### 🙋‍♂️ Question

Hey there, when using the docker-compose in the repo, the app and fileupload works, but shared links have localhost as domain instead of the actual domain the app is hosted on. How can I change that shared URL domain?

**Comment by dnielso5** [comment]
log in as your admin account, top right button, admin account, Configuration, "app url" -> change it to your domain

**Comment by matukosan** [comment]
> log in as your admin account, top right button, admin account, Configuration, "app url" -> change it to your domain

What admin account? Nothing is mentioned in the readme 🧐

**Comment by dnielso5** [comment]
> > log in as your admin account, top right button, admin account, Configuration, "app url" -> change it to your domain
> 
> What admin account? Nothing is mentioned in the readme 🧐

The first account you create is the admin account, i forgot i named mine that by default.
