### ISSUE TITLE
🐛 Bug Report: Uploading logo crashes container

### ISSUE THREAD

**Issue by maurxce** [stonith404/pingvin-share#307]
### 👟 Reproduction steps

- Create a fresh instance via compose (v0.19.1)
- `Configure > General > Logo > Pick Image`
- Upload Image
- Save

### 👍 Expected behavior

- New logo gets applied

### 👎 Actual Behavior

- App crashes
```
fileshare-pingvin-1  | node:internal/process/promises:289
fileshare-pingvin-1  |             triggerUncaughtException(err, true /* fromPromise */);
fileshare-pingvin-1  |             ^
fileshare-pingvin-1  |
fileshare-pingvin-1  | [Error: ENOENT: no such file or directory, open '../frontend/public/img/icons/icon-48x48.png'] {
fileshare-pingvin-1  |   errno: -2,
fileshare-pingvin-1  |   code: 'ENOENT',
fileshare-pingvin-1  |   syscall: 'open',
fileshare-pingvin-1  |   path: '../frontend/public/img/icons/icon-48x48.png'
fileshare-pingvin-1  | }
fileshare-pingvin-1  |
fileshare-pingvin-1  | Node.js v20.8.1
fileshare-pingvin-1  | npm notice
fileshare-pingvin-1  | npm notice New minor version of npm available! 10.1.0 -> 10.2.2
fileshare-pingvin-1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.2>
fileshare-pingvin-1  | npm notice Run `npm install -g npm@10.2.2` to update!
fileshare-pingvin-1  | npm notice
fileshare-pingvin-1 exited with code 0
```
After trying a second time (after completing the initial setup) it seems to work just fine (different image)

### 🌐 Browser

Chrome Version 118.0.5993.118 (Official Build) (64-bit)

**Comment by stonith404** [comment]
What do you mean with initial setup?

**Comment by maurxce** [comment]
@stonith404 I just meant that it was a freshly set up container and I haven't edited any settings before

**Comment by stonith404** [comment]
@maurxce Oh okay, so it worked after you restarted your Docker container again?

**Comment by maurxce** [comment]
@stonith404 yea, perhaps the application was trying to use the icon before it was done generating in 48x48

**Comment by stonith404** [comment]
Yeah could be. Can you remember approximately how much time passed between starting the container and uploading the logo?

**Comment by maurxce** [comment]
I'm not sure tbh, but I'd guess <30s

**Comment by stonith404** [comment]
It should be fixed in the newest version. Feel free to reopen the issue if it still occurs.
