### ISSUE TITLE
🚀 Feature: Docker OAuth Login Environment Variables

### ISSUE THREAD

**Issue by maurxce** [stonith404/pingvin-share#309]
### 🔖 Feature description

When using docker you should be able to predefine OIDC/OAuth logins directly with environment variables.

### 🎤 Pitch

Don't get me wrong, configuring it via the web page is nice to have, but all services I've used so far (that support OIDC/OAuth) allowed me to configure it via environment variables. (Example: [Outine Wiki](https://docs.getoutline.com/s/hosting/doc/oidc-8CPBm6uC0I))

For the everyday user this may not be a huge deal, but especially in environments with a lot of containers something like this could speed up deployment.

This isn't really a necessity, just a nice-to-have feature.

**Comment by stonith404** [comment]
I think it would make sense if all configuration variables were overrideable with environment variables because there was also a request if the `APP_URL` can be configurable with environment variables (#258).

**Comment by maurxce** [comment]
That would be great!

**Comment by stonith404** [comment]
I'm closing this because #258 is a similar request. This doesn't mean that I won't implement this feature.
