### ISSUE TITLE
❓ Question: Is it possible to change the location where shares are stored?

### ISSUE THREAD

**Issue by ucramos** [stonith404/pingvin-share#311]
### 🙋‍♂️ Question

Hello,

Is it possible to change the location where shares are stored?

I figured out that they are stored here (/opt/pingvin-share/backend/data/uploads/shares/) on my system.

I used a script by TTECK (https://github.com/tteck/Proxmox/blob/main/ct/pingvin.sh) to install the service.

As this is running on a LXC, i would like to have the shares on a mount that i already configured.

I wasn´t able to find out where the default share location is defined.
Is this even configurable?

**Comment by dnielso5** [comment]
i cant see anything in that script that lets you set your own data directory, you can install the entire app by changing line 55 and 61.

outside of that you would need to contact the person who made that script.

if i understand docker correctly and you use the official docker file provided you would update line 9 "./data:/opt/app/backend/data" with "/path/i/want/to/use:/opt/app/backend/data"

though @stonith404 might need to confirm that.

**Comment by stonith404** [comment]
I think you're not using Docker if you use this script. I highly recommend to use Docker installation if possible.

If you can't use Docker: The `DATA_DIRECTORY` environment variable allows you to specify the path of the data directory that contains the shares. See the [README](https://github.com/stonith404/pingvin-share?tab=readme-ov-file#backend) for more information.

**Comment by dnielso5** [comment]
@stonith404 It seems that they made a self installer for your app.

`These scripts empower users to create a Linux container or virtual machine interactively, providing choices for both simple and advanced configurations. The basic setup adheres to default settings, while the advanced setup gives users the ability to customize these defaults. Utilizing the whiptail command, options are displayed to users in a dialog box format. Once the user makes their selections, the script collects and validates their input to generate the final configuration for the container or virtual machine.`

This is more of a question to ask [Here](https://github.com/tteck/Proxmox/issues) unless he swaps to the docker or self install option.
