### ISSUE TITLE
🐛 Bug Report: Share Detail modal is hard to read due to white text over white background

### ISSUE THREAD

**Issue by Simandre** [stonith404/pingvin-share#312]
### 👟 Reproduction steps

1. Login
2. Ensure to use the light theme
3. Go to the share list
4. Click one of the share details icon (i)

![Capture d’écran 2023-11-05 à 12 22 06](https://github.com/stonith404/pingvin-share/assets/105607989/4860a39b-c3de-409e-ba02-fe6c2fc8893d)

### 👍 Expected behavior

Text should be black as used elsewhere

### 👎 Actual Behavior

Text is light gray over white background

The issue doesn't happen while using the dark theme:
![Capture d’écran 2023-11-05 à 12 29 17](https://github.com/stonith404/pingvin-share/assets/105607989/ed06597d-e16d-4e13-be48-1f7397ea681d)

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Fixed, thanks :) The new Docker image should be available in the next hour.
