### ISSUE TITLE
🐛 Bug Report: Upload via Reverse share without being authenticated

### ISSUE THREAD

**Issue by fvpv** [stonith404/pingvin-share#319]
### 👟 Reproduction steps

Reverse shares will not allow upload if the the user isn't authenticated. I don't want anyone online to be able to upload into our platform unless it's via a reverse share link. Unsure if this is a bug or just the way it's intended to be

### 👍 Expected behavior

Anyone should be able to upload files into a reverse share, authenticated or not

### 👎 Actual Behavior

When a authenticated user uses a reverse link it uploads successfully, but if an unauthenticated user tries to upload via a reverse link a error message "Error - 1 files failed to upload. Trying again."
Log file dosen't log any problems

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Yes that's a bug. It is fixed in the development image (`stonith404/pingvin-share:development`) and will be officially fixed in the next release.

**Comment by stonith404** [comment]
Fixed in the latest release.
