### ISSUE TITLE
Signup page accessible when it is Disabled

### ISSUE THREAD

**Issue by bigbeka** [stonith404/pingvin-share#32]
I have disabled signup page, but left the home page enabled.

The 'Get started' button leads to Signup page, but signup is disabled.

I would suggest that IF `Home page` is `true`, AND `Signup` if `false`, THEN `Get Started` button should lead to `Sign in` page or it should not be displayed at all.

**Comment by stonith404** [comment]
Thanks for your report. Yep I can reproduce this. I'll fix it in the next release, it isn't a vulnerability because the user only sees the page but can't register, nevertheless it isn't a nice user experience.

**Comment by stonith404** [comment]
Fixed in https://github.com/stonith404/pingvin-share/commit/c8a4521677280d6aba89d293a1fe0c38adf9f92c

**Comment by stonith404** [comment]
Fixed in 0.3.4
