### ISSUE TITLE
🐛 Bug Report:  Crash when PNG Uploaded as a new Logo

### ISSUE THREAD

**Issue by dclive** [stonith404/pingvin-share#320]
### 👟 Reproduction steps

Upload the attached PNG file under general-logo - instant crash on the server.

I'm running from Synology Linux, Docker, with the following compose file: 

  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3002:3000
    volumes:
      - ${DOCKERCONFDIR}/pingvin/data:/opt/app/backend/data
      - ${DOCKERCONFDIR}/pingvin/images:/opt/app/frontend/public/img

The file is: 
![15-151949_free-crazy-funny-horse](https://github.com/stonith404/pingvin-share/assets/4536776/c06f5a6a-812b-42c6-a1cc-341ca94a4b23)

It's just a random, silly pic I downloaded from a random google in order to have a picture present... 

### 👍 Expected behavior

It shouldn't crash a split second after the png is uploaded under GENERAL / LOGO. 

### 👎 Actual Behavior

Instant crash within 1 second, repeatable every time.  I will try a few more PNG files. 

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Could you share the logs? 
```
docker compose logs
```
