### ISSUE TITLE
❓ Question: Can admin see all files?

### ISSUE THREAD

**Issue by AlexNikMak** [stonith404/pingvin-share#324]
### 🙋‍♂️ Question

Hi everyone, I am new to this(git and docker)

I have a question. Is Admin able to see (open, delete) all files that are sent by other users?

How do I manage garbage files that other users set to newer expire, example:
Login user sent 10GB file and set it to newer expire then stopped to use this service how do I delete this file(space on my server isn't infinite 😢😢😢)

Is there a way to limit the number(not size) of sent files per day for non login user?

Of topic question:
Is there a way to obtain a direct installation link (no web UI just install after clicking on the link)?

Thanks in advance

**Comment by dnielso5** [comment]
1) No, looks like each share creates an encrypted file that your files reside in.

If you used the default docker install the files are located in /path/to/docker/yml_file/data/uploads/shares/link_name

so if you have this link "https://domain.com/share/ExOTE0M" your path to those files are "/path/to/docker/yml_file/data/uploads/shares/ExOTE0M

My path on my computer is "/mnt/MyBook/dietpi_userdata/docker-data/containers/pingvin/data/uploads/shares/ExOTE0M"

you can delete the file in this folder to free up space (probably delete the ExOTE0M folder as well.)

as far as your other questions i dont know.

**Comment by dnielso5** [comment]
Correct, i dont see anything in the admin UI that lets you see other users shares, as well as the shares are not separated by user in the data folder.

you also can not see what files or filename are shared as they are (as far as i can tell) encrypted. the best you can see is how many shares are still active and how large the share is.

If you are the admin you could change their password in the admin console -> users and log in as them as a last resort.

![image](https://github.com/stonith404/pingvin-share/assets/107376351/00c09f73-556e-4762-aa66-9eea670095b3)

**Comment by stonith404** [comment]
@dnielso5 Thanks for your help. You're right this isn't implemented yet, but there is an open feature request #124, feel free to vote there @AlexNikMak.

One little correction, the files aren't encrypted on the server.

**Comment by dnielso5** [comment]
> One little correction, the files aren't encrypted on the server.
Makes sense, probably bot worth it, i just didnt see a quick way to open it.
