### ISSUE TITLE
❓ Question: Microsoft connexion can's find user mail

### ISSUE THREAD

**Issue by dsin-casa** [stonith404/pingvin-share#325]
### 🙋‍♂️ Question

Hello,

I managed to configure the Microsoft connexion but after connecting i have a message telling " Can't obtain email from microsoft account"

Where can i find log to know where could be the problem ?

Thx Best Regards

**Comment by stonith404** [comment]
Probably related to #322 please try the `stonith404/pingvin-share:development` image and let me know if it works.

**Comment by zz5840** [comment]
Please refer the docs below to confirm your config is correct first, and if error still exists, please run `docker compose logs` to view the logs and paste it here.

https://github.com/stonith404/pingvin-share/blob/af8932094a1de7862f05ea103b58207b7a5df798/docs/oauth2-guide.md#microsoft

**Comment by zz5840** [comment]
Ok, this will be fixed in stable image in a few days, don't use dev image  in production environment.

**Comment by dsin-casa** [comment]
Ok thanks i will use the stable one after.

Thanks
