### ISSUE TITLE
🐛 Bug Report: Memory leak(?) downloading large files

### ISSUE THREAD

**Issue by maetthew** [stonith404/pingvin-share#326]
### 👟 Reproduction steps

I set the maximum file size limit to 50GB. Uploaded a ~17GB file and then tried downloading it.

Note that I removed the Nginx reverse proxy in the Dockerfile and built [my own image](https://hub.docker.com/layers/maetthew/pingvin-share/nonginx/images/sha256-69e86c04fadcf8fe4547d3b3bc2092efd50ef4c02aa75f7b20e707439c24811a?context=explore)
```Dockerfile
# Stage 1: Frontend dependencies
FROM node:20-alpine AS frontend-dependencies
WORKDIR /opt/app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

# Stage 2: Build frontend
FROM node:20-alpine AS frontend-builder
WORKDIR /opt/app
COPY ./frontend .
COPY --from=frontend-dependencies /opt/app/node_modules ./node_modules
RUN npm run build

# Stage 3: Backend dependencies
FROM node:20-alpine AS backend-dependencies
RUN apk add --no-cache python3
WORKDIR /opt/app
COPY backend/package.json backend/package-lock.json ./
RUN npm ci

# Stage 4: Build backend
FROM node:20-alpine AS backend-builder
WORKDIR /opt/app
COPY ./backend .
COPY --from=backend-dependencies /opt/app/node_modules ./node_modules
RUN npx prisma generate
RUN npm run build && npm prune --production

# Stage 5: Final image
FROM node:20-alpine AS runner
ENV NODE_ENV=docker

# Alpine specific dependencies
RUN apk update --no-cache
RUN apk upgrade --no-cache
RUN apk add --no-cache curl

WORKDIR /opt/app/frontend
COPY --from=frontend-builder /opt/app/public ./public
COPY --from=frontend-builder /opt/app/.next/standalone ./
COPY --from=frontend-builder /opt/app/.next/static ./.next/static
COPY --from=frontend-builder /opt/app/public/img /tmp/img

WORKDIR /opt/app/backend
COPY --from=backend-builder /opt/app/node_modules ./node_modules
COPY --from=backend-builder /opt/app/dist ./dist
COPY --from=backend-builder /opt/app/prisma ./prisma
COPY --from=backend-builder /opt/app/package.json ./

WORKDIR /opt/app

EXPOSE 3000

# Add a health check to ensure the container is healthy
HEALTHCHECK --interval=10s --timeout=3s CMD curl -f http://localhost:3333/api/health || exit 1

# Application startup
# HOSTNAME=0.0.0.0 fixes https://github.com/vercel/next.js/issues/51684. It can be removed as soon as the issue is fixed
CMD cp -rn /tmp/img /opt/app/frontend/public && PORT=3333 HOSTNAME=0.0.0.0 node frontend/server.js & cd backend && npm run prod
```

I doubt it matters but including the info anyway.

Not sure if the title is correct as I can't really tell if this is technically a memory leak or just that the whole file is being put in the memory while transmitting it.

### 👍 Expected behavior

I should be able to download the file

### 👎 Actual Behavior

Monitoring the server resources with `htop` I can see that the memory continuously rises until it runs out of memory. 

Upon next page load I get "Internal server error" and in the container logs messages like:
```
Error: connect ECONNREFUSED 0.0.0.0:39589
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 39589
}
```

`dmesg` logs:
```
[3709784.942621] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/docker/9ebc99a0d3a68c1643acb4ca5d46469d5bf223ee6676f0c2db39eda5b0b05f2c,task=next-router-wor,pid=16593,uid=0
[3709784.942666] Out of memory: Killed process 16593 (next-router-wor) total-vm:28846856kB, anon-rss:6938968kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:17880kB oom_score_adj:0
[3709787.383269] oom_reaper: reaped process 16593 (next-router-wor), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

### 🌐 Browser

Tested with Vivaldi 6.4.3160.34, Chromium 119.0.6045.105

**Comment by stonith404** [comment]
Please try with the official Docker image if you encounter this issue.

**Comment by pellett655** [comment]
Noticed this memory leak behavior on files > 2GB.  I'm using the unraid version.

![image](https://github.com/stonith404/pingvin-share/assets/43642488/80dc4911-f1bf-4376-b46b-840415c97f22)

**Comment by maetthew** [comment]
I also had this on Unraid. I tried reproducing the behaviour on my local computer a couple of hours after I opened this issue but couldn't, then I didn't have more time. But it seems to be something related to Unraid. I was on a slightly older Unraid version and tried upgrading thinking it might be a bug in the specific Docker version shipped with Unraid but it didn't change the behaviour.

Not sure what to do about this - seems to be an Unraid problem. I guess you can close if you want @stonith404

**Comment by stonith404** [comment]
I'm almost sure that this issue occurs because of your custom Docker image because you have removed Nginx. When you don't use a reverse proxy, Pingvin Share falls back to a built-in NextJS reverse proxy. This built-in reverse proxy causes memory leaks with large files.

**Comment by maetthew** [comment]
Hmm.. How does Pingvin Share know that a reverse proxy sits in front of it? I was using a reverse proxy but in a separate container, using [this image](https://hub.docker.com/r/jlesage/nginx-proxy-manager/). 

In any case, I couldn't reproduce this locally with my custom Docker image and from what I understand @pellett655 used an Unraid template which uses the official Docker image?

![image](https://github.com/stonith404/pingvin-share/assets/810218/a3d664f6-e35b-4097-9ca8-a214f79047ee)

**Comment by stonith404** [comment]
@maetthew Maybe it's really a Unraid specific issue. But please try it again with the following configuration:

1. Expose port `8080` (backend) from your custom Docker image


```dockerfile
...
WORKDIR /opt/app

EXPOSE 8080
EXPOSE 3000
...
```
2. Map `/api` to `pingvin-share-container-ip:8080` in Nginx Proxy Manager

The configuration should basically be the same like the [Nginx configuration](https://github.com/stonith404/pingvin-share/blob/main/nginx/nginx.conf) of the official Docker image. 

There was an issue that seems similar #272 that was fixed by me, by adding Nginx to the Docker image. And as you removed Nginx from the Docker image, you have to do the same configuration manually with Nginx Proxy Manager.

**Comment by stonith404** [comment]
@pellett655 I have no experience with Unraid, did you use any installation guide for setting up Pingvin Share on Unraid?

**Comment by maetthew** [comment]
@stautonico Indeed that seems to rectify the problem.

**Comment by stonith404** [comment]
Great, can we close this issue?

**Comment by maetthew** [comment]
Up to you - seems to be Unraid related to me as the issue you linked also had a user that were on Unraid.

**Comment by stonith404** [comment]
@maetthew I was able to reproduce this issue back then without Unraid. But I'll wait for a response of @pellett655 and then I'll close it.
