### ISSUE TITLE
🚀 Feature: Adding your icon to ente authenticator

### ISSUE THREAD

**Issue by Imzxhir** [stonith404/pingvin-share#327]
### 🔖 Feature description

Not really a feature request for pingvin-share itself but I would appreciate if you could PR your logo to the ente authenticator repo by following the instrutctions found [here](https://github.com/ente-io/auth/blob/main/CONTRIBUTING.md).

This is a similiar request to what was said in my previous issue [here](https://github.com/stonith404/pingvin-share/issues/285).

### 🎤 Pitch

In my opinion, this would be great as this has started become a more widely used 2FA Authentication app and it would be great if the pingvin-share icon was there rather than having no logo.

**Comment by stonith404** [comment]
Feel free to create the PR by your own :)

This is the SVG logo: [pingvin-share-logo](https://github.com/stonith404/pingvin-share/assets/58886915/7cbbbdfb-3332-4d14-8cbc-0d1b06924a38)

And this the color code: #485099

**Comment by Imzxhir** [comment]
I will PR the logo to their repo, thanks for the logo!
