### ISSUE TITLE
🚀 Feature: URL Shortener Section

### ISSUE THREAD

**Issue by TheHecateII** [stonith404/pingvin-share#328]
#### Description:
I would like to suggest the addition of a URL shortener section in Pingvin Share. This feature could enhance the user experience by providing a convenient way to share shortened links for files or content hosted on Pingvin Share.

#### Proposed Functionality:
- Allow users to generate short URLs for shared content.
- Provide an option to customize short URLs for user convenience.
- Include analytics or tracking for short URLs to monitor engagement.

#### Potential Benefits:
- Improved ease of sharing, especially for lengthy URLs.
- Enhanced user control over shared links.
- Analytics could offer insights into link engagement.

**Comment by zz5840** [comment]
I don't think this feature should be implemented in a file sharing app. Maybe you should host your own URL shortener app.

https://awesome-selfhosted.net/tags/url-shorteners.html

**Comment by stonith404** [comment]
Yeah there are many other self-hosted URL shorteners. I don't want that Pingvin Share ends like Nextcloud with countless completely unrelated features.
