### ISSUE TITLE
🚀 Feature: Allow admins to disable "built-in" auth and force specific IDP

### ISSUE THREAD

**Issue by ukdaaan** [stonith404/pingvin-share#329]
### 🔖 Feature description

Allow the administrator to disable the "built-in" accounts (and hide the username / password fields) and if only one social connector is enabled automatically redirect to the relevant IDPs auth flow. 

The user should then also be able to create an account using the idp auth flow sign in request on successful sign in if they don't already have an account.

### 🎤 Pitch

I use SSO for all of my public / client facing services having the ability to hide other authentication methods and redirect the user automatically to the sign-in page if only one method is enabled would improve the user experience sign-in flow.

**Comment by stonith404** [comment]
@zz5840 Yeah I think this feature would make sense.

**Comment by stonith404** [comment]
This was added in `v1.1.0`. If only one OAuth provider is present and password login is disabled, the user will get redirected automatically.
