### ISSUE TITLE
SQLite database is locked

### ISSUE THREAD

**Issue by Fzibi21** [stonith404/pingvin-share#33]
Getting error see bellow: 

Error: SQLite database error
database is locked
   0: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:186
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> pingvin-share-backend@0.0.1 prod
> prisma migrate deploy && prisma db seed && node dist/src/main
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
6 migrations found in prisma/migrations
Error: SQLite database error
database is locked
   0: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:186

**Comment by stonith404** [comment]
That is really strange, I have no clue why the database is locked, I've never seen that before. Could you try a fresh installation? You have to run `docker compose down` to stop the container, then delete the `data` directory and start the container with `docker compose up -d`. Let me know if it works after that :)

**Comment by Fzibi21** [comment]
still doing the same. 
could it be that  am installing it on a shared volume through Open Media vault and it does not like it ? that Pi is the only one i got that is running 64 bit.   have another one that is not on 64 and i am not able to install it on that one

**Comment by stonith404** [comment]
I'm not really sure what you mean with a shared volume. Did you mount the data directory with a folder on your machine like in the official docker compose file?

**Comment by SteliosPapamichail** [comment]
> I'm not really sure what you mean with a shared volume. Did you mount the data directory with a folder on your machine like in the official docker compose file?

Sorry, I should have probably explained further. Yes, the /data directory that I've mounted is on my server's (CIFS) network drive. I'm just mentioning it in case it's causing this issue, since Fzibi seems to be facing the same problem. The interesting thing is that I haven't had such issues with my other containers on this drive. Could it be a permissions issue from pingvin's side?

Happy to provide any info that could help you out :)

**Comment by stonith404** [comment]
I really have no clue why the database is locked... Permissions shouldn't be the issue because it would throw an other error. 
Can your try to rename the database file and then rename it back?
Something like this:
```
docker compose down
cd data
mv pingvin-share.db pingvin-share.db.copy
mv pingvin-share.db.copy pingvin-share.db
docker compose up -d

```

**Comment by stautonico** [comment]
@SteliosPapamichail Is the database being used anywhere? Do you have the server running? Sometimes when a connection is in progress to a database, it doesn't allow any other connections.

**Comment by Fzibi21** [comment]
docker compose down
cd data
mv pingvin-share.db pingvin-share.db.copy
mv pingvin-share.db.copy pingvin-share.db
docker compose up -d

that did not help it still says database locked

**Comment by Fzibi21** [comment]
to bad armv7 is not supported

**Comment by stonith404** [comment]
Ah yeah that could be the issue. A core package of Pingvin Share named Prisma ORM doesn't support armv7. But you can use a 64bit OS on your Raspberry PI. I personally really like Ubuntu Server on a Raspberry PI. With a 64bit OS it has to work.

**Comment by Fzibi21** [comment]
> Ah yeah that could be the issue. A core package of Pingvin Share named Prisma ORM doesn't support armv7. But you can use a 64bit OS on your Raspberry PI. I personally really like Ubuntu Server on a Raspberry PI. With a 64bit OS it has to work.

just for the record I am using a raspberry pi with 54 bit too.  As I said before it installs but does the thing with the SQL Database locked error.

not sure what else may be tried their.

**Comment by stonith404** [comment]
@Fzibi21 ah okay, I interpreted your answer wrongly. You said earlier you use Open Media Vault. I've never used it before but Google says it is a "network-attached storage". Did you already try to mount the volume on the same machine, just to be sure, that it isn't a problem when you use a NAS for the volume?

**Comment by CoppingEthan** [comment]
I'm getting the same error as @Fzibi21 

I'm using TrueNAS to run a network share which is mounted to my docker VM via CIFS on boot with 0777 file/dir mode. When I go to run the container get the same error:

Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
8 migrations found in prisma/migrations
Error: SQLite database error
database is locked
   0: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:186

I don't believe it's a network share issue as all permissions are set to full and other containers that don't use a database run fine so it's most likely just an SQLite issue.

When I run it locally, no issues arise, works flawlessly.

**Comment by Gamerou** [comment]
Yeah I got the same Issue when I try to install it on my Shared Drive.

**Comment by PikaYuhno** [comment]
I also have the same issue when I change the volume to a smb share. If I have the `data` directory on the current directory then it works just fine.

**Comment by stonith404** [comment]
You could try to mount the database file to your OS disk and the share data to your NAS. This would fix the issue. Here is an example:

```yml
version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "/path-to-your-nas/pingvin-share-uploads:/opt/app/backend/data/uploads"
      - "./pingvin-share.db:/opt/app/backend/data/pingvin-share.db" # Create this file before you start the container e.g touch pingvin-share.db

```

**Comment by PikaYuhno** [comment]
> You could try to mount the database file to your OS disk and the share data to your NAS. This would fix the issue. Here is an example:
> 
> ```yaml
> version: '3.8'
> services:
>   pingvin-share:
>     image: stonith404/pingvin-share
>     restart: unless-stopped
>     ports:
>       - 3000:3000
>     volumes:
>       - "/path-to-your-nas/pingvin-share-uploads:/opt/app/backend/data/uploads"
>       - "./pingvin-share.db:/opt/app/backend/data/pingvin-share.db" # Create this file before you start the container e.g touch pingvin-share.db
> ```

Thanks, that works!

**Comment by stonith404** [comment]
I close this because this should fix the issue.

> You could try to mount the database file to your OS disk and the share data to your NAS. This would fix the issue. Here is an example:
> 
> ```yaml
> version: '3.8'
> services:
>   pingvin-share:
>     image: stonith404/pingvin-share
>     restart: unless-stopped
>     ports:
>       - 3000:3000
>     volumes:
>       - "/path-to-your-nas/pingvin-share-uploads:/opt/app/backend/data/uploads"
>       - "./pingvin-share.db:/opt/app/backend/data/pingvin-share.db" # Create this file before you start the container e.g touch pingvin-share.db
> ```
