### ISSUE TITLE
🐛 Bug Report: Max expiration gets ignored if expiration is set to "never"

### ISSUE THREAD

**Issue by wedoodevelopment** [stonith404/pingvin-share#331]
### 👟 Reproduction steps

- Go to configuration
- Go to share
- Set Max expiration to 1 (hour)
- Upload a file
- Select never expire / set an expiration date

### 👍 Expected behavior

If I set the Max expiration to a certain time, I expect all the other options that save the upload longer then the Max expiration are disabled.

### 👎 Actual Behavior

I can still upload with never expire option when I have set a Max expiration to 1 hour.

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Thanks, I'll look into this.

**Comment by stonith404** [comment]
Fixed in the latest version 👍
