### ISSUE TITLE
🚀 Feature: Isolating the login panel from shared links (hide login panel)

### ISSUE THREAD

**Issue by Qu4Q** [stonith404/pingvin-share#334]
### 🔖 Feature description

It would be nice to be able to expose only the path to the generated links, but in such a way that the login panel is not visible from the outside. Maybe a separate port for the login panel and links? or the possibility of configuring Pingvin Share so that you can easily split /admin and /share in your own separate reverse proxy

If anyone currently has a solution for this, please share your idea.

### 🎤 Pitch

Preserving the ability to post public links for downloading and uploading files, but preventing viewing and logging in or attempting to log in to the user/administrator panel from outside the local network

**Comment by stonith404** [comment]
I'm not a reverse proxy expert but I think this can be done pretty easily. Here is an example nginx configuration from ChatGPT:

```
server {
    listen 80;

    # Define the server name
    server_name your_server_name.com;

    # Location blocks for specific paths
    location ~ ^/(next/.*|/(img/.*|s/.*|share/.*|api/shares/.+|api/files/.+) {
        # Allow only local network access
        allow 192.168.0.0/16; # Adjust this to your local network IP range
        deny all;

        # Reverse proxy settings
        proxy_pass http://your_backend_server;
        # Include other necessary proxy settings
    }

    # Default location block, denying all other requests
    location / {
        deny all;
    }

    # Other server configurations
    # ...
}
```

Maybe I'm missing some paths that should be allowed outside the network, but you can debug this with the browser dev tools and update the whitelist accordingly.

**Comment by stonith404** [comment]
In my opinion this is something that shouldn't be implemented directly into Pingvin Share, because of that I'm closing the issue. Feel free to create a GitHub discussion if you need help with your custom configuration.

**Comment by Qu4Q** [comment]
Maybe right, I set up Nginx Proxy Manager, and I managed to configure it using the GUI without major issues. For others who would like to achieve something similar using the GUI:

Add a regular "Proxy Host" with access for everyone.

In the "Custom Locations" tab, add 5 locations:
/s
/share
/api
/img
/upload

with the filled custom/cog field:
allow all; # Public access

and the fifth one:
/

with the filled custom/cog field:
allow 192.168.1.0/24; # Local access only (IP address range)
deny all; # All other connections will be rejected

You can add more 'allow' statements before 'deny all.'


It seems to me that you could also simply block /auth and leave the rest unlocked. However, in my case, I wanted the main page not to be publicly accessible, so I blocked everything and only allowed what seemed necessary to me.
