### ISSUE TITLE
🚀 Feature: Limiting Discord login to members of a specific server

### ISSUE THREAD

**Issue by axiomen** [stonith404/pingvin-share#338]
### 🔖 Feature description

Currently, from my understanding, when using Discord login, anyone with a Discord account can login/register and use Pingvin-Share. I'd like to have an option to allow only users from a specific server (guild) to register.

### 🎤 Pitch

Limiting Discord login only to XYZ server would be a great way to share files with people from the server you want. It would be easier for user management, and the members wouldn't need to have a separate login (people would be more inclined to join and share). Social login for Nextcloud is an example of a plugin that supports it.

**Comment by zz5840** [comment]
It's a nice feature. I will implement it soon.

**Comment by zz5840** [comment]
@axiomen Can you test the #346?

**Comment by axiomen** [comment]
@zz5840 Nice, I'll test it today when I have access to my server.

**Comment by zz5840** [comment]
@axiomen Thanks, use stonith404/pingvin-share:development image to test this feature.

**Comment by axiomen** [comment]
@zz5840 Works great! Haven't found any issues.

**Comment by zz5840** [comment]
Giant thanks! We'll release it ASAP.
