### ISSUE TITLE
Upload for large files (>500MB) takes very long time

### ISSUE THREAD

**Issue by kpinarci** [stonith404/pingvin-share#34]
Hello,
I find your project very cool, wanted to test immediately because I needed exactly such a thing. I installed it with a docker-compose on my VPS, behind a reverse proxy (caddy).

Additional configuration after installation built in very nicely, ;) I liked it.

I have uploaded a couple of small data, with which it copes very well, but as for large data (>500) upload takes very long. I had to cancel the test because it took so long. Unfortunately, I could not find in the logs why this is so slow. 

For comparison:
File:                 APP duration
800MB ----> pingvin------> infinite
800MB----->seafile------->59s

Tip:
It would be really cool to see the upload display in percent or time, then you know when how long you still have to wait. 
Otherwise, really cool project, the Config is simple and clear.

**Comment by stonith404** [comment]
Hey thanks for your issue :) I actually tested the upload with a 1 GB file a few minutes ago. It took 1:50 minutes and my internet speed is 11 mb/s so it uploads almost as fast as my internet speed is. Does the progress bar update on the right side of the file while your uploading?

But true, I should implement a feature that shows the remaining time👍

**Comment by kpinarci** [comment]
Hi, I uploaded another ISO file 767,5 MB today, my uploade speed is 46,5 mb/s. It took 3 minutes and 47 seconds. This takes me too long if I compare it with seafile (here it took only 37 seconds). 

The progress bar is there, but it is not clear enough what the process status is. If it showed how many percent it has uploaded, then you can see better what the current process status is.

**Comment by stonith404** [comment]
Just to be sure, you run Seafile and Pingvin Share on the same machine with the same circumstances like proxy etc?

**Comment by stonith404** [comment]
Should be fixed now with `v0.6.0` and chunk uploads. Feel free to reopen the issue if it still occurs.
