### ISSUE TITLE
❓ Question: Why is my domain name response Critical error: no domain selected!

### ISSUE THREAD

**Issue by CurryOnPatat** [stonith404/pingvin-share#344]
### 🙋‍♂️ Question

hi, i use docker to host this awesome project but when i tried to open it to the internet via my domain name it says: Critical error: no domain selected! 

in the app id i have entered https://file.mydomain.com/ so why is this not working?

i use cloudflare > local nginx manager (aapanel) then reverse proxy to my local ip

**Comment by zz5840** [comment]
You can use the following command to check whether this app is running.

```bash
curl http://localhost:3000/api/health
```

If the output is `OK`, you may have wrong configurations in your aapanel, please check the documentation or search the web to solve it.

**Comment by CurryOnPatat** [comment]
its not a aapanel issue i have other docker containers run just fine with the exact same config

**Comment by zz5840** [comment]
Can you run the command above to check the outputs?

**Comment by CurryOnPatat** [comment]
Found out the issue it was aapanel you need to set the php version to 7.4 not 8.2

**Comment by zz5840** [comment]
Interesting, we don't have any php code, and it would be better to disable php.

**Comment by zz5840** [comment]
Please close the issue if your issue is resolved, thx.
