### ISSUE TITLE
🚀 Feature: Cleanup uploads directory

### ISSUE THREAD

**Issue by plague-doctor** [stonith404/pingvin-share#348]
### 🔖 Feature description

Pingvin should walk through the uploads directory and cleanup unused/broken/unfinished files/directories.

### 🎤 Pitch

```
drwxrwxr-x 2 1001 1001 4.0K 2023-11-30 11:17 kwMjQ3N
drwxrwxr-x 2 1001 1001 4.0K 2023-11-20 11:08 kyMzEzO
drwxr-xr-x 2 1001 1001 4.0K 2023-11-10 17:13 Wy4zXzz
drwxrwxr-x 2 1001 1001 4.0K 2023-10-13 10:50 MwODc3N
drwxrwxr-x 2 1001 1001 4.0K 2023-11-27 18:48 Q3Mzg0N
drwxrwxr-x 2 1001 1001 4.0K 2023-11-30 11:10 U5NjYyN
```
I have noticed there are Shares which definitely should be removed: `Wy4zXzz` and `MwODc3N`. Most likely they still exist because of a glitch in pingvin, or it had crashed while uploading... I don't know.
I cannot open those shares - I get "Share not found".
Anyway, share not in the database - nuke it!

**Comment by stonith404** [comment]
I think this is more a bug than a feature but thanks for sharing. 

Is the share really not in the database anymore or are you just unable to open the share? The expected behaviour of Pingvin Share is that it deletes expired shares every hour so they might be still on the disk and in the database until this job runs.

Are those shares expired more than an hour ago?

**Comment by plague-doctor** [comment]
I have analysed the pingvin-share.db and no - neither of them are in the database. 
For sure `Wy4zXzz` and `MwODc3N` expiry date is way past. Other expired shares are nicely vanishing but those two persist. Especially `MwODc3N` which is over a month old.

**Comment by fvpv** [comment]
Same to me

**Comment by plague-doctor** [comment]
@stonith404 Sorry, I do not remember that. But logically thinking what else could it be? I have not created those directories manually...

**Comment by stonith404** [comment]
I just can't reproduce the issue where the files don't get cleaned up. If it happens again, please provide more information, such as whether the upload failed and the share configuration. Thank you :)

**Comment by sebasdt** [comment]
I have also not been able to reproduce the issue too... 
However, I've noticed that failed uploads tend not to get deleted on the host system.

**Comment by stonith404** [comment]
Okay feel free to share more information if you encounter this bug again, maybe the bug occurs only with a special condition.

I recently tested if a successful, failed and expired share gets deleted and it worked for me.
