### ISSUE TITLE
Copying link from "copy link" button does nothing, only shows notification

### ISSUE THREAD

**Issue by m-klecka** [stonith404/pingvin-share#35]
When clicking "copy link" from the shares pages it does nothing except showing notification - no link copied:/

**Comment by stonith404** [comment]
Could share the OS and your browser that you use?

**Comment by sebasdt** [comment]
hey, Im having the same issue,
while pressing the copy link button it doesnt copy it to my clipboard.
Im using firefox on windows 10. 
let me check if the same happens on chrome.

**Comment by scubeedu2** [comment]
I have the same issue and am running Ubuntu 20.04.5 LTS on WSL-2

**Comment by stonith404** [comment]
Okay strange, I'm using Firefox on MacOS and it works. Does the copy button on the share finished modal work for you?

**Comment by scubeedu2** [comment]
> Okay strange, I'm using Firefox on MacOS and it works. Does the copy button on the share finished modal work for you?

Nope, and I've tried it using (Win10) Chrome and MS-Edge.  Haven't tried it on Firefox though.

**Comment by sebasdt** [comment]
> Okay strange, I'm using Firefox on MacOS and it works. Does the copy button on the share finished modal work for you?

Nor does it work for me when creating a share or where the shares are managed.
Maybe its a good idea to see what browser versions we're on. 
My firefox is on version 107.0.1

**Comment by stonith404** [comment]
I'm using version 107.0.1 too. On my windows VM I can reproduce the bug with Firefox and Edge too so it's an issue on Linux and Windows but not on windows. I'm looking into it.

**Comment by stonith404** [comment]
I think I've found the issue, copy to clipboard needs a secure origin (either https or localhost). Do you guys use https?
reference: https://stackoverflow.com/a/51823007/14058016

**Comment by stonith404** [comment]
Yep, this must be the issue. I've added an error dialog if https is not enabled 2435a4f8da35cae9e92cf55ab058bf0d8a6d7af5

**Comment by sebasdt** [comment]
Yes the Page wasn't using https. I forgot to say this.. my bad

It would be useful if there's another way to see the  share link on the manage shares page.

Maybe a screen pops up with here is your link just like when the file has been uploaded.

**Comment by stonith404** [comment]
Removed the copy button when https is not enabled when the share was finished. On the shares page it opens now the following dialog instead of copying when https is not enabled:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/58886915/206854489-e5dd8c69-468f-401e-9066-b9eaa433dc42.png">

**Comment by stonith404** [comment]
Are you satisfied with this solution

**Comment by m-klecka** [comment]
@stonith404 thats great, thank you for the fix a info:)

**Comment by stonith404** [comment]
Fixed in 0.3.4
