### ISSUE TITLE
❓ Question: Slow Upload Speeds

### ISSUE THREAD

**Issue by fvpv** [stonith404/pingvin-share#353]
### 🙋‍♂️ Question

Hello!

I'm currently enjoying using your service but have encountered a technical issue regarding upload speeds. My setup includes a high-capacity server with a 10G Ethernet port and symmetrical 500Mb/s internet connectivity. When uploading a large 10G file, the process only utilizes about 20% of the server's available download bandwidth. This is puzzling because the same server reaches its full upload capacity of 500Mb/s when downloading files. Both the server and the client have similar internet speeds.

I've experimented with different compression settings (0 and 9) but haven't noticed any impact on the upload speed. The server has over 100GB of available RAM and the CPU usage hovers around 5%. Interestingly, when I use multiple tabs for simultaneous uploads (e.g., uploading the 10G file twice), the bandwidth usage scales accordingly (e.g., 20% x 2).

Is there a possibility that Pingvin is intentionally throttling connectivity to balance the network performance for other clients? Any insights or settings recommendations to address this would be greatly appreciated.

server side when client is uploading:
![image](https://github.com/stonith404/pingvin-share/assets/146464635/74eec460-920a-4af1-9188-df43988f68e7)
when downloading:
![image](https://github.com/stonith404/pingvin-share/assets/146464635/cef377c1-33a8-49d2-83e6-ecdf188960f8)

**Comment by stonith404** [comment]
I don't really have network knowledge, but this might happen because the file get uploaded in small parts. Feel free to create a bug report then I can look into it further :)

**Comment by fvpv** [comment]
Thanks,

Not going to raise the bug report yet, I'll make some other tests and see if I can find the bottleneck.

Cheers!

**Comment by stonith404** [comment]
Okay, if you think it's related to Pingvin Share feel free to create a bug report :)
