### ISSUE TITLE
❓ Question: Internal Error while setting the OIDC

### ISSUE THREAD

**Issue by Simandre** [stonith404/pingvin-share#355]
### 🙋‍♂️ Question

Hello!

I'm trying to setup SSO on my NAS, using pingvin-share on a docker on said host. I was able to run the SSO Server on my NAS, add an app entry to generate Client ID & Secrets, callback URL and the Wellknown URL too.
![Capture d’écran 2023-12-12 à 11 09 45](https://github.com/stonith404/pingvin-share/assets/105607989/dfa9b8df-47be-45cb-a253-d1374b853372)

I was also able to go to the admin panel and fill the corresponding fields:
![Screenshot 2023-12-12 at 11-14-12 Paramètres - Pingvin Share](https://github.com/stonith404/pingvin-share/assets/105607989/cc36e0e2-f5fa-4553-8e57-3274ae3ba96a)

However, the connection fails at when trying to log via SSO, and I don't understand OpenID enought to getwhat is wrong. Server side, the logs says a successful attempts (`"User ••• signed in to application Pinginv via SSO."`), but there is an internal error Client side. It looks like the Username is not managed, or the claim is not able to bind my Pingvin account with my server account (I have redacted sensible part of the log)

```
2023/12/12 01:33:38	stderr	    at async OAuthController.callback (/opt/app/backend/dist/src/oauth/oauth.controller.js:53:13)
2023/12/12 01:33:38	stderr	    at async OAuthService.link (/opt/app/backend/dist/src/oauth/oauth.service.js:77:9)
2023/12/12 01:33:38	stderr	    at zr.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
2023/12/12 01:33:38	stderr	    at zr.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
2023/12/12 01:33:38	stderr	    at zr.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:8007)
2023/12/12 01:33:38	stderr	    at Ur (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:115:5803)
2023/12/12 01:33:38	stderr	Argument `providerUsername` is missing.
2023/12/12 01:33:38	stderr	
2023/12/12 01:33:38	stderr	     })
2023/12/12 01:33:38	stderr	       }
2023/12/12 01:33:38	stderr	     +   providerUsername: String
2023/12/12 01:33:38	stderr	         providerUserId: "•••",
2023/12/12 01:33:38	stderr	         provider: "oidc",
2023/12/12 01:33:38	stderr	         userId: "•••",
2023/12/12 01:33:38	stderr	       data: {
2023/12/12 01:33:38	stderr	→ 77 await this.prisma.oAuthUser.create({
2023/12/12 01:33:38	stderr	  76 }
2023/12/12 01:33:38	stderr	  75     ]);
2023/12/12 01:33:38	stderr	  74         `provider_${provider}`,
2023/12/12 01:33:38	stderr	
2023/12/12 01:33:38	stderr	/opt/app/backend/dist/src/oauth/oauth.service.js:77:37
2023/12/12 01:33:38	stderr	Invalid `this.prisma.oAuthUser.create()` invocation in
2023/12/12 01:33:38	stderr	PrismaClientValidationError: 
2023/12/12 01:33:38	stderr	Argument `providerUsername` is missing.[39m
2023/12/12 01:33:38	stderr	
2023/12/12 01:33:38	stderr	     })
2023/12/12 01:33:38	stderr	       }
2023/12/12 01:33:38	stderr	     +   providerUsername: String
2023/12/12 01:33:38	stderr	         providerUserId: "•••",
2023/12/12 01:33:38	stderr	         provider: "oidc",
2023/12/12 01:33:38	stderr	         userId: "•••",
2023/12/12 01:33:38	stderr	       data: {
2023/12/12 01:33:38	stderr	→ 77 await this.prisma.oAuthUser.create({
2023/12/12 01:33:38	stderr	  76 }
2023/12/12 01:33:38	stderr	  75     ]);
2023/12/12 01:33:38	stderr	  74         `provider_${provider}`,
2023/12/12 01:33:38	stderr	
2023/12/12 01:33:38	stderr	/opt/app/backend/dist/src/oauth/oauth.service.js:77:37
2023/12/12 01:33:38	stderr	Invalid `this.prisma.oAuthUser.create()` invocation in
2023/12/12 01:33:38	stderr	[31m[Nest] 40  - [39m12/12/2023, 1:33:38 AM [31m  ERROR[39m [38;5;3m[ExceptionsHandler] [39m[31m 
```

According to [this documentation](https://kb.synology.com/en-global/DSM/tutorial/set_up_oidc_for_dsm_in_sso_server#x_anchor_id541dbfc9a1) it looks like the `Authorization scope` and the `Username claim` has to be set Client side.

Can someone help me figure this out?

**Comment by zz5840** [comment]
This appears to be due to the provider not following the specification. According to the OpenID Connect specification [here](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims), a name should be provided to be used as user's display name. Which OpenID provider are you using?

**Comment by Simandre** [comment]
I'm using Synology SSO, but I did not find any settings to check what is correctly given. I do stumble upon the same problem with the docker image of FreshRSS, that I was able to solve:

```yml
  freshrss:
    image: freshrss/freshrss:latest
    environment:
      # See https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html
      OIDC_ENABLED: 0
      OIDC_PROVIDER_METADATA_URL: https://celest.synology.me/webman/sso/.well-known/openid-configuration
      OIDC_CLIENT_ID: •••
      OIDC_CLIENT_SECRET: ••• 
      OIDC_CLIENT_CRYPTO_KEY: •••
      OIDC_REMOTE_USER_CLAIM: username  # <-
      OIDC_SCOPES: openid # <-
      OIDC_X_FORWARDED_HEADERS: X: openidX-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
```

So, if I understand you correctly, I was able to make it work with this image because I specified to the client which claim member from the server to use as to reconcile the user to ; but in the case of Pingvin it's using default members that is not provided by the server, isn't it? If it's the case, why I was able to fix using username as the member to claim, but here the member is not given via the `preferedusername` member?

**Comment by zz5840** [comment]
Yes, I'll add a claim config soon.

**Comment by Simandre** [comment]
Quick follow up:

<img width="723" alt="Capture d’écran 2023-12-27 à 03 02 15" src="https://github.com/stonith404/pingvin-share/assets/105607989/1b6e82ff-14fb-4a68-8e1d-7ff517672276">

I was able to add the required member, and bind my user (not admin) account to my provider account and be logged in. 

To be nitpicking: 
- on the logging screen, it opens a new tab/window that resolve to the same page once logged — that makes the previous tab useless, it could be nice to stay on the same tab.
- not in the translation system yet.
- — otherwise works like a charm so far. 💯

**Comment by zz5840** [comment]
@stonith404 I have no idea why the translation doesn't work. Could you check it?

**Comment by stonith404** [comment]
@zz5840 @Simandre Oh, I forgot to merge the Crowdin (translation tool) pull request before releasing. It will be fixed in the next release.
