### ISSUE TITLE
Jobs don't get executed

### ISSUE THREAD

**Issue by sufd4** [stonith404/pingvin-share#36]
I'm unclear if this should be done and my config is incorrect or this needs to be a feature request. Once an item expires or has reached the maximum views, can an option be created to clean up and wipe them from my drive? It will eventually have a lot of junk files otherwise. Thank you and love the work so far.

**Comment by stonith404** [comment]
There is a [job](https://github.com/stonith404/pingvin-share/blob/v0.3.4/backend/src/jobs/jobs.service.ts#L15), that runs every hour, that should delete these files. Are you sure the files didn't get deleted after an hour?

**Comment by sufd4** [comment]
I had suspected as much. The files and their folders remain but the interface removes them when they expire. Perhaps this is a permissions issue since I've mapped it to a folder on the Ubuntu host machine?

**Comment by stonith404** [comment]
Actually I noticed that all jobs don't get executed. It is fixed 05cbb7b27ef98a3a80dd9edc318f1dcc9a8bd442 and will be released in the next release. Thanks for your report!
