### ISSUE TITLE
npm ERR! command failed

### ISSUE THREAD

**Issue by bedny22** [stonith404/pingvin-share#363]
### 🙋‍♂️ Question

Hello, I tried to deploy pingvin using portainer, I created stack with exact copy of your .yml file. It always ends with this error, I tried this on 2 different hosts. Can you tell what is wrong from this container log ? Thank you very much :)
```
Applying migration `20231021165436_oauth`
The following migrations have been applied:
migrations/
  └─ 20221011172612_init/
    └─ migration.sql
  └─ 20221013212615_cascade_delete_on_share/
    └─ migration.sql
  └─ 20221018123139_make_creator_optional/
    └─ migration.sql
  └─ 20221113221005_share_recipient/
    └─ migration.sql
  └─ 20221201220540_config_and_admin_functionalities/
    └─ migration.sql
  └─ 20221208191607_v0_3_3/
    └─ migration.sql
  └─ 20221213173854_v0_3_6/
    └─ migration.sql
  └─ 20221219061131_user_entity/
    └─ migration.sql
  └─ 20221230120407_category_attribute_config/
    └─ migration.sql
  └─ 20230104145733_v0_5_1/
    └─ migration.sql
  └─ 20230113080918_removed_reason_attribute/
    └─ migration.sql
  └─ 20230126125501_reverse_shares/
    └─ migration.sql
  └─ 20230209205230_v0_10_0/
    └─ migration.sql
  └─ 20230303091601_v0_11_0/
    └─ migration.sql
  └─ 20230319120712_edited_value/
    └─ migration.sql
  └─ 20230718155819_remove_config_veriable_description/
    └─ migration.sql
  └─ 20231021165436_oauth/
    └─ migration.sql
      
All migrations have been successfully applied.
Environment variables loaded from prisma/.env
Running seed command `ts-node prisma/seed/config.seed.ts` ...
🌱  The seed command has been executed.
┌─────────────────────────────────────────────────────────┐
│  Update available 5.0.0 -> 5.7.1                        │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘
npm notice 
npm notice New patch version of npm available! 10.2.3 -> 10.2.5
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
npm notice Run `npm install -g npm@10.2.5` to update!
npm notice 
npm ERR! path /opt/app/backend
npm ERR! command failed
npm ERR! signal SIGILL
npm ERR! command sh -c prisma migrate deploy && prisma db seed && node dist/src/main
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-22T18_23_59_786Z-debug-0.log
> pingvin-share-backend@0.21.0 prod
> prisma migrate deploy && prisma db seed && node dist/src/main
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
17 migrations found in prisma/migrations
No pending migrations to apply.
Listening on port 3333 url: http://0.0.0.0:3333
Environment variables loaded from prisma/.env
Running seed command `ts-node prisma/seed/config.seed.ts` ...
🌱  The seed command has been executed.
npm ERR! path /opt/app/backend
npm ERR! command failed
npm ERR! signal SIGILL
npm ERR! command sh -c prisma migrate deploy && prisma db seed && node dist/src/main
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-22T18_24_30_607Z-debug-0.log
> pingvin-share-backend@0.21.0 prod
> prisma migrate deploy && prisma db seed && node dist/src/main
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
17 migrations found in prisma/migrations
No pending migrations to apply.
Listening on port 3333 url: http://0.0.0.0:3333
Environment variables loaded from prisma/.env
Running seed command `ts-node prisma/seed/config.seed.ts` ...
```

**Comment by bedny22** [comment]
Hi, sure thank you for your response.
Both machines I used for the test are HP Microservers Gen 7 N54L (AMD Turion II Neo N54L (2.2 Ghz). https://n40l.fandom.com/wiki/Base_Hardware_N54L

One is running Docker on Synology (Xpenology on baremetal), The second one is running Proxmox 8.1.3, Docker host is Ubuntu 20.04LTs.

Since last post I tried to play with permissions on the pingvin binds, but problem remains same. Pingvin seems to be able to create DB in the folders so that shoud be fine.

I have one more Lab server, running VMware on Intel CPU so I will give it shot if you think the hardware could be cousing the issue.

**Comment by stonith404** [comment]
Can you try again with no volumes at all? With that we can make sure that the issue is hardware specific.

**Comment by bedny22** [comment]
Hi so I did some more troubleshooting and sadly it looks like HW specific issue.
I tested pingvin on another docker running on Ubuntu 20.04 but the host is VMware with Intel CPU (i5-9600K,48GB RAM) and yea it run first try without any issues using Portainer. I then tried running without volumes on this system - like you suggested and it again run fine.
Then I tried to run the exact same "stack" without volumes on my AMD based HP microserver Gen7 and the NPM error is still there.
It says ("npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-22T18_24_30_607Z-debug-0.log") But for some reason I am not able to exec into the container and check the log...
Actually this is first time I have run into the compatibility issue with this HP server, I am running quite a few services on this machines without problems (Vaultwarden,Nginx,pihole,wireguard,unifi,duplicati,watchtower even nextcloud etc...)
Do you think there is something we can do ? I really liked Pingvin :)
Anyway thank you for your time.

**Comment by stonith404** [comment]
It's strange because there is nothing useful in the logs. It just says
```
npm ERR! path /opt/app/backend
npm ERR! command failed
npm ERR! signal SIGILL
```
Can you try to mount `/root/.npm/_logs/` to your host machine? With that you can access the log file. Additionally, can you share your docker compose file?

**Comment by eg7122** [comment]
Hello, I have the same problem, did you find a solution?
