### ISSUE TITLE
❓ Question: How can I edit homepage if Docker ?

### ISSUE THREAD

**Issue by DarkXero-dev** [stonith404/pingvin-share#366]
### 🙋‍♂️ Question

Hey

I installed pingvin via Docker is there a way to update home page ? I want it to say my Service name.. 

Thanks...

**Comment by sebasdt** [comment]
Hi!

> I installed pingvin via Docker is there a way to update home page ? I want it to say my Service name..
Do you what to you your own name instead of pingvin-share?

if so you can do that via the website GUI, login into admin account -> top right adminstration -> configuration -> General -> change: "App name" (here you also could change the logo icon)

**Comment by DarkXero-dev** [comment]
I meant this 
![page](https://i.imgur.com/xIrPR3u.png)

**Comment by stonith404** [comment]
You have to fork the repository and build your own docker image. This shouldn't be that difficult as the Dockerfile already exists.

**Comment by DarkXero-dev** [comment]
> You have to fork the repository and build your own docker image. This shouldn't be that difficult as the Dockerfile already exists.

I have never done that I have no clue where to begin xD

**Comment by stonith404** [comment]
It's pretty simple:
1. [Fork the repo](https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)
2. Clone the forked repository and open it on your machine
3. Edit the home page file (`frontend/src/pages/index.tsx`)
4. Go back to the root of the project
5. Install Docker
6. Sign in to the Github Docker registry with `docker login ghcr.io`
7. Create a Docker image with `docker build -t ghcr.io/<your-github-username>/pingvin-share .`
8. Push the Docker image with `docker push ghcr.io/<your-github-username>/pingvin-share`
9. Then you can replace `stonith404/pingvin-share` with `ghcr.io/<your-github-username>/pingvin-share` in your `docker-compose.yml` on your server.

**Comment by DarkXero-dev** [comment]
I am getting this
![error](https://i.imgur.com/oFLamzT.png)

**Comment by stonith404** [comment]
Like the error message says the image name must be lowercase. Try to use the 'darkxero' instead of 'darkXero'.

**Comment by DarkXero-dev** [comment]
Ok thanks but it hangs on 
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by stonith404** [comment]
You have to sign in on your server to the GitHub registry too `docker login ghcr.io`

**Comment by DarkXero-dev** [comment]
> You have to sign in on your server to the GitHub registry too `docker login ghcr.io`

I did that, if I didn't I wouldn't be reporting it. I logged out then back in 5 times to no avail.. I use Portainer to deploy my "Stacks" using docker-compose

**Comment by stonith404** [comment]
Okay then you probably have to[ add the registry to Portainer](https://docs.portainer.io/admin/registries/add/custom).

**Comment by DarkXero-dev** [comment]
Now am getting bad gateway all I did was change URL n add my ghcr.io to registry xD
https://share.xerolinux.xyz

**Comment by stonith404** [comment]
Logs of the pingvin share container?

**Comment by DarkXero-dev** [comment]
```
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

**Comment by stonith404** [comment]
Which CPU does your server and pc/laptop have?

**Comment by DarkXero-dev** [comment]
It's a raspberry Pi4

**Comment by stonith404** [comment]
and the CPU of the device where you've built the image?

**Comment by DarkXero-dev** [comment]
It's a Ryzen 5 3600x

**Comment by stonith404** [comment]
You probably have to build the Docker image with Buildx as the Raspberry PI has an ARM CPU and your Ryzen CPU is x86. 
With this command you can build and push the image for x86 and ARM:

```
docker buildx build --push --tag <your-image-tag> --platform linux/amd64,linux/arm64 .
```

**Comment by DarkXero-dev** [comment]
What's my image tag ? coz
`zsh: no such file or directory: docker-share`

**Comment by stonith404** [comment]
You have to be inside the pingvin-share folder...

**Comment by stonith404** [comment]
And the tag shouldn't be `<docker-share>`, it's just a placeholder that you have to replace with your own tag e.g `ghcr.io/darkxero-dev/docker-share`

**Comment by DarkXero-dev** [comment]
Now I get
```
 => ERROR [runner  2/16] RUN apk update --no-cache                                                       0.6s
 => ERROR [backend-dependencies 2/5] RUN apk add --no-cache python3 
 ```

**Comment by stonith404** [comment]
Whole logs?

**Comment by DarkXero-dev** [comment]
Here
```
sudo docker buildx build --push --tag ghcr.io/darkxero-dev/docker-share --platform linux/arm64 .            
[+] Building 2.6s (12/34)                                                                      docker:default
 => [internal] load .dockerignore                                                                        0.0s
 => => transferring context: 139B                                                                        0.0s
 => [internal] load build definition from Dockerfile                                                     0.0s
 => => transferring dockerfile: 2.04kB                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:20-alpine                                        0.7s
 => CACHED [backend-builder 1/6] FROM docker.io/library/node:20-alpine@sha256:9e38d3d4117da74a643f67041  0.0s
 => [internal] load build context                                                                        0.0s
 => => transferring context: 19.23kB                                                                     0.0s
 => ERROR [backend-dependencies 2/5] RUN apk add --no-cache python3                                      0.6s
 => ERROR [runner  2/16] RUN apk update --no-cache                                                       1.8s
 => CACHED [backend-builder 2/6] WORKDIR /opt/app                                                        0.0s
 => CACHED [backend-builder 3/6] COPY ./backend .                                                        0.0s
 => CACHED [frontend-builder 3/5] COPY ./frontend .                                                      0.0s
 => CACHED [frontend-dependencies 3/4] COPY frontend/package.json frontend/package-lock.json ./          0.0s
 => ERROR [frontend-dependencies 4/4] RUN npm ci                                                         1.7s
------                                                                                                        
 > [backend-dependencies 2/5] RUN apk add --no-cache python3:                                                 
0.441 exec /bin/sh: exec format error
------
------
 > [runner  2/16] RUN apk update --no-cache:
0.480 exec /bin/sh: exec format error
------
------
 > [frontend-dependencies 4/4] RUN npm ci:
0.433 exec /bin/sh: exec format error
------
Dockerfile:16
--------------------
  14 |     # Stage 3: Backend dependencies
  15 |     FROM node:20-alpine AS backend-dependencies
  16 | >>> RUN apk add --no-cache python3
  17 |     WORKDIR /opt/app
  18 |     COPY backend/package.json backend/package-lock.json ./
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache python3" did not complete successfully: exit code: 1
```

**Comment by stonith404** [comment]
I can't really help you with that one because I don't know your environment. My guess is that buildx isn't installed correctly. Make sure that you're on the latest Docker Desktop version and you've chosen WSL as Docker backend. 

If this didn't fix your problem you have to search trough Google, you'll probably find something.

**Comment by DarkXero-dev** [comment]
> I can't really help you with that one because I don't know your environment. My guess is that buildx isn't installed correctly. Make sure that you're on the latest Docker Desktop version and you've chosen WSL as Docker backend.
> 
> If this didn't fix your problem you have to search trough Google, you'll probably find something.

Well I am on ArchLinux doing this .. Latest Kernel using Docker my Pi4 is running PiOS Basic no DE.. (Debian 12)

**Comment by stonith404** [comment]
@DarkXero-dev Oh okay, I can't really help you with buildx on ArchLinux. But a second option would be to copy the project to the server and build the image there, without buildx. Then the CPU would be the same for building and running.

**Comment by DarkXero-dev** [comment]
@stonith404 

So basically re-do everything on Pi4?

**Comment by stonith404** [comment]
Yeah everything, except the buildx steps.

**Comment by DarkXero-dev** [comment]
@stonith404 Ok Steps 6 to 9 after cloning forked repo.. Gotcha ... Will report back thanks ;)

**Comment by DarkXero-dev** [comment]
@stonith404 It worked !!! Finally !!!! Thanks !!!
https://share.xerolinux.xyz

**Comment by stonith404** [comment]
Great!

**Comment by NexusEFR** [comment]
Hi, before anything else, congratulations on your project and application. It seems excellent and useful for privacy. The thing is, I would also like to have the option to publish it in my department, but customization would be better with white label branding. However, I can't find the route you mentioned in point 3 in Docker: **_Edit the home page file (frontend/src/pages/index.tsx)_** (I use it under Unraid server). Is the route different? Do I need to do all that forking just to change one word on the welcome home page? Can I map the volume in Docker to see it through the user route in Unraid server? Thank you very much for all the support. Regards.
