### ISSUE TITLE
🐛 Bug Report: Share password field can not be blanked

### ISSUE THREAD

**Issue by mossroy** [stonith404/pingvin-share#367]
### 👟 Reproduction steps

- Choose a file to share
- Click on share button
- In security options, type any letter in the password field
- Remove this letter in the field (because you finally don't want to set any password)
- Click on share button

Alternative scenario (tested on Firefox, might be the same with other browsers or password managers):
- Create an account on pingvin-share, and ask your browser to save the login/password
- Choose a file to share
- Click on share button
- The browser has populated email field with your previously saved login, and password field with your previously saved password
- Remove the content of these 2 fields (because you don't want to set any password for this share)
- Click on share button

Reproduced with v0.17.0 and v0.21.2

### 👍 Expected behavior

The chosen file should be shared without password

### 👎 Actual Behavior

The password field is outlined in red, and the following message is shown below: `password must be at least 3 characters`
It's not possible to share the file without a password, any more

### 🌐 Browser

Firefox or Chrome

**Comment by mossroy** [comment]
It seems to me that there are 2 underlying issues:

- there is certainly some javascript code that checks for 3 characters minimum for the share password field. And it is probably triggered only if this field has been "changed" by the user. It's probably possible to modify this javascript code to accept 0 characters. Or to trigger the javascript code only if the field has been "changed" and is not empty
- for some reason, Firefox considers that the couple "email recipients"/"share password" should be filled with saved credentials. Hopefully there is a way to avoid that

**Comment by stonith404** [comment]
Fixed in `v0.23.3`. Unfortunately there is currently no way to disable auto completion in chrome. It doesn't autofill in Firefox, right?

**Comment by mossroy** [comment]
I tested v0.21.3: it indeed fixes the first issue, by letting the user remove empty the "share password" field. Many thanks!

Regarding the autofill issue, a few wild guesses:
- maybe adding a meaningful `name` attribute for each form field could help browsers distinguish them
- maybe removing the `mantine-` prefix in the `id` attribute of the form fields could help too (but I would understand if it was too complicated)

**Comment by stonith404** [comment]
@mossroy I already tried many solutions like adding the attribute `autoComplete="off"` and changing the name attribute but the browser seems to ignore this. Feel free to create a new bug report because maybe someone knows a solution.
