### ISSUE TITLE
❓ Question: How do I change the frontend port using an .env file?

### ISSUE THREAD

**Issue by asbrwl** [stonith404/pingvin-share#377]
### 🙋‍♂️ Question

How do I change the frontend port using an .env file?
This is on the standalone version, not docker. I already have a few applications running behind NGINX, hence don't want to use the docker version.

I've tried creating a .env file with *PORT=3002" in the root for frontend application and have tried building and running it. however it is still running with the port 3000. 

I wasn't sure if it is a bug, or just me doing something wrong, hence asking a question first.

**Comment by stonith404** [comment]
Can you explain a bit more how you've installed Pingvin Share? Useful would be the .env file and the commands that you've used to start Pingvin Share.

**Comment by asbrwl** [comment]
Sure
I'm using the standalone version of penguin share
pingvin-share has been cloned into a directory 
/pingvin-share/

the backend application is running in ~/pingvin-share/backend/ using the pm2 instructions from the documentation

`pm2 start --name="pingvin-share-backend" npm -- run prod` 

and is running correctly as expected on port 8080

For the frontend application the .env file is saved in ~/pingvin-share/frontend/.env 
The contents of the .env file are simply one line

`port=3002`

After doing the following steps

``` npm install 
npm run build
pm2 start --name="pingvin-share-frontend" npm -- run start 
```

The service in pm2 errors out, 
If I specifically try to start the frontend service without pm2 using

`npm run start`

I get the following error

> Failed to start server
> Error: listen EADDRINUSE: address already in use :::3000
>     at Server.setupListenHandle [as _listen2] (node:net:1872:16)
>     at listenInCluster (node:net:1920:12)
>     at Server.listen (node:net:2008:7)
>     at /home/akhilesh/pingvin-share/frontend/node_modules/next/dist/server/lib/start-server.js:254:16
>     at new Promise (<anonymous>)
>     at startServer (/home/akhilesh/pingvin-share/frontend/node_modules/next/dist/server/lib/start-server.js:191:11)
>     at nextStart (/home/akhilesh/pingvin-share/frontend/node_modules/next/dist/cli/next-start.js:50:40)
>     at /home/akhilesh/pingvin-share/frontend/node_modules/next/dist/bin/next:157:54
>     at async main (/home/akhilesh/pingvin-share/frontend/node_modules/next/dist/bin/next:157:5) {
>   code: 'EADDRINUSE',
>   errno: -98,
>   syscall: 'listen',
>   address: '::',
>   port: 3000
> }

Hope this helps. Let me know if I can share something additional.

**Comment by SteveDevOps** [comment]
I want to do this via docker compose environment.. plz enable. It's ignored. Probably because there's a PORT and a PORT for both frontend/backend?

**Comment by stonith404** [comment]
Yeah, feel free to create a feature request for that :)

**Comment by asbrwl** [comment]
Requesting this to be re-opened. It's not really completed. / Or if you would prefer I create a feature request.
The docker-compose variation comes in as a different way to run the program. 

Also PM2 would just be responsible for running the app I believe. The app needs to be able to read the .env file?

**Comment by stonith404** [comment]
@asbrwl  The issue drifted a bit away from the original question. The suggested solution for the question would be:

> Thanks. I'm not a pm2 to expert but as far as I know it is not possible to use a `.env` file with pm2. Or am I wrong?
> 
> But this way it should work:
> 
> ```
> PORT=3002 pm2 start --update-env --name="pingvin-share-frontend" npm -- run start 
> ```

Could you elaborate what your question is?
