### ISSUE TITLE
Customer System

### ISSUE THREAD

**Issue by dmkjr** [stonith404/pingvin-share#38]
Forgive the incorrect location for this.  I saw your contributing section, but I don't have enough time at the moment to work on this, but I have thought about creating something similar for a few years without much success getting started.

I think a key element for a system like this is to offer the ability to create a "my account" section for those that are downloading uploads.  The use case is most folks (in my estimation, at least my own mileage) use systems like this to transfer files to customers (think creative content creators).  I have a buddy who works for Viacom (BET, MTV, Comedy Central, etc.) as an imaging director for their TV/Radio commercials.  He uses WeTransfer (paid version) so he can get information from the download(er) such as IP address, time/date of download, etc. to verify the product was collected.  Further, he uses it when other customers (smaller promoters) attempt to say they didn't get a download and dispute the CC charge.

Having a system that allows for a list of files that have been assigned to a user account so they can log in and see their past "content" would be an amazing feature, potentially even a paid feature.

I don't know if this is possible with the structure you are creating or if even is an acceptable 'request'.  Would love to help with the project in the future (as time and my wife permits).

Cheers!

**Comment by stonith404** [comment]
Sounds nice! Assign a share to a user is definitely on the roadmap. Could you add a comment that includes a list which features that your enhancement should include? And could you clarify what you mean with a paid feature?

**Comment by dmkjr** [comment]
@stonith404 

- Each user (end user, those that are downloading files) should have a "my account" area that could show all of their "active" downloads.  I say "active", because some business cases may require to utilize the "shared for 1 day" type of feature.  But may once the download is no longer available, it could stay as "this download no longer exists" placeholder, to show something was there at one time.
- Each download should capture user specific information such as IP address (this is key and really is needed for disputing credit card charge backs.
- Ability to allow end-users (those that download) to have the ability to send files.  This is useful in a content creation network to allow the end-user (think customer) to send in multimedia needed for the creation.  Saves on emailing this to the content creators.

It's commonplace for folks to open-source software, sure.  But everyone has to enjoy the benefits of their work (sometimes in terms of dollars).  I would be willing to pay a one-time costs for "premium features" which could include something like above that I'm talking about.

Thank you!

**Comment by stonith404** [comment]
Thanks for your clarification! I think this isn't really difficult to implement. A few questions:
Do you think the IP's should be displayed in the frontend, or can they stay in the logs only?
Do you think that https://github.com/stonith404/pingvin-share/issues/43 could satisfy point three?
And you would recommend to add paid premium features (like these) to Pingvin Share?

**Comment by stonith404** [comment]
So with point 3 you basically mean to update an existing share's metadata? Because there is already a list of a user's share, the share can be deleted too.

**Comment by dmkjr** [comment]
Correct.  Something like.......

USER PROFILE

Uploads Section

1. ITEM (stats / share / edit / delete)
2. ITEM (stats / share / edit / delete)
3. ITEM (stats / share / edit / delete)

**Comment by stonith404** [comment]
Okay I think I got it now ;) Would you mind to create three separate issues, because this would allow use to track our work much better.

**Comment by dmkjr** [comment]
> Okay I think I got it now ;) Would you mind to create three separate issues, because this would allow use to track our work much better.

Certainly. I will write some of my request as well as time permits.  Should put the issues in this morning.

**Comment by stonith404** [comment]
Closing this because here are multiple requests in one issue. Feel free to create an issue for every feature request :)
