### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by SteveDevOps** [stonith404/pingvin-share#381]
### 👟 Reproduction steps

a newly invited user that is using temp pw generated by app.. is able to login, but can't change the pw. I've verified that the generated/old pw is correct.

### 👍 Expected behavior

it should allow newly invited user to change the password. 

### 👎 Actual Behavior

I get error popup -- invalid password. I've tried different combinations.. here is latest attempt:

![image](https://github.com/stonith404/pingvin-share/assets/9933200/3f9bd84a-a312-4bd4-b5f9-293e2e4c8e62)

### 🌐 Browser

Firefox - Windows 10 - v121.0.1 (64-bit)

**Comment by SteveDevOps** [comment]
Ahh.. I figured this out.. but confusing from ui. The temp pw that is auto-generated for new user .. you can't specify as "old" password when you go to change. You have to put new one in for both "old" and "new"... only way I got it to work. This should be notated in ui? or old password field auto-greyed out for new user --  or fixed so new user can actually change using the old auto-generated old pw.

**Comment by stonith404** [comment]
Thanks for your report! This is fixed in `v0.21.5`.
