### ISSUE TITLE
🐛 Bug Report: Deleting a user does not delete the files they have uploaded

### ISSUE THREAD

**Issue by jlar0che** [stonith404/pingvin-share#389]
### 👟 Reproduction steps

I just installed the newest version of Pingvin Share (v0.21.5) and was thoroughly testing it out before "deployment". I noticed that if the admin deletes a user the message that comes up is something akin to "Are you sure you want to delete the user and all their shares?". To me, this implies that the user along with their shares (both the link to the share and the shared file itself) will be deleted. Unfortunately, this isn't the case.

I looked in the shared directory after deleting a user and saw the file(s) uploaded by them persist.

This would end up being quite a logistical headache to clean up when deciding what files need to be deleted after moderate usage by users + tidying up by admin(s).

### 👍 Expected behavior

**Possible Solutions:**
1. The files shared by a user should be deleted when the user is deleted by an admin.
2. There should be a dialog when an admin deletes a user that asks whether to keep  their files, or delete them along with the user.

### 👎 Actual Behavior

When a User is deleted by an Admin their files persist.

### 🌐 Browser

Firefox, Chrome

**Comment by stonith404** [comment]
Thanks for your report. This is fixed and will be released in the next release.

**Comment by stonith404** [comment]
The new releases includes this fix.
