### ISSUE TITLE
Enable https on node.js frontend

### ISSUE THREAD

**Issue by woreibi** [stonith404/pingvin-share#39]
Hi,
I love the project the team has started. I would love to see if possible if you can include docker environment variable to allow use of:

- https
- reference to location of key and cert files

This will allow application to run on https://somedomainname or https://someIPaddress instead of using a reverse proxy in front of application.

I tried to look for node.js file for frontend but was not able to locate it. I believe https can be activated in that file and possibly variables added that can point to cert and key files as an environment variable that can be passed by docker environment variables.

Appreciate your feedback.

Great work.

Thank you,

**Comment by stonith404** [comment]
Hey thanks for your enhancement. I don't really a reason for this feature because a reverse proxy would easily do this job. You just could spin up a reverse proxy container. Can I ask why you don't want to use a reverse proxy?

**Comment by woreibi** [comment]
Hi,

I was thinking to have full encryption end to end. With reverse proxy only one leg of communication is encrypted.

What is the name and location for server.js or node.js for frontend where it can reference https and cert keys to use?

Thank you,


On Dec 10, 2022 2:51 PM, Elias Schneider ***@***.***> wrote:

Hey thanks for your enhancement. I don't really a reason for this feature because a reverse proxy would easily do this job. You just could spin up a reverse proxy container. Can I ask why you don't want to use a reverse proxy?

**Comment by stonith404** [comment]
Sorry I don't know anything about SSL directly with Node.js,  I'm not even sure if this is possible. 
Additionally using SSL directly hasn't any advantages, or has it?

But you can easily enable SSL with a reverse proxy: https://domysee.com/blogposts/reverse-proxy-nginx-docker-compose

I personally use Nginx Proxy Manager, this is a reverse proxy with a GUI.

**Comment by stonith404** [comment]
There are plenty node.js files. For the frontend they are placed in the `/frontend/src` folder. The frontend uses nextjs btw.

**Comment by stevenengland** [comment]
+1 for https

I would love to be able to spin up this container with TLS support.

**Comment by stevenengland** [comment]
> Additionally using SSL directly hasn't any advantages, or has it?

There are advantages. Encryption and possibly trust in the internal network. "Zero Trust".

**Comment by woreibi** [comment]
Hi Steven,

Main advantage is encryption of communication all through out if using a reverse proxy or browsing application directly. In my personal opinion any docker application should have flexibility to run on http or https with environment variables that allow users to configure what port you want it to listen to and allow you also to define SSL cert to use but that adds dev time to get that done. I’m not a dev person but I do tinker around and sometimes I can make the container work with https if it was not designed by creator to work with https and sometimes configuration is not very clear and I’m not successful.

In this instance I have not been successful so far but I have not tried again after  my last communication with creator about path to NextJS config file.

Thanks,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by woreibi** [comment]
Hi,

I tried yesterday to implement https on Nodejs webserver to practice and was able to get it done. It needs few lines of code.

I'm not sure if Nextjs follow same guide lines in code for https as Nodejs but this container didn't have a clear cut config file that I can locate. There is some many .is file in it and very difficult to know where  is the actual config file where http and port are declared. If we can find that file I can try to add code to it.

Do you exactly where and what is the file name?
Last path I got from feedback was not correct...


Thank you,
Wissam

On Dec 14, 2022 12:25 AM, Elias Schneider ***@***.***> wrote:

I've never set up SSL directly with NextJS. If someone knows how to setup https directly with NextJS, feel free to create a PR :)

**Comment by stonith404** [comment]
I think NextJS creates the http server automatically in the background. But there is a way to create a [custom web server](https://nextjs.org/docs/advanced-features/custom-server) with NextJS, but never used it before.

**Comment by woreibi** [comment]
I would love to help but without knowing where the config file is, it will be hard. There Will be a line of code to create http server and declare port it is listening on, if we can locate that file then it will become easier to troubleshoot.
Digging into this container it seemed to have so many .js files it would take a lot of time to dig through them.

I'm not sure if this container was copied from another project but I would think you would know where the main config file is since you are the owner of project.

Either way, I gave it a shot and it didn't work...I tried on another container that was done in Nodejs and dev owner didn't do https but I edited the file and added the code and was able to get that other project container working on https...so it should not be too different in this project either as long as main config file can be located...

I think this is the end of this open issue on my end. Without main file I can't do much.


Thanks everyone for your responses. I appreciate it.

Wissam

On Dec 14, 2022 6:41 AM, Elias Schneider ***@***.***> wrote:

I think NextJS creates the http server automatically in the background. But there is a way to create a custom web server<https://nextjs.org/docs/advanced-features/custom-server> with NextJS, but never used it before.

**Comment by stonith404** [comment]
@woreibi Thanks for your tries :) Sorry but I really don't know what you mean with a config file. There is a [nextjs config file](https://github.com/stonith404/pingvin-share/blob/main/frontend/next.config.js), but related to nodejs and nextjs there isn't any other config file. 

As a work around, you could add nginx to the docker compose stack. With this solution the data is only not encrypted in the docker network. I understand this is not the solution you want, but it's pretty secure. The only way a "hacker" could read the traffic, is when he has access to the docker container and when he has access to the docker container, he easily could read the database.

**Comment by woreibi** [comment]
No worries. I have not tried Nextjs as a plain web server as a test that I can do and try to enable https but I'll look into that to see if it is different from Nodejs.

Thank you for the feedback.
Wissam

On Dec 14, 2022 9:07 AM, Elias Schneider ***@***.***> wrote:

@woreibi<https://github.com/woreibi> Thanks for your tries :) Sorry but I really don't know what you mean with a config file. There is a nextjs config file<https://github.com/stonith404/pingvin-share/blob/main/frontend/next.config.js>, but related to nodejs and nextjs there isn't any other config file.

As a work around, you could add nginx to the docker compose stack. With this solution the data is only not encrypted in the docker network. I understand this is not the solution you want, but it's pretty secure. The only way a "hacker" could read the traffic, is when he has access to the docker container and when he has access to the docker container, he easily could read the database.
