### ISSUE TITLE
🚀 Feature: Markdown Preview Rendering / READMEs

### ISSUE THREAD

**Issue by maurxce** [stonith404/pingvin-share#393]
### 🔖 Feature description

You should add markdown rendering to the file preview in shares, or allow each share to have a README.

![image](https://github.com/stonith404/pingvin-share/assets/91284394/6a2e26f5-ab05-4e0b-ad14-71e70601db31)

### 🎤 Pitch

My use-case:
I'm (planning to) using pingvin to distribute software to my clients. Every time I distribute my software I usually attach a README.pdf, since most clients don't want to bother with markdown files.

Rendering these files would eliminate the need to
a) convert my markdown to a pdf
b) set up a wiki which renders my markdown

I know, this might not be a necessity for *everyone*, but I'm sure most of us here have grown used to using markdown for READMEs in git repositories, so why not include this here too?

And honestly, I'm fine with not having a built-in markdown editor and having to delete and reupload my README everytime, because even then, it would mean I can skip an additional step of work.

**Comment by maurxce** [comment]
In addition to this it would probably be benefitial if it was possible to pin the README to the top

**Comment by maurxce** [comment]
I'm not *too* familiar with NextJS or really any frontend technology (apart from some basics), but I believe this could be achieved using `next-mdx-remote`: https://nextjs.org/docs/app/building-your-application/configuring/mdx#remote-mdx

Don't quote me on this, but I believe the TextPreview could technically be replaced by this, something along the lines of:
```tsx
import { MDXRemote } from "next-mdx-remote/rsc";

const TextPreview = () => {
  const { shareId, fileId } = React.useContext(FilePreviewContext);
  const [ text, setText ] = useState<string>("");

  useEffect(() => {
    api
      .get(`/shares/${shareId}/files/${fileId}?download=false`)
     .then(res => setText(res.data ?? ""));
  }, [ shareId, fileId ]);
  
  return <MDXRemote source={text}>;
}
```

**Comment by maurxce** [comment]
![image](https://github.com/stonith404/pingvin-share/assets/91284394/1f4d0e4e-13fe-4540-9154-3fdc022b09f7)
I guess at the same time markdown support for descriptions might be an option too

**Comment by stonith404** [comment]
Yeah, that would be great. Currently, I'm really busy, and I'm only able to invest my time in bug fixes for the project. But I would love it if you or someone else wanted to create a PR.

**Comment by maurxce** [comment]
Totally understand that!
It's a feature I'd really be interested in, so I'll try my best to do some research and maybe create a PR^^

**Comment by maurxce** [comment]
PR has been opened https://github.com/stonith404/pingvin-share/pull/396
Any input is appreciated

**Comment by stonith404** [comment]
@maurxce Great! I'll look into it ASAP.
