### ISSUE TITLE
❓ Question:

### ISSUE THREAD

**Issue by NexusEFR** [stonith404/pingvin-share#395]
### 🙋‍♂️ Question

Hi, before anything else, congratulations on your project and application. It seems excellent and useful for privacy. This question comes from this closed question https://github.com/stonith404/pingvin-share/issues/366 , I hope you can tell me something, thank you. 
The thing is, I would also like to have the option to publish it in my department, but customization would be better with white label branding. However, I can't find the route you mentioned in point 3 in Docker: Edit the home page file (frontend/src/pages/index.tsx) (I use it under Unraid server). Is the route different? Do I need to do all that forking just to change one word on the welcome home page? Can I map the volume in Docker to see it through the user route in Unraid server? Thank you very much for all the support. Regards.
image

**Comment by stonith404** [comment]
Yeah you have to do the steps mentioned in #366 to change the source code of the dockerized Pingvin Share. That's because the website and backend is compiled in the Docker image.
