### ISSUE TITLE
🐛 Bug Report: Wenn Freigabe über Link nicht gefunden wird

### ISSUE THREAD

**Issue by thokich** [stonith404/pingvin-share#398]
### 👟 Reproduction steps

Freigabe erstellen, Mailfreigabe versenden, Freigabe löschen dann keine korrekte Seitendarstellung das keine Freigabe mehr vorhanden ist nach Drücken des ZURÜCK Buttons. Habe die App inder der :latest Version getestet.

### 👍 Expected behavior

.

### 👎 Actual Behavior

.

### 🌐 Browser

Chrome

**Comment by thokich** [comment]
![Bildschirmfoto 2024-02-04 um 23 33 26](https://github.com/stonith404/pingvin-share/assets/124937197/f8e710a5-b02a-4d11-9926-734688c4d467)

**Comment by stonith404** [comment]
Thanks. This is fixed and will be available in the next release. For the next time, please compose your issue in English, because else the other people won't understand it.

**Comment by thokich** [comment]
I'm looking forward to your new release. You make an innovative product, I like it very much. My next GitHub will be in English.
