### ISSUE TITLE
ZIP file being created for single-file shares, disk space wasted

### ISSUE THREAD

**Issue by kzshantonu** [stonith404/pingvin-share#40]
Hi, loving the project so far.
May I suggest disabling ZIP file generation and also disabling "Download all" button for single-file shares.
Makes no sense to download a zip file with one file in it

**Comment by stonith404** [comment]
Fixed in https://github.com/stonith404/pingvin-share/commit/3d1d4d0fc7c0351724387c3721280c334ae94d98
