### ISSUE TITLE
🚀 Feature: Oauth2 at runtime

### ISSUE THREAD

**Issue by RatCornu** [stonith404/pingvin-share#402]
### 🔖 Feature description

Currently, the Oauth2 configuration must be compiled with the backend. It could be interesting to try reading the variables directly from a file or from the environment (with variables like `OIDC_ENABLED`, `OIDC_DISCOVERY_URI`, ...).

### 🎤 Pitch

In NixOS, all the sources for the compilation are available in the nix store, which is in read-only (but it's not a problem here), and readable by all users (which is more concerning ^^'). Thus, having the client ID and secret not directly written in the source code would be a great improvement in my use case for security reasons.

**Comment by stonith404** [comment]
I'm not sure if I understood something wrong in your feature request but these OAuth2 variables aren't hard-coded in the source code and therefore also not compiled with the backend. They are stored in the database and can be changed by the user on the admin page.

**Comment by RatCornu** [comment]
Oh I'm sorry I misread the Oauth2 guide, I thought you had to write your configuration for your provider directly in `config.seed.ts`. It could still be interesting to try reading the variables directly from a file or from the environment but this is not as important as I thought anymore. Thanks!

**Comment by stonith404** [comment]
Great! Defining all config variables as environment variables is already requested in #258 because of that I'm closing this issue.
