### ISSUE TITLE
🚀 Feature: GUI Adjustment Options

### ISSUE THREAD

**Issue by itsdoublearon** [stonith404/pingvin-share#403]
### 🔖 Feature description

I would like the ability to adjust the layout of the page the end-user sees when landing on the share page. A big one being... a BIG download button. 

### 🎤 Pitch

I'm migrating off other third party download services and clients are use to BIG download buttons to get the file fast. I know this sounds strange, but some clients don't know what the little download icon is.

**Comment by stonith404** [comment]
For user specific changes like changing the size of the button, you have to fork the project and edit the code by your own. You can learn more about setting up the project in the [`CONTRIBUTING.md`](https://github.com/stonith404/pingvin-share/blob/main/CONTRIBUTING.md#setup-project) and in the issue #366.
