### ISSUE TITLE
🌐 Language request: Arabic

### ISSUE THREAD

**Issue by nitpack** [stonith404/pingvin-share#406]
### 🌐 Language name (native)

العربية

### 🌐 Language code

ar

**Comment by nitpack** [comment]
Arabic is RTL indeed, but if mean mirror-flipping the entire thing, I don't think it's necessary, we're used to items staying in same location when switching EN-->AR. Especially if it's gonna take your considerable effort to do it.

**Comment by stonith404** [comment]
@nitpack Okay, great! I added Arabic. I'll look into whether I can change the layout to RTL, but at the moment it is just LTR. Thanks for your contribution :)
