### ISSUE TITLE
"Download all" button on chromium-based browsers download file without extension

### ISSUE THREAD

**Issue by kzshantonu** [stonith404/pingvin-share#41]
Firefox seems to work fine

<img width="180" alt="brave_xRdBvoCD3h" src="https://user-images.githubusercontent.com/7745374/206882451-5ee2be87-4147-4d14-98ab-cd12557fca22.png">
<img width="110" alt="explorer_y3V5D4KzfC" src="https://user-images.githubusercontent.com/7745374/206882452-1f5fe211-5708-421c-be11-1c170cbfaa7e.png">

**Comment by stonith404** [comment]
Fixed in https://github.com/stonith404/pingvin-share/commit/5b0110877745f1fcde4952737a93c07ef4a2a92d
