### ISSUE TITLE
❓ Question: Pingvin Share not working behigh cloudflared tunnel

### ISSUE THREAD

**Issue by tatum163** [stonith404/pingvin-share#410]
### 🙋‍♂️ Question

I install Pingvin Share LXC from https://tteck.github.io/Proxmox/ It working! on local ip port 3000

But when i use cloudflared tunnel (for make domain) it's NOT working 
show : Application error: a client-side exception has occurred (see the browser console for more information).

maybe because **cloudflared tunnel is force HTTPS and my pingvin is http on port 3000**

How can i do ?  

If i use Nginx proxy manager can input some parameter in advance tab. it's work but now i have no public ip for use NPM.

**Comment by kzaoaai** [comment]
same exact setup with this issue.

**Comment by kzaoaai** [comment]
I used the solution in #362 ([link to post](https://github.com/stonith404/pingvin-share/issues/362#issuecomment-1906158102)), and it works now.
The key was re-installing the software after modifiying middleware.ts file. Instructions on the github readme.
