### ISSUE TITLE
🐛 Bug Report: Pingvin shows localhost url when running behind a reverse proxy

### ISSUE THREAD

**Issue by vinc3nz** [stonith404/pingvin-share#412]
### 👟 Reproduction steps

1. Install pingvin as shown in the readme (Standalone)
2. Set up a reverse proxy such as Cloudflare Tunnels
3. Upload a file and look at the generated url

### 👍 Expected behavior

It should provide the url from where I am trying to access to website. 
(Maybe allow setting the host via a environment variable or config file)

### 👎 Actual Behavior

It uses localhost:3000 (8102 in my case), which is of course not accessible from outside. Shares still work when accessing via the correct url.

### 🌐 Browser

Duckduckgo for Android

**Comment by stonith404** [comment]
You probably have to change the app URL on your admin dashboard. You can find the setting on `https://<your-domain>/admin/config/general`. Let me know if this fixes the issue.

**Comment by vinc3nz** [comment]
This actually fixed the problem. I would recommend adding a few lines that describe the possibilities to configure the share. At least I did not stumble around the admin dashboard when reading the installation guide.

**Comment by stonith404** [comment]
Yes, you're right. This step could be missed. I've just made the README a bit clearer for this step. You can find it in the [README config section](https://github.com/stonith404/pingvin-share?tab=readme-ov-file#configuration). Additionally there is a screen after the first user was registered that recommends to customize Pingvin Share by going to the admin dashboard.
