### ISSUE TITLE
❓ Question: Why do my upload speeds seem throttled on a local network?

### ISSUE THREAD

**Issue by Rage-GitHub** [stonith404/pingvin-share#419]
### 🙋‍♂️ Question

This may be a similar issue to #353 and #108 but it seems that my uploads, in particular this upload being ~25GB, seem to take ages even on a local network. Normally I use FileZilla to transfer large amounts of files and large files from my desktop to my at-home server and it transfers within minutes.

However, it seems that with Pingvin, my uploads are being seriously throttled and knocked down. My Ethernet capability is 1GB nad I have a network switch setup with both my desktop and server connected directly to my router.

The below is a screenshot of my Netdata interface for the server itself, with realtime stats.
![image](https://github.com/stonith404/pingvin-share/assets/17907584/b6077802-bc82-437d-8850-7c339ef44e07)

It also seems that when I attempt to upload these large files, I keep getting this error which unfortunately stops the upload completely. Though this could just be a issue related to Brave not being able to fully exercise the amount of resources I have on my PC.

![image](https://github.com/stonith404/pingvin-share/assets/17907584/006a2859-8eef-49c2-85ec-6fabef772b19)

**Comment by droplinxuser** [comment]
Maybe the chunk file size somewhat affects the upload speed?

**Comment by stonith404** [comment]
Yeah that's probably because the files get uploaded in chunks. You can change the chunk size since the last version. Feel free to create a bug report If the issue still occurs if you increase the chunk size.

Regarding the crash, this should be fixed too in the last version. If not feel free to create a bug report.

**Comment by stonith404** [comment]
Hm, okay :/ Feel free to create a bug report and please include your setup information, like the reverse proxy.
