### ISSUE TITLE
🐛 Bug Report:  The user opens the web page from the reverse share link and all files uploaded afterward are collected in the reverse share.

### ISSUE THREAD

**Issue by IvanLi-CN** [stonith404/pingvin-share#421]
### 👟 Reproduction steps

1. Create a reverse share and copy link.
2. Open by self, other user or anonymous.
3. Goto home and open upload page (not reverse sharing link).
4. Any files uploaded after that will collected in the reverse share.

### 👍 Expected behavior

Uploaded files are only collected in the reverse share when open reverse share link.

### 🌐 Browser

Chrome

---

There doesn't seem to be any place to clear `reverse_share_token` in Cookies. https://github.com/IvanLi-CN/pingvin-share/blob/f52dffdaac5a893804525913943f3f4f99b7c55a/frontend/src/pages/upload/%5BreverseShareToken%5D.tsx#L23

It seems that whenever `reverse_share_token` is present it is treated as a reverse shared file. https://github.com/IvanLi-CN/pingvin-share/blob/98380e2d48cc8ffa831d9b69cf5c0e8a40e28862/backend/src/share/share.controller.ts#L65

**Comment by stonith404** [comment]
Thanks for your report, I'll look into it.

**Comment by stonith404** [comment]
This was fixed in `v0.23.1`.
