### ISSUE TITLE
🚀 Feature: LDAP support

### ISSUE THREAD

**Issue by axiomen** [stonith404/pingvin-share#422]
### 🔖 Feature description

If possible, I'd like to see LDAP support to have all my services authenticate in one place for easy user access management.

### 🎤 Pitch

Whether it's in home server environment with third party authentication services, or in enterprise environtment with Microsoft implementation, LDAP support comes as a great tool for integrating Pingvin into a single local authentication provider.

**Comment by WolverinDEV** [comment]
Hey,  
I had the same need and quickly implemented it myself.  
It lacks support for any translations except English but works like a charm.  
I've attached a patchfile.  
[ldap.patch](https://github.com/user-attachments/files/16484359/ldap.patch)
