### ISSUE TITLE
🐛 Bug Report: v0.22.2 unable to upload a large file (no error/413/browser crash)

### ISSUE THREAD

**Issue by axiomen** [stonith404/pingvin-share#423]
### 👟 Reproduction steps

I wanted to test another bug (part of #241), but in the process discovered I'm unable to upload a large file (24GB in my test). I either don't get any error in Pingvin logs nor browser logs, or I get `413 Entity too large`. I thought the issue was with Caddy, so I added `max_size` directive to Caddyfile. First I attempted with 30GB, but I figure it only accepts in MB, so changed that accordingly, even though caddy shouldn't be setting any limit by itself if no directive is given. However, my browser crashed unexpectedly while testing that scenario. Furthermore, in the case of  `413` error, even after going to Settings or any other page on the Pingvin web UI, the browser console continues to get flooded with multiple errors (413, 500, some of which I remember seeing) upon failed upload.

Tested locally without proxy in the middle (HTTP over IP).

### 👍 Expected behavior

Successful upload of large files.

### 👎 Actual Behavior

With no changes to Caddyfile, the browser either stops with the upload, without any errors in the logs or UI (loading animation on Share button also keeps going), or reports `413 Entity too large` error. With changes to Caddyfile, the browser crashes. I'll be honest, I'm not at all familiar with caddy.

### 🌐 Browser

Firefox, Chrome

**Comment by stonith404** [comment]
This should probably be fixed in the latest release, as the maximum request body size is now exactly the same as the chunk size.

Can you confirm that the bug is fixed?

**Comment by stonith404** [comment]
Great, thanks!
