### ISSUE TITLE
"Reverse" shares (URL for file upload)

### ISSUE THREAD

**Issue by stautonico** [stonith404/pingvin-share#43]
A feature that I would really like to see is the ability to generate a URL which allows for a one time file upload. This could be used in cases where you want someone to send you a file, but it is large so hard to send over discord/email.

It would work as such:
1. The authenticated user generates a URL that leads to a file upload. (can have expiration, use count, etc.)
2. The user sends the link to someone
3. The other person can upload a file (ability to limit to specific size/mime type/file count, etc)
4. The authenticated user can view all the files uploaded to that specific URL via the shares dashboard, or possibly another dashboard.

This feature should be limited to authenticated users only.

This missing feature is the only thing stopping me from deploying this on my own server, and I would love to see it.

If this is something that you would like implemented into the program, I don't mind doing it myself and opening a PR.

**Comment by stonith404** [comment]
This feature sound really interesting! When we would have this feature, do think we would even need the feature that unauthenticated users can create shares anymore? 
If you want you are very welcome to work on it, I could probably work on this feature too but currently I'm really busy until Christmas.

**Comment by mztiq** [comment]
I'd love to see this implemented too ....wish I could contribute, but I'm no dev.

**Comment by stautonico** [comment]
> do think we would even need the feature that unauthenticated users can create shares anymore?

I think it would be a good idea to give users the choice: do they want anyone to be able to create shares, or do they only want some users to create shares, and maybe only once, like my proposed feature would implement. 

I am very busy as well as finals week is coming up soon. Perhaps we can put this feature on the back burner until then?

**Comment by stonith404** [comment]
@stautonico Sure, because this is a big feature.

**Comment by stonith404** [comment]
@mztiq This is a really big feature, but this will be the next issue I want to implement. Looking forward to implement this ASAP, when I have some free time:)

**Comment by mztiq** [comment]
Awesome, thanks for the quick reply!

**Comment by stonith404** [comment]
I think I'm almost finished. Could you guys give me some feedback? Here is a demo video #86 .

**Comment by mztiq** [comment]
Wow, this looks awesome and is going to make things so much easier for my use cases.
I have one question: Would it be possible for the creator to receive a (E-mail) notification once an unauthenticated user uploaded files to the share? This would be really neat.
Other than that I can't wait to test this feature myself.

Thanks again for your quick work!

**Comment by stonith404** [comment]
@mztiq Thanks for your feedback :)  That's a good suggestion, I'll look into it.

**Comment by stonith404** [comment]
@mztiq Do you think it's necessary that the user can configure the subject and message of this email notification?

**Comment by stautonico** [comment]
@stonith404 In my opinion, its not a super useful feature, but its probably not that hard to implement so may be worth considering.

**Comment by stonith404** [comment]
Added in `v0.8.0` :)

**Comment by mztiq** [comment]
Just tested it, works like a charm.
Thanks again for implementing this 👍.

**Comment by RollPitchYall** [comment]
This feature is exactly what I was looking for, I love pingvin share! Thanks so much for making it!
