### ISSUE TITLE
🚀 Feature: Decouple share name from URL token

### ISSUE THREAD

**Issue by Hely0n** [stonith404/pingvin-share#430]
### 🔖 Feature description

Right now, the generated token in the link is considered the name of the share. I think it would be better if those were decoupled and it will autogenerate a hard-to-guess URL token, that can be edited too if desired.
Additionally, isn't the currently generated token/name too short security-wise?

### 🎤 Pitch

If I share a photo album to my friends, I can't just name the link "Lisas Birthday" because it would be an easy-to-guess URL. Otherwise, if I take the generated token (or a longer one), the preview in Whatsapp for example will show "Share Y252aXsta...", so it doesn't look appealing for others 😅

**Comment by Hely0n** [comment]
Yes, both issues have the same goal :)

**Comment by stonith404** [comment]
Okay, I'll close this issue then as the other issue is older.

**Comment by Hely0n** [comment]
So it's not planned?

**Comment by stonith404** [comment]
Oh, sorry, I forgot that I had closed the other issue. This feature is definitely a good suggestion.

**Comment by Hely0n** [comment]
Thank you very much!

**Comment by stonith404** [comment]
I've just implemented this feature. It will be released in the next release :)
