### ISSUE TITLE
🚀 Feature: Requesting that the chunk file size be a configurable option

### ISSUE THREAD

**Issue by droplinxuser** [stonith404/pingvin-share#431]
### 🔖 Feature description

Requesting that the chunk file size be a configurable option.

Right now, I think it's fixed at 10MB. 
I would like to increase it to something like 50MB.

### 🎤 Pitch

The reason for this request is to hopefully speed up the upload speed.

**Comment by stonith404** [comment]
Added in the newest version. You can find the setting in the share tab of the admin settings.

**Comment by droplinxuser** [comment]
That is very quick; I'll test it now.
Thanks a lot.

**Comment by droplinxuser** [comment]
Increasing it, I always got this error during large file uploads:
`413 Payload Too Large`

I tried 32, 25, and 20MB chunk sizes so far.
Cloudflare allows 100MB; my Nginx allows 1GB.

**Comment by droplinxuser** [comment]
On the front-end app, I got this log:
```
node[2416818]: 
API response for /api/shares/1gb/files/e9d69354-515d-455d-a608-2468044ce8b5 exceeds 4MB. 
API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit

```
So I lower it down to 4MB to prevent the error above.

**Comment by stonith404** [comment]
Oh I have found the issue. The limit for the body parser gets set in the bootstrap function of the backend which only gets called when the application starts. So if you change the chunk size the changes will only be applied when you restart the application.

I'll release a fix later today until then you have to restart the application. Thanks for your feedback!

**Comment by droplinxuser** [comment]
> On the front-end app, I got this log:
> 
> ```
> node[2416818]: 
> API response for /api/shares/1gb/files/e9d69354-515d-455d-a608-2468044ce8b5 exceeds 4MB. 
> API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
> ```

I think this error log or warning happens when a large file is downloaded, like this URI path for a 1GB file.
Not related to file uploads, I guess.

**Comment by stonith404** [comment]
So the error occurs when you want to download a file?

**Comment by droplinxuser** [comment]
> So, does the error occur when you try to download a file?

Yes correct.
