### ISSUE TITLE
❓ Question: Uncaught Error: Minified React error #425

### ISSUE THREAD

**Issue by droplinxuser** [stonith404/pingvin-share#437]
### 🙋‍♂️ Question

I got this browser console error log:

> Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Which means "text content does not match server-rendered HTML."

Only if I add this to my Nginx configuration:
`proxy_set_header Accept-Encoding "";`

I specifically added it so I can use the nginx **sub_filter**:
https://nginx.org/en/docs/http/ngx_http_sub_module.html

Without it, **sub_filter** doesn't work.
Any advice from nginx users?

**Comment by droplinxuser** [comment]
Is there any way we can specifically ignore or disable mismatch error logging on the front end?

Thank you :)

**Comment by stonith404** [comment]
The issue is just the error in the logs, right? The behaviour of Pingvin Share doesn't change?

 Would you mind to share why you have to use `sub_filter`?

**Comment by droplinxuser** [comment]
Yeah, the only issue is in the browser console log; the app and website work fine as expected.

I use `sub_filter` to insert and modify the HTML output without directly modifying the source of Pingvin, as I'm not an expert on this type of coding language.

I just want to insert links to my site on the home page and in the footer.

**Comment by stonith404** [comment]
Okay then the error "text content does not match server-rendered HTML." makes sense as you are manipulating the html. 

As far as I know it is not possible to ignore this error as this is thrown by React. But I mean if the error is just in the logs and the user doesn't notice anything it isn't really that bad.

**Comment by droplinxuser** [comment]
Even if I haven't applied the `sub_filter` yet, that error goes into the logs already.

I think it's because the Pingvin backend/app generates the rendered HTML without compressing it with gzip/brotli (because I set this `proxy_set_header Accept-Encoding "";`).
But when it reaches Nginx, Nginx compresses it with either gzip or brotli before it sends it to the user.

That's why it doesn't match anymore in terms of size.

Yes, it isn't that bad either :).
Right now, I only impose it on some URIs, except the homepage.

I'll close this for now, Thank you so much :)
