### ISSUE TITLE
Ability to leave description

### ISSUE THREAD

**Issue by MasterChiefv1** [stonith404/pingvin-share#44]
Hi, great application can i have the ability to leave a note?
So i can know what i have uploaded?

**Comment by stonith404** [comment]
Thanks:) You mean something like a share description?

**Comment by stautonico** [comment]
Share description seems like a reasonable feature. Seems pretty simple to implement

**Comment by stonith404** [comment]
Can work on that today 👍 Should be easy to implement

**Comment by MasterChiefv1** [comment]
Yeah sorry, i mean indeed something like description.
Thank you, keep it up.

**Comment by MasterChiefv1** [comment]
Thanks... keep it up.
