### ISSUE TITLE
❓ Question: Updating past docker image 1.22.1

### ISSUE THREAD

**Issue by SierraKomodo** [stonith404/pingvin-share#442]
### 🙋‍♂️ Question

I've been having an issue with updating an existing docker container from 1.22.1 to any of the later versions. On 1.22.1, the container boots up and the web page loads normally. However, when changing the container version to 1.22.2 or later, re-pulling the image, and restarting the container, the container still boots up but it only serves a blank white screen. Inspecting and comparing the logs between versions, I've noticed this line at the beginning of the log for v1.22.2 and later (Up to v1.23.1 as of writing):

```
2024-04-06 11:10:45
/bin/sh: nginx: not found
```

It looks like it's trying to run nginx instead of caddy when I update the existing container. Any ideas?

**Comment by stonith404** [comment]
That's strange. I replaced Nginx with Caddy in version `0.22.2`, but since this release, there isn't any reference to Nginx left in the project. You don't build the Docker image yourself, do you?

**Comment by SierraKomodo** [comment]
> That's strange. I replaced Nginx with Caddy in version `0.22.2`, but since this release, there isn't any reference to Nginx left in the project. You don't build the Docker image yourself, do you?

I don't - I'm pulling the images as `stonith404/pingvin-share:{version-number-here}`

**Comment by stonith404** [comment]
Maybe Docker tries to get the last layer from the cache. Please try to delete all images of Pingvin Share and recreate the container:

```
cd pingvin-share
docker compose down
docker rmi $(docker images | grep 'stonith404/pingvin-share')
docker compose up -d
```

**Comment by SierraKomodo** [comment]
Doesn't look like following those steps have resolved it. I cloned things over to my desktop for further testing and discovered that installing v0.22.1 then updating to 0.22.2 works perfectly fine from here so something on my server seems to be the culprit.

I'm going to try backing up the volume, thoroughly purging the container and compose file, and reinstalling with the latest version in a new file and see if that works.

**Comment by SierraKomodo** [comment]
Okay I have no idea what was broken but it's working now after I've done that, with the old volume bound to it. I'm chalking this one up to computer black magic.

**Comment by stonith404** [comment]
Really strange. But at least it works now :)
