### ISSUE TITLE
❓ Question:

### ISSUE THREAD

**Issue by elooox77** [stonith404/pingvin-share#456]
### 🙋‍♂️ Question

Bonjour,

J'ai un problème lorsque j'arrive sur mon interface web, je n'arrive pas à créér de compte cela me remet automatiquement la page de création de compte et je n'ai pas la même interface. Alors que j'ai bien tout démarré 
![error pinving-share](https://github.com/stonith404/pingvin-share/assets/165184869/9b06a6b6-0462-4b8a-b234-6f8d7e3bd2ac)

**Comment by stonith404** [comment]
Please create a new issue in English as not everyone understands French here. Thanks :)

**Comment by elooox77** [comment]
Hello,

I have a problem when I get to my web interface, I can't create an account. It automatically returns me to the account creation page and I don't have the same interface. Even though I've started everything
