### ISSUE TITLE
❓ Question: Is there a Discord server?

### ISSUE THREAD

**Issue by InvitedToHell** [stonith404/pingvin-share#458]
### 🙋‍♂️ Question

I wanted to ask if there is any kind of Discord or Fediverse Server to join, that lets users talk about this project. I'd love to see one if there is none yet!

**Comment by stonith404** [comment]
No, there isn't a Discord server yet. But I'm not sure if there is even a real use case for it. Why do you think this could be useful?

**Comment by InvitedToHell** [comment]
I feel like most open source  projects have one. Pingvin Share could grow bigger with a community. Also you could have a channel for community support. When someone does not understand something, he could ask for help there. Anyone with knowledge could answer those questions. 

Furthermore I think it would be helpful to discuss features there and upvote the ones you find helpful. It gets more community driven by that.

**Comment by stonith404** [comment]
Okay, thanks for explaining this further. Currently, I have much to do, and I don't really have the time to be active in the server. Do you think it makes sense nevertheless? 

Also, do you have any good examples of a good Discord servers for open-source projects that I could checkout for inspiration?

**Comment by InvitedToHell** [comment]
I think it would still make sense. You would not have to be more active than you are on GitHub. Just do it the same way you manage your issues. 

I have 3 servers that I really think benefited from Discord servers. Those would be the one from [ntfy](https://github.com/binwiederhier/ntfy), [nilesoft-shell](https://github.com/moudey/Shell) and of course the [Catppuccin](https://github.com/catppuccin/catppuccin) server. (But that's an entire community for several things, so you might ignore that one)

ntfy: https://discord.gg/KadKMAXPcp
nilesoft-shell: https://discord.gg/9ENF6atxHz
Catppuccin: https://discord.gg/catppuccin

**Comment by stonith404** [comment]
Great, thanks :) I'll look into it ASAP. I've never created a Discord server before, so the setup could take some time.

**Comment by InvitedToHell** [comment]
I am here to help if you need any. I can also set it up, if that helps.

**Comment by stonith404** [comment]
@InvitedToHell Sorry for my delayed response. If you have experience in creating Discord servers and are interested in helping, I would love your help for setting it up! Here's the link to the [Discord server](https://discord.gg/WJJXqJZW). As soon as you I can make you admin :)

**Comment by InvitedToHell** [comment]
I've joined already! c:

# Continuing this issue as soon as the Server is ready.
