### ISSUE TITLE
❓ Question: How to share files with only specific users

### ISSUE THREAD

**Issue by maurxce** [stonith404/pingvin-share#471]
### 🙋‍♂️ Question

![image](https://github.com/stonith404/pingvin-share/assets/91284394/5c6a9e83-97a1-478d-9731-f4a4f81343fa)
There's this setting, but I can't figure out how to share something with only specific users (without using a password)

**Comment by stonith404** [comment]
You have to enable SMTP and then you can specify the users which should get an email:
![image](https://github.com/stonith404/pingvin-share/assets/58886915/a0ab3427-6f60-4597-a52b-7c36f89951f6)

Just so you know, the share won’t be limited to only those users. Anyone with the link can access the share.

**Comment by maurxce** [comment]
Oh, thanks!

> Just so you know, the share won’t be limited to only those users. Anyone with the link can access the share.  
Is there a placeholder for the password of the share? So I can share it in the same email?

**Comment by stonith404** [comment]
No, but you could use a more random link. If you send the password in the same email as the link, the password becomes useless. When you send a link to a shared file along with its password in the same email, anyone who gains access to that email can use both the link and the password to access the share. Or am I missing something?

**Comment by stonith404** [comment]
Okay, that makes sense. Don’t you think the safest solution would be to send the password separately through another messaging service? This way, an attacker would need access to two different services to access the share.

Regarding your question, are you trying to share the file with someone who has a Pingvin Share account, or not?

**Comment by maurxce** [comment]
Sure, 2 different messages across 2 different services is safer, but it would require *2 services*.
Yes it's possible, but I think there has to be a better way

And yes, I would want to share it with a different Pingvin Share account on the same installation

**Comment by stonith404** [comment]
Yeah, that’s definitely too time-consuming if the other user has an account as well. It would be nice to specify specific Pingvin Share users when creating a share, so only those users can access the shared content when they are logged in. This would probably be the best solution, right?

**Comment by maurxce** [comment]
Yeah, that would be really nice

**Comment by stonith404** [comment]
Okay, please create a feature request so we can track this request more easily. Thanks :)
