### ISSUE TITLE
🐛 Bug Report: How To Fix Spacing For <h1> Tag In HomePage?

### ISSUE THREAD

**Issue by fmunim** [stonith404/pingvin-share#473]
### 👟 Reproduction steps

- Go to homepage
- See

https://github.com/stonith404/pingvin-share/assets/32178410/781a8a10-bbde-4923-8d2b-fede3b82b54d

### 👍 Expected behavior

- `<h1>` tag should have a space like the first space between, but in when the tag ends there is not? 
- `<h1></h1>` tag has a whitespace at the end also, which should not be highlighted within `<h1>` but be outside of it

### 👎 Actual Behavior

It be consistent in the spacing and not have weird behavior like shown in the video

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Thanks, I have fixed it, and it will be included in the next release :)
