### ISSUE TITLE
❓ Question: Cannot access via domain

### ISSUE THREAD

**Issue by LovroGrilc** [stonith404/pingvin-share#478]
### 🙋‍♂️ Question

Hi, i have a problem. I cannot access the application via my domain name if i don't specify port after the domain. How can i fix that. I have tried to change app url in settings but it doesn't work. The domain is subdomain and it is pointed to public ip of my VPS. I'm using OVH vps with ubuntu installed.

**Comment by stonith404** [comment]
You can change the port of the container in the `docker-compose.yml` to `80`.
```
   ...
    ports:
      - 80:3000
   ...
```

But if you want to use HTTPS (which is recommended), I would use a reverse proxy. If you don't have experience with reverse proxies, I can recommend you Nginx Proxy Manager.
