### ISSUE TITLE
The link does not open through some email clients

### ISSUE THREAD

**Issue by imswel** [stonith404/pingvin-share#48]
### 👟 Reproduction steps

When I click on the link through the windows mail application, it sends me to an invalid link because the mail client considers the dot at the end of the link. However when I open the same email on the Gmail site directly it works.

> Hey!
> [USERNAME] shared some files with you. View or dowload the files with this link: https://exemple.com/share/UtNxQ6M.
> Shared securely with Pingvin Share 🐧

I suggest just removing the dot at the end of the link, this will fix the issue on all affected email clients.

### 👍 Expected behavior

The link should work on all email clients

### 👎 Actual Behavior

This does not work on all clients because of the dot

### 🌐 Browser

Mail App Windows

**Comment by stonith404** [comment]
Should be fixed 9b0c08d0cdeeeef217ccba57f593fea9d8858371 :)
