### ISSUE TITLE
🐛 Bug Report: Incorrect File Size Display in "Share Informations" Section

### ISSUE THREAD

**Issue by Samppady** [stonith404/pingvin-share#481]
### 👟 Reproduction steps

    1) Log in to the site (self-hosted Pingvin Share, Docker).
    2) Upload a file (any file or jpg).
    3) Go to the "My Shares" section.

When I view the details of the recently uploaded file in the "Share informations" section, the share appears as follows: Size: NaN undefined / 1.0 GB (NaN%)

However, the "Administration Share management" shows the correct information.

### 👍 Expected behavior

The file size should be displayed correctly.

### 👎 Actual Behavior

In the "Share informations" section, the size is displayed as: Size: NaN undefined / 1.0 GB (NaN%)

### 🌐 Browser

Firefox 126.0

**Comment by Samppady** [comment]
![file1](https://github.com/stonith404/pingvin-share/assets/123966061/d574cdc2-65fb-4557-9264-7f1774553a35)
![file2](https://github.com/stonith404/pingvin-share/assets/123966061/2b84d6cb-dfa0-43d6-89b8-473c2f9b1e08)

**Comment by stonith404** [comment]
Thanks for your report :) This is fixed and will be released in the next release.
