### ISSUE TITLE
🚀 Feature: File previews for videos, images, PDFs

### ISSUE THREAD

**Issue by Hukuma1** [stonith404/pingvin-share#49]
### 🔖 Feature description

If the file(s) being shared are videos (e.g. `mp4`), allow the user to stream/preview the file. WeTransfer does this seamlessly for example.

### 🎤 Pitch

Perhaps there are multiple files shared and you only need one specific video. Without downloading them all, you can quickly preview/scrub/find the one you want before downloading. Or perhaps you simply want to do a remote playback without downloading anything, like streaming a video on Youtube.

**Comment by stonith404** [comment]
Good idea! Image previews would also be nice.

**Comment by viperr-san** [comment]
> Good idea! Image previews would also be nice.

Would also love it if there was a way to embed a single video or image file on Discord so Pingvin could function as a self hosted alternative to something like Streamable,

**Comment by stonith404** [comment]
@viperr-san Sharing a file directly (without clicking the download button) is unfortunately impossible because of the security feature like visitor limit.

**Comment by Hukuma1** [comment]
If a person clicks the preview image of the video it would count as a visitor/download, no? Or is the visitor/download limit two separate parameters being tracked?

**Comment by Hukuma1** [comment]
Updated the title to reflect a bigger feature request. Perhaps it could also be optional for people who wish to keep a minimal UI experience as well? e.g. toggle switch for enabling previews for images, another switch for videos, and another for word documents.

**Comment by stonith404** [comment]
@Hukuma1 Thanks. I think that's the next issue that I want to implement. I think I will not implement previews for special files like word because that's in my opinion an over-kill for a file sharing platform. But I definitely looking forward to implement previews for images, videos and PDFs.

**Comment by stonith404** [comment]
Added in https://github.com/stonith404/pingvin-share/commit/91a6b3f716d37d7831e17a7be1cdb35cb23da705 and will be released soon. 
Currently we only support files that are supported natively by the browser:
- PDF
- Audio: MP3, WAV, OGG
- Video: MP4, WebM, OGG
- Images

In my opinion it would be an over-kill if we add support for files that aren't natively supported by the browser because then we would need an library for each file type.

**Comment by stonith404** [comment]
Added in `v0.9.0` :)

**Comment by Hukuma1** [comment]
This is awesome and you implemented this so quickly! Thank you!

Even AV1 video works (MP4 container). And FLAC for audio. Crazy. :)
