### ISSUE TITLE
🚀 Feature:  virus scan for uploaded files from external sources

### ISSUE THREAD

**Issue by tschoene** [stonith404/pingvin-share#50]
### 🔖 Feature description

hi, first I want to say, that pingvin-shares is an amazing software! Thank you very much! I like the requested feature for generating upload links for external but known people. but for this feature, i think it is also necessary to check the files for viruses or other malware in some way. Have there already been requests in this regard? best wishes Torsten 

### 🎤 Pitch

Virus and malware scan for incoming files.

**Comment by stonith404** [comment]
Good idea! Currently there are a lot of feature requests and I'm really busy at the moment. But looking forward to implement this or maybe there is someone that did something similar in the past, who wants to work on this :)

**Comment by stonith404** [comment]
added in 76088cc76aedae709f06deaee2244efcf6a22bed

**Comment by stonith404** [comment]
Released in `v0.7.0`. See the README, to learn how to set it up.
