### ISSUE TITLE
🚀 Feature: Add email recipients more efficiently

### ISSUE THREAD

**Issue by adan89lion** [stonith404/pingvin-share#500]
### 🔖 Feature description

In Pingvin, it is counterproductive to add email recipents: you must type an email address, and click on the "autosuggestion" dropdown (which doesn't suggest anything) in order to add a single email address.

There are two major ways I can think of to improve this part:
1. Use Gmail-esque email form, which automatically submit an email address when typing the `,` (comma) symbol, so users can manually type in multiple email addresses without clicking the dropdown box all the time.
2. Use `type="email"` in the email form, and let the browser auto-detects a valid email address, and submit the form if the browser allows to.

### 🎤 Pitch

I frequently use Pingvin to share files across my devices, and send an email notification to my self-hosted mailbox as a reminder. However, I find that adding email recipients in Pingvin can be improved with this small tweak, which can be useful for other Pingvin users, too.

**Comment by RahulMishra0722** [comment]
hey where is this located i cant find this all i see is this
<img width="1697" alt="Screenshot 2024-06-19 at 10 17 15 PM" src="https://github.com/stonith404/pingvin-share/assets/119395914/890f89c0-897e-4297-9e4c-da63fd3d7e0a">

**Comment by RahulMishra0722** [comment]
@stonith404  this was resolved can we close this for other contributors/for less confusion Thanks
