### ISSUE TITLE
🐛 Bug Report:  Does not delete expired files on the server

### ISSUE THREAD

**Issue by ruiribeiro2010** [stonith404/pingvin-share#502]
### 👟 Reproduction steps

Hello, congratulations on the software,

I don't know if it's a bug, but it must be.

When I share with an expiration date, it disappears from the website at the end of time, but if you look at it in the folder on the server unraid, it doesn't delete it, it should.

If I delete a share on the client account, this already deletes the file on the server.

compliments

### 👍 Expected behavior

delete expired shared file from server

### 👎 Actual Behavior

The shared link disappears on the website, but does not delete the file on the server

### 🌐 Browser

Firefox, Edge

**Comment by stonith404** [comment]
There is a job that cleans up every file of expired shares every hour. Can you check again if the files are still there?

**Comment by ruiribeiro2010** [comment]
> There is a job that cleans up every file of expired shares every hour. Can you check again if the files are still there?

Hi, yes, in fact, after 1 hour, it disappears from the server, so it must be working fine

**Comment by stonith404** [comment]
Okay, great, then I'm going to close this.
