### ISSUE TITLE
🐛 Bug Report: Provider username is ignored when signing up using OAuth

### ISSUE THREAD

**Issue by marvinruder** [stonith404/pingvin-share#505]
### 👟 Reproduction steps

When I sign up using my OAuth Provider (I use OIDC)

### 👍 Expected behavior

It should take the new user’s username from the provider (configured claim or `preferred_username`)

### 👎 Actual Behavior

It actually derives the username from the email address

### 🌐 Browser

Safari

**Comment by stonith404** [comment]
Thanks for your report. Did you set the `OpenID Connect username claim` variable in the admin settings? 

Currently the username gets derived in the following order:
```js
    const username = claim
      ? idTokenData[claim] // <-- claim is the `OpenID Connect username claim` variable
      : idTokenData.name ||
        idTokenData.nickname ||
        idTokenData.preferred_username;
```

Is it possible that the `name` claim of your OIDC provider is the email?

**Comment by marvinruder** [comment]
The username is correctly extracted using `idTokenData[claim]` and used as the `OAuthUser`’s `providerUsername`, which I can verify on the “My account” page. However it is not used as the user’s username, which appears to always be derived from the email address in https://github.com/stonith404/pingvin-share/blob/6d6b9e81fff27989d7a3a82de28a8e60cc382ddb/backend/src/oauth/oauth.service.ts#L156
