### ISSUE TITLE
🚀 Feature: Configure session timeout

### ISSUE THREAD

**Issue by marvinruder** [stonith404/pingvin-share#507]
### 🔖 Feature description

A configuration option is added that defines the time of inactivity after which the session cookies expire and a user must sign in again.

### 🎤 Pitch

The existing timeout appears to be quite large (3 months) and allowing to reduce it to a shorter period of time may enhance security.

**Comment by RahulMishra0722** [comment]
based on the acess token both for user and admin its 15 minutes could you clarify what exactly are you asking?
<img width="469" alt="Screenshot 2024-06-29 at 10 05 19 AM" src="https://github.com/stonith404/pingvin-share/assets/119395914/e745452b-9cd2-4d30-9062-b83785098108">

**Comment by marvinruder** [comment]
@RahulMishra0722 This morning, I was already logged in to Pingvin Share when I opened the page for the first time, so I must assume that a session can be longer than 15 minutes. Specifically, the `access_token` cookie in my browser will expire on September 27, in approximately 3 months: 

![image](https://github.com/stonith404/pingvin-share/assets/18495294/94a15ff8-1657-4126-92bf-bf2da00b0251)

I believe this is set here:

https://github.com/stonith404/pingvin-share/blob/6d6b9e81fff27989d7a3a82de28a8e60cc382ddb/backend/src/auth/auth.service.ts#L232

**Comment by marvinruder** [comment]
On second thoughts, I find it odd that an access token is created with a TTL of 15 minutes in

https://github.com/stonith404/pingvin-share/blob/6d6b9e81fff27989d7a3a82de28a8e60cc382ddb/backend/src/auth/auth.service.ts#L169

but refreshed with a TTL of 3 months in

https://github.com/stonith404/pingvin-share/blob/6d6b9e81fff27989d7a3a82de28a8e60cc382ddb/backend/src/auth/auth.service.ts#L232

@stonith404 Is this intentional?

I would be fine with a session TTL of 15 minutes, I would not need a configuration option then, so maybe this should be considered a bug instead?

**Comment by RahulMishra0722** [comment]
yaa i noticed i started again and i was logged in tho i closed it like2 hours ago

**Comment by stonith404** [comment]
Yeah the `maxAge` of an access token cookie should only be 15 minutes, but it's not critical as the token expires after 15 minutes anyways. 

While having a token valid for 3 months is less secure than one that expires in 15 minutes, I don’t see it as a major security risk. The refresh token is an HTTP-only cookie, valid only for the path /api/auth/token, so it can only be stolen if someone intercepts your traffic without HTTPS or has full access to your device. Or am I missing something?

**Comment by marvinruder** [comment]
> While having a token valid for 3 months is less secure than one that expires in 15 minutes, I don’t see it as a major security risk. The refresh token is an HTTP-only cookie, valid only for the path /api/auth/token, so it can only be stolen if someone intercepts your traffic without HTTPS or has full access to your device. Or am I missing something?

Full access to the device is an interesting attack vector in my opinion. Pingvin Share is a very convenient way to share files from the computer of a friend, a client, or your local public library, to have them available later elsewhere. If a user forgets to log out, that friend, client or anyone at your local public library has access to all your shared files for the next 3 months.

It would be nice to be able to limit that time period (= validity of the refresh token, if I understand the authentication concept correctly) to something shorter than 3 months.

**Comment by stonith404** [comment]
Yeah sure, adding an option to change the session duration makes sense. I just don't really see a reason to change the default value.
