### ISSUE TITLE
🚀 Feature: Allow the Traffic from a specific IP or Domain Name

### ISSUE THREAD

**Issue by Zac10ck** [stonith404/pingvin-share#519]
### 🔖 Feature description

Add an Option to whitelist certain IP addresses or Domain Names for accessing the application 

### 🎤 Pitch

It would be beneficial to implement a feature that allows for whitelisting traffic from specific IP addresses or domain names. This would enable administrators to grant authorized access to a predetermined set of users, thereby mitigating the risk of unauthorized access or downloads. Doing so would protect sensitive files from potential security breaches, and only trusted sources would be permitted to interact with the system. This feature would provide an additional layer of security and control, ensuring the integrity and confidentiality of sensitive data.

**Comment by stonith404** [comment]
For this type of feature, I would recommend you to use a reverse proxy. You can place Pingvin Share behind a reverse proxy and configure the allowed IP addresses in the configuration of the reverse proxy. Here is an example with [Nginx](https://ubiq.co/tech-blog/block-ip-address-nginx).

**Comment by Zac10ck** [comment]
@stonith404   Thanks a lot boss - currently the Pingvin Share is running on a docker and managed through Portainer (because there are some other Dockers too running on the same Linux server ) 

Thanks a lot for your valuable recommendations I will try the Nginx reverse proxy. but just think about this feature - maybe on a future release 

- Abin Abraham Anchery
