### ISSUE TITLE
🐛 Bug Report: Upload times out after 5 minutes

### ISSUE THREAD

**Issue by andreidelait** [stonith404/pingvin-share#53]
### 👟 Reproduction steps

When I upload a large file (minimum 8 GB recommended)

### 👍 Expected behavior

It should complete the upload

### 👎 Actual Behavior

After uploading like 6.5 GB it shows "An unknown error occurred" and the upload stops.
Also the temp file will remain in /uploads/_temp until I manually delete it.
![Untitled](https://user-images.githubusercontent.com/76945620/208101164-d2b861a8-ea80-4704-8a89-7ca179a613dc.png)

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Could you try it again and look out for errors in the network tab of chrome and share them? The temporary files get cleaned every hour btw.

**Comment by andreidelait** [comment]
![Screenshot 2022-12-16 165829](https://user-images.githubusercontent.com/76945620/208126041-0bc5477c-2c19-435d-889b-12e9fdb21629.png)
If you need me to export the data somehow let me know.
Thank you.

**Comment by stonith404** [comment]
Thanks. It looks like the request gets aborted after 5 minutes. I'll look into it.

**Comment by stonith404** [comment]
Seems like a bigger issue. I'll try to implement chunked uploads #42 anyway, this will fix it.

**Comment by stonith404** [comment]
Should be fixed with chunk uploads in the last release.
