### ISSUE TITLE
🐛 Bug Report: HTTP ERROR 431 after updating

### ISSUE THREAD

**Issue by droplinxuser** [stonith404/pingvin-share#533]
### 👟 Reproduction steps

- Login as admin or normal user
- Update to the latest version, 0.27.0
- Visit the site again after updating
- Now the user will be greeted with an error page saying "HTTP ERROR 431"

### 👍 Expected behavior

The site should work fine after the update.

### 👎 Actual Behavior

The site now displays: HTTP ERROR 431

But the site works fine on other browsers or in incognito mode.
The solution for now is to clear browser cookies and caches, but not all normal users know this.

### 🌐 Browser

Chrome latest on MacOS

**Comment by stonith404** [comment]
Strange, I can't reproduce that. Do you still have a browser where the issue still occurs so that we can debug this further?

**Comment by droplinxuser** [comment]
I cannot debug this further as the browser that is returning the error now, after a few restarts, works fine again.

**Comment by droplinxuser** [comment]
On the same browser, I got the same error again: 431 (Request Header Fields Too Large)
This time during uploads and uploads fails with the error appearing on the browser console.

<img width="532" alt="image" src="https://github.com/user-attachments/assets/ce27f5c5-b5b1-4522-a327-aa125a43c2ea">

On other browsers or in incognito mode, it still works fine.

**Comment by droplinxuser** [comment]
I tried adjusting my Nginx configuration to:
`large_client_header_buffers 8 256k;
`
It still doesn't work.

**Comment by droplinxuser** [comment]
Maybe I have too many cookie stored for this domain on my main browser?
I restarted my browser and the cookies persist.

<img width="872" alt="image" src="https://github.com/user-attachments/assets/44e251f6-3c4f-4762-ac99-969120a7bb96">

**Comment by stonith404** [comment]
Oh yeah that's probably the issue.  Thanks for sharing this information, I'll try to fix it ASAP :)

**Comment by droplinxuser** [comment]
HI,

Thanks a lot for the update.
I applied your patch to my installation, tried a new upload on the browser I'm having problem.
Still, I cannot upload with the same error on the console: "431 (Request Header Fields Too Large)."

Does it mean my only fix for now is to clear cookies manually?

**Comment by stonith404** [comment]
Yeah, you have to clear the cookies manually, unfortunately.  Once you did this, only the 10 newest share token cookies will be stored, which should fix the problem.

Typically, these cookies are automatically cleared when you close your browser. However, if you have enabled the “Continue where you left off” feature in Chrome, this prevents cookies from being cleared after the browser is closed.

**Comment by droplinxuser** [comment]
> However, if you have enabled the “Continue where you left off” feature in Chrome, this prevents cookies from being cleared after the browser is closed.

Yeah, this is what I always do.
