### ISSUE TITLE
🚀 Feature: Better Uploading

### ISSUE THREAD

**Issue by COMPLEXWASTAKEN** [stonith404/pingvin-share#537]
### 🔖 Feature description

you should add to where when its uploading it has a real time upload speed and % of whats its add and etc 

### 🎤 Pitch

in my use case i would like to have it because it looks better and is better to know what % its at and the upload time your at

**Comment by stonith404** [comment]
I'm closing this in favour of #199. Feel free to participate in the discussion there.
