### ISSUE TITLE
🐛 Bug Report: Download with {"message":"Unauthorized"}

### ISSUE THREAD

**Issue by pronyxhack** [stonith404/pingvin-share#54]
### 👟 Reproduction steps

Share a file.
Access the link
I click in "Download"

### 👍 Expected behavior

I should download a file.

### 👎 Actual Behavior

When I click  in download a file a receive the {"message":"Unauthorized"}

### 🌐 Browser

Firefox & Chrome

**Comment by stonith404** [comment]
Are you signed in?

**Comment by stautonico** [comment]
Please put a description of the issue in the title

**Comment by pronyxhack** [comment]
> 

Both. Signed ou Unsigned. With admin or normal user.

**Comment by stautonico** [comment]
Running in a docker container or via the console in dev mode? 
If you can, please provide any output from the docker container/dev console.

**Comment by pronyxhack** [comment]
In a docker container. Not error into log docker.

**Comment by pronyxhack** [comment]
I believe that the port was incorrect. The application was 3000 and docker 3003.
