### ISSUE TITLE
🐛 Bug Report: trying to setup openid connected

### ISSUE THREAD

**Issue by tinytempmouse** [stonith404/pingvin-share#541]
### 👟 Reproduction steps

Hiya, I'm trying to get authentik working with pingvin however have gotten a bit lost. I can't tell if its something I've done wrong. I've set the redirects in authentik to https://pinvin/api/oauth/callback/oidc
And in pingvin set discovery url to https://authentik/application/o/pingvin/.well-known/openid-configuration
As well as client id and secret from authentik.

### 👍 Expected behavior

Will do auth magic 

### 👎 Actual Behavior

When I click the openid button it opens this page:
https://pingvin/api/oauth/auth/oidc
With this message:
{"statusCode":500,"message":"Internal server error"}
And this log:
`pingvin          | [Nest] 40  - 07/25/2024, 1:45:52 AM   ERROR [ExceptionsHandler]
fetch failed
pingvin          | TypeError: fetch failed
pingvin          |     at node:internal/deps/undici/undici:12502:13
pingvin          |     at process.processTicksAndRejections (node:internal/process/
task_queues:95:5)
pingvin          |     at async OidcProvider.fetchConfiguration (/opt/app/backend/d
ist/src/oauth/provider/genericOidc.provider.js:133:21)
pingvin          |     at async OidcProvider.getConfiguration (/opt/app/backend/dis
t/src/oauth/provider/genericOidc.provider.js:29:13)
pingvin          |     at async OidcProvider.getAuthEndpoint (/opt/app/backend/dist
/src/oauth/provider/genericOidc.provider.js:40:31)
pingvin          |     at async OAuthController.auth (/opt/app/backend/dist/src/oau
th/oauth.controller.js:44:21)`

### 🌐 Browser

Chrome and Firefox

**Comment by stonith404** [comment]
Can you open the URL https://authentik/application/o/pingvin/.well-known/openid-configuration in the browser and share the output?

**Comment by tinytempmouse** [comment]
Sorry for the delay:
`{
  "issuer": "https://authentik/application/o/pingvin/",
  "authorization_endpoint": "https://authentik/application/o/authorize/",
  "token_endpoint": "https://authentik/application/o/token/",
  "userinfo_endpoint": "https://authentik/application/o/userinfo/",
  "end_session_endpoint": "https://authentik/application/o/pingvin/end-session/",
  "introspection_endpoint": "https://authentik/application/o/introspect/",
  "revocation_endpoint": "https://authentik/application/o/revoke/",
  "device_authorization_endpoint": "https://authentik/application/o/device/",
  "response_types_supported": [
    "code",
    "id_token",
    "id_token token",
    "code token",
    "code id_token",
    "code id_token token"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post"
  ],
  "jwks_uri": "https://authentik/application/o/pingvin/jwks/",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "implicit",
    "client_credentials",
    "password",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic"
  ],
  "acr_values_supported": [
    "goauthentik.io/providers/oauth2/default"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "ak_proxy",
    "profile",
    "offline_access",
    "goauthentik.io/api"
  ],
  "request_parameter_supported": false,
  "claims_supported": [
    "sub",
    "iss",
    "aud",
    "exp",
    "iat",
    "auth_time",
    "acr",
    "amr",
    "nonce",
    "sid",
    "ak_proxy",
    "email",
    "email_verified",
    "name",
    "given_name",
    "preferred_username",
    "nickname",
    "groups"
  ],
  "claims_parameter_supported": false,
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}`

**Comment by stonith404** [comment]
Is `https://authentik` accessible from the Pingvin Share container? You can test this with
```
docker compose exec pingvin-share curl https://authentik
```

**Comment by tinytempmouse** [comment]
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by tinytempmouse** [comment]
I've mounted the cert for my self signed SSL but still get the same result

**Comment by stonith404** [comment]
I can't really help you with that one as I don't have experience with self signed SSL certificates. But the issue seems not caused by Pingvin Share but with your SSL certificate.

**Comment by tinytempmouse** [comment]
The issue is not the self signed cert as it work with all my other containers, its getting pingvin to accept it as a trusted ca that's the issue. You wouldn't have any tips?

**Comment by stonith404** [comment]
Did you need to configure your other containers to accept your CA? If so, how did you accomplish this?

**Comment by tinytempmouse** [comment]
Right found the solution, please if you could append this fix in the pingvin oauth documentation for others to find if needed: 
Add "NODE_EXTRA_CA_CERTS=/etc/ssl/certs/cert.pem"
 environment variable to your docker compose file in
