### ISSUE TITLE
🚀 Feature: Default file sorting

### ISSUE THREAD

**Issue by balonchiks** [stonith404/pingvin-share#542]
### 🔖 Feature description

Hey, thanks for your work first of all!

I have tried searching the issues here and could not find what i am looking for. Would be happy to be wrong, if someone points on how to do it!

It would be awesome to see the default sorting option. Example: when i upload 10 files names picture_x.jpg where x is a number from 1 to 10, by default the files will be sorted by their upload time, which in all cases (at least for me!) end up with a list that looks like this:

```
picture_2.jpg
picture_6.jpg
picture_3.jpg
picture_1.jpg
picture_9.jpg
```

etc etc etc...

I do know that I can click on the title and sort the list alphabetically, but most of the people i share links with - do not know it.

So ideally i'd love to see the _default sorting_ option iof i may call it that, which would show a list sorted alphabetically to the client despite the file upload time. In other words, no matter how and in what order the files are uploaded, always show them like that:

```
picture_1.jpg
picture_2.jpg
picture_3.jpg
picture_4.jpg
picture_5.jpg
```

### 🎤 Pitch

imho it adds ease of use for the end clients that i share files with, especially if the files are photos which have clear numeration

**Comment by stonith404** [comment]
That's a good idea. I have implemented it, and it will be included in the upcoming release. I won't create a release only for this feature as this is a small change.
