### ISSUE TITLE
0.29.0: Unable to run container as non-privileged user

### ISSUE THREAD

**Issue by marvinruder** [stonith404/pingvin-share#549]
### 👟 Reproduction steps

When I try to run the container as the user [node (1000)](https://github.com/nodejs/docker-node/blob/844b019f6d0df6d09e91c99fe90808a99bac6743/Dockerfile-alpine.template#L6) as a security precaution recommended e.g. [here](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-2-set-a-user)

### 👍 Expected behavior

It should start the service normally

### 👎 Actual Behavior

It actually fails to start Caddy, as the non-privileged user is not allowed to create the file `caddy.log` in the directory `/opt/app` owned by `root`:

```
/bin/sh: can't create caddy.log: Permission denied
```

### 🌐 Browser

N/A

**Comment by marvinruder** [comment]
Possible mitigations include changing the user to `node` in the Dockerfile for everyone or writing to a file in a directory like `/var/log/caddy/caddy.log` so I can mount the directory `/var/log/caddy` with adequate permissions.

**Comment by stonith404** [comment]
Thanks for your report I've pushed a new image to the `latest` tag as a quick fix. Do you build a custom image so that you can run the container as a non-root user?

**Comment by marvinruder** [comment]
Yes, it works with the latest image and prints the Caddy output to `stdout` (by the way, among those is a warning that some `X-Forwarded-` headers are declared unneccessarily, so they can probably be removed from the `Caddyfile`). Currently I use the image as-is, and it worked before by just setting `user: 1000:1000`.
