### ISSUE TITLE
🐛 Bug Report: Discord Login

### ISSUE THREAD

**Issue by COMPLEXWASTAKEN** [stonith404/pingvin-share#550]
### 👟 Reproduction steps

have discord auth enabled and you try to login with discord first it opens the url into https://domain.com/auth/domain.com/api/oauth/auth/discord and after you put that normal url into the browser to try the auth it gives {"redirect_uri": ["Not a well formed URL."]}

### 👍 Expected behavior

first the login button for discord should open it in a page and after you get to discord it should not throw that browser 

### 👎 Actual Behavior

it should allow u to login to discord

### 🌐 Browser

opera gx

**Comment by stonith404** [comment]
Which redirect uri did you specify on the Discord website? Additionally, can you share a screen recording of the bug?

**Comment by COMPLEXWASTAKEN** [comment]
the url for it was https://share.vexhub.tech/auth/api/oauth/callback/discord and the video is 

https://github.com/user-attachments/assets/f076a270-7463-441c-8a69-5d0ebbae53a6

**Comment by stonith404** [comment]
I think the issue is that you've set the app URL to `share.vexhub.tech` instead of `https://share.vexhub.tech` in the admin settings of Pingvin share.

Additionally, you should use `https://share.vexhub.tech/api/oauth/callback/discord` as the callback URL instead of `https://share.vexhub.tech/auth/api/oauth/callback/discord`

**Comment by COMPLEXWASTAKEN** [comment]
alr thanks that worked

**Comment by DrMemoryFish** [comment]
> alr thanks that worked

hey, i heard that you got it all sorted.
I'm not really understanding how to set up discord oauth all up from a fresh start, i followed [this](https://github.com/stonith404/pingvin-share/blob/main/docs/oauth2-guide.md) guide, but I'm not really understanding it. could you please help me by providing detailed instructions. 

I've already got my domain name, its just the discord stuff that i don't understand, and how to link it to this application or whatever. 

thanks
