### ISSUE TITLE
🚀 Feature: Disable Email Registration all together

### ISSUE THREAD

**Issue by TadeSF** [stonith404/pingvin-share#553]
### 🔖 Feature description

As an administrator, I want to be able to disable not only certain openID connect clients but also the email registration itself, so that registration and sign-in is only possible via OAuth2.

### 🎤 Pitch

In our non-profit organization, we have a SSO structure that we try to use wherever we can. Especially, we try to forbid our members to sign in with their own mail addresses but instead try to force them to use the SSO. Therefore it would be great to disable the registration by mail all together and only allow registrations via the configured OAuth2/OpenID connect options to force our users keeping that good habit across our platforms.

**Comment by marvinruder** [comment]
I believe this is already achievable by setting "Share -- Allow registration" to `false`, "Social Login -- Allow registration" to `true` and "Social Login -- Disable password login" to `true`. This is what I use in my setup which appears to fulfill your requirements.

**Comment by TadeSF** [comment]
Thanks for the hint! Unfortunately I did run the exact previous version of the one where this got added, sorry for not updating first!
