### ISSUE TITLE
🐛 Bug Report: Get Started Button on Home Page not working when Sign-Up is disabled

### ISSUE THREAD

**Issue by TadeSF** [stonith404/pingvin-share#557]
### 👟 Reproduction steps

Just a minor bug. Disable the "Allow registration" option in the configurations and go back (while not logged in) to the starting page. Then click on the Button "Get Started"

### 👍 Expected behavior

It should lead to the sign-in page, since sign-ups are disabled

### 👎 Actual Behavior

Nothing happens, because the sign-up page is disabled

### 🌐 Browser

Arc (based on Chromium), Safari

**Comment by stonith404** [comment]
This will be fixed in the next release.
