### ISSUE TITLE
🚀 Feature: Delete share once `Maximal views` are reached

### ISSUE THREAD

**Issue by mztiq** [stonith404/pingvin-share#56]
### 🔖 Feature description

Not sure if it's a bug or a feature request but I just noticed that shares do not get deleted if the `Maximal views` are reached.
Since nobody can access the share after the `Maximal views` are reached anyways it would be great if the share and it's files then get removed or at least make it an option.  

### 🎤 Pitch

Shares with `Maximal views` reached can't be accessed no more, IMO there is no point in keeping the share and it's files.

**Comment by stonith404** [comment]
Expired shares should get deleted every hour. Can you check if your share is deleted after an hour?

**Comment by stonith404** [comment]
This is not possible, here is an example:
You create a share with a visitor limit of 1. When I open your link the view count gets increased and the limit is exceeded. When I now want to download the files, the share would already be deleted.

I hope you understand what I mean.

**Comment by mztiq** [comment]
I get it, thanks for the clarification.  
Sorry for the unqualified question but is there a way to restrict shares by downloads and not views? I mean something like a feature called `Maximal downloads` so the share gets deleted **after** the download happens?  

This feature is really not **that** important to me I'm asking out of personal interest since it would be nice to have.  
IMHO the restriction by views as it's implemented now comes with the risk of orphaned shares on your disk once the view limit is reached.

**Comment by stonith404** [comment]
@mztiq Questions are always welcome :) The problem is that a share can have multiple files, so it's really difficult to limit the downloads. Maybe you have an idea to solve that? As a workaround you can delete the share manually in the `My Shares` section, but yeah it isn't an elegant solution.

**Comment by mztiq** [comment]
I understand the problem on this feature better now, sadly I've no idea on how to solve this, just wanted to hear your opinion on it.
Thanks again for taking the time.

**Comment by stonith404** [comment]
Is it okay when I close the issue for now? If we find a solution we can reopen it later. 

Unrelated: Btw. thank you so much for your sponsorship! I wanted to thank you with an email but your mail server declines emails

**Comment by mztiq** [comment]
Yes, issue can be closed for now.  

And you're welcome, I appreciate your work and I'm impressed by what you can do, especially considering your age.  
Thanks for pointing out the problem with my mail server, I barely use this E-Mail but it's fixed now :-).
