### ISSUE TITLE
🐛 Bug Report: Missing translation for LDAP "Admin group" field description

### ISSUE THREAD

**Issue by reznakt** [stonith404/pingvin-share#563]
### 👟 Reproduction steps

- Update to `v1.0.0`
- Go to Administration -> LDAP

### 👍 Expected behavior

An appropriate description should be shown for the "Admin group" field.

### 👎 Actual Behavior

A missing key in [`frontend/src/i18n/translations/en_US.ts`](https://github.com/stonith404/pingvin-share/blob/cfcc5cebac0f82c129f6cd546969ca545737fdda/frontend/src/i18n/translations/en-US.ts#L586) causes the  description to be missing and a fallback text is rendered:
![image](https://github.com/user-attachments/assets/ef5f93e0-d689-4df7-b7a1-8686d571e92c)

### 🌐 Browser

Firefox 129

**Comment by stonith404** [comment]
Thanks. This should be fixed.
