### ISSUE TITLE
🐛 Bug Report: Translation for {expires} in Emails 

### ISSUE THREAD

**Issue by ipod86** [stonith404/pingvin-share#575]
### 👟 Reproduction steps

I have just registered with crowdin to add a translation.
Unfortunately I cannot find the corresponding entry.

I would like to translate the values ​​of {expires} that are inserted in an email. These always arrive in English.

Presumably the email does not pick up the system language?

### 👍 Expected behavior

System language of the variables in an email.

### 👎 Actual Behavior

Variables in the mail are always in English.

**Comment by stonith404** [comment]
There is a already an open issue (#351) because of that I'm closing this.
