### ISSUE TITLE
🚀 Feature: Add "Test Email" button to configuration screen

### ISSUE THREAD

**Issue by jl-678** [stonith404/pingvin-share#58]
### 🔖 Feature description

I appreciate how you have added a custom username and password to the email configuration.  It is helpful!  The setup went smoothly, but I am missing a "Send test email" button.  Clicking this would send an email and confirm that the entered email configuration is working and valid.

### 🎤 Pitch

Troubleshooting email issues is frustrating.  While I can force sending an email by creating and deleting a share, it requires more work than needed. A simple button and associated message box would be really helpful.  You click the button and PV tries to send an email and at a minimum it would say "Email sent successfully" or "email failed."

A more advanced approach could provide more status details in the message box based on the response for the email server. I could envision "Message Sent", "Invalid user id", "Invalid password" or stuff like that.

**Comment by stonith404** [comment]
Good idea! The current state of configuration isn't very well and it could get really difficult to add this feature. But I plan to improve the configuration page #60. With the new configuration page I'll definitely implement this.

**Comment by stonith404** [comment]
Added in v0.5.0 :)
