### ISSUE TITLE
🐛 Bug Report: LDAP Auth not working for Active Directory

### ISSUE THREAD

**Issue by regiolis** [stonith404/pingvin-share#582]
### 👟 Reproduction steps

**Server URL:** ldap://domain.local
**Bind DN:** CN=bind,CN=Users,DC=domain,DC=local
**Bind password:** password
**User base:** OU=Accounts,DC=domain,DC=local
**User query:** (sAMAccountName=%username%)
**Admin group:** CN=APP_PINGVIN_ADMINS,CN=User,DC=domain,DC=local

### 👍 Expected behavior

AD login should works.

### 👎 Actual Behavior

It doesn't works when trying to login with samAccountName and password.

Error:Wrong email or password

### 📜 Logs

[Nest] 59  - 08/31/2024, 2:22:40 PM   DEBUG [AuthService] Trying LDAP login for user regiolis

[Nest] 59  - 08/31/2024, 2:22:40 PM     LOG [AuthService] Failed login attempt for user regiolis from IP 172.18.0.1

[Nest] 59  - 08/31/2024, 2:23:18 PM   DEBUG [AuthService] Trying LDAP login for user regiolis

[Nest] 59  - 08/31/2024, 2:23:18 PM     LOG [AuthService] Failed login attempt for user regiolis from IP 172.18.0.1

**Comment by stonith404** [comment]
@WolverinDEV Do you know what could cause this issue?

**Comment by WolverinDEV** [comment]
Hey @regiolis,
Have you tried running the user query manually with an LDAP explorer?  
Running the query manually could help narrow down which of these might be happening. Let me know if you find anything!
  
From experience, silently failing LDAP authentication can typically result from one of the following scenarios:
1. User not found by the query  
For example, a query like `(sAMAccountName=regiolis)` might not return any results.

2. Incorrect password
A user is found, but the password provided doesn't match.

3. Username contains unsupported characters
If the username contains characters outside of [a-zA-Z0-9]+ ([source](https://github.com/stonith404/pingvin-share/blob/main/backend/src/auth/ldap.service.ts#L107)), authentication could fail. This check is in place to prevent injection attacks in the LDAP query, though it could be relaxed to allow characters like . and @. (I might submit a PR for this someday).

4. Multiple user results
Although rare, if your query yields multiple users, only the first one is authenticated against, which could lead to unexpected behaviour.

**Comment by stonith404** [comment]
Thanks, @WolverinDEV. That likely is the issue. I’m not sure I fully understand your question—could you clarify what you mean? Are you suggesting we eliminate the username attribute altogether?

**Comment by WolverinDEV** [comment]
I mean [this](https://github.com/stonith404/pingvin-share/blob/main/frontend/src/services/auth.service.ts#L6).  
Is there any particular reason you do not pass it as `emailOrUsername` to the server?

**Comment by stonith404** [comment]
@WolverinDEV Not really, I just thought that it is cleaner to handle it in the frontend. But does it make a difference for LDAP if we handle this in the frontend because it would need a different query nevertheless or I'm wrong? I thought about something like this or would you recommend some other solution?

```ts
public async authenticateUser(usernameOrEmail: string, password: string): Promise<LdapAuthenticateResult | null> {
    const usernamePattern = /^[a-zA-Z0-9]+$/;
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    // Determine whether the input is a valid email or username to prevent injection 
    // (not sure if this is necessary)
    const isEmail = emailPattern.test(usernameOrEmail);
    const isUsername = usernamePattern.test(usernameOrEmail);

    if (!isEmail && !isUsername) {
        return null;
    }

    // Determine the appropriate search query based on input type
    const searchBase = this.serviceConfig.get("ldap.searchBase");
    let searchQuery: string;

    if (isEmail) {
        searchQuery = this.serviceConfig.get("ldap.searchQueryForEmail")
            .replaceAll("%email%", usernameOrEmail);
    } else {
        searchQuery = this.serviceConfig.get("ldap.searchQueryForUsername")
            .replaceAll("%username%", usernameOrEmail);
    }
    ...
}
```

**Comment by regiolis** [comment]
> Hey @regiolis,
> Have you tried running the user query manually with an LDAP explorer?  
> Running the query manually could help narrow down which of these might be happening. Let me know if you find anything!
>   
> From experience, silently failing LDAP authentication can typically result from one of the following scenarios:
> 1. User not found by the query  
> For example, a query like `(sAMAccountName=regiolis)` might not return any results.
> 
> 2. Incorrect password
> A user is found, but the password provided doesn't match.
> 
> 3. Username contains unsupported characters
> If the username contains characters outside of [a-zA-Z0-9]+ ([source](https://github.com/stonith404/pingvin-share/blob/main/backend/src/auth/ldap.service.ts#L107)), authentication could fail. This check is in place to prevent injection attacks in the LDAP query, though it could be relaxed to allow characters like . and @. (I might submit a PR for this someday).
> 
> 4. Multiple user results
> Although rare, if your query yields multiple users, only the first one is authenticated against, which could lead to unexpected behaviour.
>   
> Edit:  
> PS: Actually there is one bug when it comes to LDAP and a login with an e-mail address.  
> As the authentication dto differentiates between an username and an email, login by an emails does not work. The LDAP authentication expects a username ([source](https://github.com/stonith404/pingvin-share/blob/main/backend/src/auth/auth.service.ts#L87)) and will fail if only an email is provided.  
> @stonith404 do I may ask, why you differentiate so explicitly between them?

Hey,

Yeah but still doesn't works...

**Comment by WolverinDEV** [comment]
Have you tried your query manually and verified, that the user can be found with that query?

**Comment by regiolis** [comment]
> Have you tried your query manually and verified, that the user can be found with that query?

Yeah but even with **(sAMAccountName=regiolis)** it still not working...
I would like to add my others webapps using LDAP Auth are working well so it's not an AD issue...

**Comment by WolverinDEV** [comment]
By any chance, does your user contains any special characters (non ascii characters).  
E.g. äöü etc?

**Comment by WolverinDEV** [comment]
> new issue
> Edit
> Hide
> Delete

Any updates on this?

**Comment by dnielso5** [comment]
So im having an issue as well. i can use LDAPSearch and connect to the LDAP server from the pingvin server.

Here is my setup:

```
Server URL: Server IP address

Bind DN: My admin account name (also tried CN=Admin_Username,OU=Administrators,OU="All Users",DC=domain,DC=name,DC=com)

Bind Password: My password

User base: OU=Users,OU=All Users,DC=domain,DC=name,DC=com

User Query: (&(objectClass=user)(sAMAccountName=%username%)(memberof=CN=FileSharing,OU=Users,OU="All Users",DC=domain,DC=name,DC=com))

I have also tried: %username% and (sAMAccountName=%username%)

Admin Group: FileSharingAdmins
```


I get this error when trying to log in:

`[Nest] 43  - 09/23/2024, 10:43:09 PM     LOG [AuthService] Failed login attempt for user Username from IP My_IP`

**Comment by dnielso5** [comment]
This is where im stuck at. This is my ldapsearch:

`ldapsearch -x -b "OU=Users,OU=All Users,dc=domain,dc=domain,dc=domain" -H ldap://ServerIP -D "cn=My_admin,ou=administrators,ou=all users,dc=domain,dc=domain,dc=domain" -w Password '(&(objectClass=user)(sAMAccountName=My_username)(memberof=CN=FileSharing,OU=Groups,OU=All Users,DC=dc=domain,dc=domain,dc=domain))'`

which shows all the info of "My_Username"

This is my LDAP config page:

![{C3E8FC47-1C4A-4D7F-8918-C3083527D17E}](https://github.com/user-attachments/assets/e043df71-330b-4135-9a21-3880e2154450)

My user account can not log in.

**Comment by WolverinDEV** [comment]
Hey,  
well that's odd.  
I've created a PR to improve the current LDAP implementation and add more verbose information for troubleshooting:  
https://github.com/stonith404/pingvin-share/pull/615
  
Maybe you can try out that build and get more insights with which reason the login fails.  
It may also fixes the issue, idk. As of now, as you ensured that the query and all other parameters are correct, I do not have an idea why it's not working.

**Comment by regiolis** [comment]
> Hey, well that's odd. I've created a PR to improve the current LDAP implementation and add more verbose information for troubleshooting: #615
> 
> Maybe you can try out that build and get more insights with which reason the login fails. It may also fixes the issue, idk. As of now, as you ensured that the query and all other parameters are correct, I do not have an idea why it's not working.

I'll try that, but sorry, how to build the container from your PR ?

**Comment by stonith404** [comment]
You can use the image `stonith404/pingvin-share:dev-pr-615`. It should be available in a few minutes.

**Comment by regiolis** [comment]
> You can use the image `stonith404/pingvin-share:dev-pr-615`. It should be available in a few minutes.

Thank you !!! You can push the changes to release ! It's working now !!!

**Comment by regiolis** [comment]
> You can use the image `stonith404/pingvin-share:dev-pr-615`. It should be available in a few minutes.

However the "Admin" LDAP group feature doesn't works. Even if I set the full DN of the group.

**Comment by dnielso5** [comment]
> Hey, well that's odd. I've created a PR to improve the current LDAP implementation and add more verbose information for troubleshooting: #615
> 
> Maybe you can try out that build and get more insights with which reason the login fails. It may also fixes the issue, idk. As of now, as you ensured that the query and all other parameters are correct, I do not have an idea why it's not working.

> You can use the image `stonith404/pingvin-share:dev-pr-615`. It should be available in a few minutes.

@stonith404 @WolverinDEV Thank you, whatever the change was is now letting my user log in.

**Comment by dnielso5** [comment]
@stonith404 this is a bit off topic but when running the dev-pr-615 it was allowing me to attempt to upload files while not being signed in which is an option that i had disabled. My understanding is it should push me back to the "login screen" instead of showing me the "upload" page.

It will not let you actually create a link giving a "forbidden resource error". Now i know this is not supposed to be a production release so it probably doesn't matter but i thought i should point it out.

![{18C7449E-F0A0-4723-A557-123D5A3EC4BB}](https://github.com/user-attachments/assets/a66e2da0-851b-4dcb-81c5-33fcc0eb4b76)

![{9FCD0856-58A1-4697-8E9F-4B342B5ABF97}](https://github.com/user-attachments/assets/3dbf3538-8db4-4f2e-b3f2-e5096709771d)

**Comment by Esperenza84** [comment]
I used the dev-pr-615 image and LDAP works great!
However I wanted to use instead of sAMAccoutName I used “mail” and when displaying my users it's the user ID that appears.
I have no idea if it's possible to fix it, so I'm just sharing the information.

`User query: (mail=%username%)`

![Capture d'écran 2024-09-27 122624](https://github.com/user-attachments/assets/ebff3b02-c193-4da0-9351-60cca820398e)

**Comment by WolverinDEV** [comment]
> > You can use the image `stonith404/pingvin-share:dev-pr-615`. It should be available in a few minutes.
> 
> Thank you !!! You can push the changes to release ! It's working now !!!

Great to hear!



> > You can use the image `stonith404/pingvin-share:dev-pr-615`. It should be available in a few minutes.
> 
> However the "Admin" LDAP group feature doesn't works. Even if I set the full DN of the group.

You have to specify the full group DN as it will be contained in the memberOf attribute of the user :)



> I used the dev-pr-615 image and LDAP works great! However I wanted to use instead of sAMAccoutName I used “mail” and when displaying my users it's the user ID that appears. I have no idea if it's possible to fix it, so I'm just sharing the information.
> 
> `User query: (mail=%username%)`
> 
> ![Capture d'écran 2024-09-27 122624](https://private-user-images.githubusercontent.com/114189853/371495436-ebff3b02-c193-4da0-9351-60cca820398e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDA0MDEsIm5iZiI6MTcyNzQ0MDEwMSwicGF0aCI6Ii8xMTQxODk4NTMvMzcxNDk1NDM2LWViZmYzYjAyLWMxOTMtNGRhMC05MzUxLTYwY2NhODIwMzk4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMjI4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmVkZjBiMmIwMmFhYzE5YzZjNDRjZDZjYzRlNjY0MzJkNWI1OWM1NjY0NzQ2MzdiYjc0NmFiNTRiYzlmYzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J9H2p-vl8q5EiSaH4lMm3x9PkU7tJ_frp97BoaH-o_U)

Yes, this is intentional as pingvin has no idea, what a proper username for this user would look like.  
I've created a new issue to discuss this topic in more detail: #620 620

**Comment by regiolis** [comment]
> > > You can use the image `stonith404/pingvin-share:dev-pr-615`. It should be available in a few minutes.
> > 
> > 
> > Thank you !!! You can push the changes to release ! It's working now !!!
> 
> Great to hear!
> 
> > > You can use the image `stonith404/pingvin-share:dev-pr-615`. It should be available in a few minutes.
> > 
> > 
> > However the "Admin" LDAP group feature doesn't works. Even if I set the full DN of the group.
> 
> You have to specify the full group DN as it will be contained in the memberOf attribute of the user :)
> 
> > I used the dev-pr-615 image and LDAP works great! However I wanted to use instead of sAMAccoutName I used “mail” and when displaying my users it's the user ID that appears. I have no idea if it's possible to fix it, so I'm just sharing the information.
> > `User query: (mail=%username%)`
> > ![Capture d'écran 2024-09-27 122624](https://private-user-images.githubusercontent.com/114189853/371495436-ebff3b02-c193-4da0-9351-60cca820398e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDA0MDEsIm5iZiI6MTcyNzQ0MDEwMSwicGF0aCI6Ii8xMTQxODk4NTMvMzcxNDk1NDM2LWViZmYzYjAyLWMxOTMtNGRhMC05MzUxLTYwY2NhODIwMzk4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMjI4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmVkZjBiMmIwMmFhYzE5YzZjNDRjZDZjYzRlNjY0MzJkNWI1OWM1NjY0NzQ2MzdiYjc0NmFiNTRiYzlmYzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J9H2p-vl8q5EiSaH4lMm3x9PkU7tJ_frp97BoaH-o_U)
> 
> Yes, this is intentional as pingvin has no idea, what a proper username for this user would look like. I've created a new issue to discuss this topic in more detail: #620
> 
> I think this issue can be closed now :)

Here's my conf, as you can see I've set up the right group DN but Pingvin is still unable to check if the user is member of this group...

![image](https://github.com/user-attachments/assets/f969c5b3-c67f-4561-8617-494246a33206)
