### ISSUE TITLE
🚀 Feature: LDAP users by AD group instead of OU

### ISSUE THREAD

**Issue by dnielso5** [stonith404/pingvin-share#586]
### 🔖 Feature description

Hello, unless I'm missing something you are unable to select and AD group that has users in it, and instead need to select an OU, this would add all users in our AD. is it possible to select a group like is required for admins.

### 🎤 Pitch

we do not want everyone in our AD having access and would like to only select a group of users.

**Comment by stonith404** [comment]
@WolverinDEV

**Comment by WolverinDEV** [comment]
Hey,  
you can just easily do this by adjusting the search query to only find users which are a member of a certain group :)

**Comment by stonith404** [comment]
Thanks @WolverinDEV. @dnielso5 feel free to reopen the issue if this doesn't work for you.

**Comment by dnielso5** [comment]
works for me, though not sure what the query would be for a specific group. ill have to look into it.

**Comment by WolverinDEV** [comment]
Just a generic example:  
```
(&(objectClass=user)(sAMAccountName=yourUserName)(memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com))
```
(https://stackoverflow.com/a/1032426)

**Comment by dnielso5** [comment]
> Just a generic example:
> 
> ```
> (&(objectClass=user)(sAMAccountName=yourUserName)(memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com))
> ```
> 
> (https://stackoverflow.com/a/1032426)

Thank you, ill try this out at work on Monday.
