### ISSUE TITLE
🚀 Feature: Add 2 Factor Authentication

### ISSUE THREAD

**Issue by jl-678** [stonith404/pingvin-share#59]
### 🔖 Feature description

Given that files are being shared publicly, security is paramount.  It would be great if you added 2FA as an option.  Ideally, this would be configured at a user level.  You could even have a setting to define the default authentication behavior for newly registered users. (e.g. 2FA or non-2FA).

### 🎤 Pitch

It is all about added security and protection.  Having it as an option would keep the flexibility of not using for those who do not want to with the option to enable it for those users who do.

**Comment by stonith404** [comment]
Thanks for your feature request. There is already an open issue #28 and an open PR #55. This feature will be released soon. For the next time, please be sure that there isn't already an open issue before creating one:)
