### ISSUE TITLE
🐛 Bug Report: SMTP requires username/password even if the server does not require it

### ISSUE THREAD

**Issue by alexlehm** [stonith404/pingvin-share#592]
### 👟 Reproduction steps

When I configure a SMTP that does not require authentication, e.g. when running on the same host the web server is running on, using SMTP AUTH is often not required and it would work with leaving the fields empty

### 👍 Expected behavior

The SMTP client should attempt to send the mail without AUTH PLAIN when the username field is empty

### 👎 Actual Behavior

Currently leaving the username/password fields empty leads to an error `Missing credentials for "PLAIN"`

**Comment by stonith404** [comment]
I should have fixed this, but as I don't have a SMTP server without authentication I can't test it. Could you test the `stonith404/pingvin-share:development` image and let me know if it works?

**Comment by alexlehm** [comment]
Yes, it works with the development version

**Comment by stonith404** [comment]
Thanks. This is now available in `v1.1.0`.

**Comment by alexlehm** [comment]
Thank you, that works as expected now
