### ISSUE TITLE
🚀 Feature: Auto-Login with OpenID

### ISSUE THREAD

**Issue by webzit** [stonith404/pingvin-share#595]
### 🔖 Feature description

Suggest implementing an environment variable for auto-login when only one OpenID Provider is available, eliminating the need for the current extra click.

### 🎤 Pitch

Currently, users are required to click the "OpenID" button to log in using an OpenID Provider, which adds an extra step to the login process. This extra click is unnecessary when there are no alternative login methods available.

To streamline the login experience for users who only have one OpenID Provider, I propose introducing an environment variable to enable auto-login. This would eliminate the need for users to click the OpenID button, thereby speeding up the login process.

**Comment by stonith404** [comment]
This was added in `v1.1.0`. If only one OAuth provider is present and password login is disabled, the user will get redirected automatically.
