### ISSUE TITLE
Registration possible even if ALLOW_REGISTRATION=false is set

### ISSUE THREAD

**Issue by asisdrico** [stonith404/pingvin-share#6]
Hi,

even with 
```
ALLOW_REGISTRATION=false
```
in the .env file,  the "Get Started" button on the homepage redirects to `/auth/signUp`  and multiple users can register.

Also I asked myself how to add a user, if registrations are not possible. Is there a cli program, that allows to add a user ?   

Also, even when not showing the Homepage the `/auth/signUp` link is reachable and users can register. 

Probably a wrong ENV variable --> process.env.NEXT_PUBLIC_DISABLE_REGISTRATION in signUp.tsx, should be !ALLOW_REGISTRATION

Apart from that, great work... ;)

**Comment by stonith404** [comment]
Thanks for your issue:) There was actually a wrong configuration in the frontend and backend. This should now be fixed.
