### ISSUE TITLE
🚀 Feature: Indicate that the page is loading after a click

### ISSUE THREAD

**Issue by alexlehm** [stonith404/pingvin-share#607]
### 🔖 Feature description

When clicking on a link like the my shares link, the page is loaded in the background, I assume that is standard by Next.js and then displayed when the first request is finished and is only displayed then. This is fine but it makes the page seem sluggish and I have clicked a few times on some menus as I thought it was not registering the mouse click.

### 🎤 Pitch

I would prefer the browser or  the mouse to indicate that the browser is doing something in the back which would make the app appear faster even though it does not change the processing speed at all
e.g. when I load my "my shares" page, it currently takes about 7 seconds for the shares.js page
![image](https://github.com/user-attachments/assets/43dc75c3-dc23-4af0-b299-dd6b3982a0a1)

**Comment by stonith404** [comment]
Are you running the Pingvin Share frontend in development mode? Can you share the command that you've used to start the frontend?

**Comment by alexlehm** [comment]
I believe its prod mode, I run the npm stuff directly without docker

````
npm install
npm run build
API_URL=http://localhost:8081
pm2 start --name="pingvin-share-frontend" .next/standalone/server.js
````

the backend server is running on port 8081
