### ISSUE TITLE
🐛 Bug Report: when the notification email is invalid nothing is shown when the section is closed

### ISSUE THREAD

**Issue by alexlehm** [stonith404/pingvin-share#608]
### 👟 Reproduction steps

create an upload and enter a name without domain in the Email Recipients area, close the section again and click Share button
the page does not display anything and the button has no effect

### 👍 Expected behavior

The page should show invalid email address like it does when the section is open, like this:

![image](https://github.com/user-attachments/assets/a2ffc6b3-a86b-4133-92ff-d8b774843df9)

### 👎 Actual Behavior

The button does not do anything and the user is not shown an error

![image](https://github.com/user-attachments/assets/16388641-7b78-4ce4-81ee-31ddbad7c668)

**Comment by stonith404** [comment]
Fixed in `v1.2.1` although the share recipient component needs a rework because it will ignore the recipient if it isn't added to the list which confuses users.
