### ISSUE TITLE
🐛 Bug report: Database resets after upgrade

### ISSUE THREAD

**Issue by Ju17091** [stonith404/pingvin-share#61]
### 👟 Reproduction steps

I don't know if anyone else has this problem and if anyone can help me find the problem. I have installed Pingvin on my Synology. The Docker containers are automatically updated via Watchtower. Every time Watchtower Pingvin I lose all my settings in Pingvin.
App url and accounts are all gone then.
And I have to set up everything again

### 👍 Expected behavior

I don't know if it's my synology or the settings. All other containers are updated normally and do not lose their settings

### 👎 Actual Behavior

![BF39E363-C82E-4C0F-9359-5B7DFCD24068](https://user-images.githubusercontent.com/119397275/209083623-b7bf6fcb-b062-483c-811a-bf64d8026b1a.jpeg)

### 🌐 Browser

Firefox, Safari

**Comment by stonith404** [comment]
This must be an issue with the volume. Can you share your docker compose file?

**Comment by stonith404** [comment]
@Ju17091  Can you check if the volume exists? Marius mentioned this command in his post:
```
docker run -d --name=Pingvin-Share \
-p 6090:3000 \
-v /volume1/docker/pingvin:/opt/app/backend/data \
--restart always \
stonith404/pingvin-share
```

I'm not sure if you're familiar with Docker, but on line 3 you can see the volume flag. This mounts the folder `/opt/app/backend/data` to your local directory `/volume1/docker/pingvin`. You probably changed the path but can you check, if the mounted folder isn't empty?

**Comment by Ju17091** [comment]
@stonith404 Okay, I have found the error 🙈
The folder was empty for me.
I have now removed everything again and made a new one. Now the folder is no longer empty. Sorry for the circumstances 🙈
