### ISSUE TITLE
🐛 Bug Report: Google OAuth2 users have whitespace in usernames, preventing promotion of a Google user to Admin

### ISSUE THREAD

**Issue by XStylus** [stonith404/pingvin-share#611]
### 👟 Reproduction steps

This issue assumes a normal pingvin instance with Google OAuth2 correctly configured in the Social Login admin settings page, and with "Allow Registration" enabled.

1 - A new Google user logs in via Google login. Pingvin creates a username them under their name (For example, "John Doe")
2 - Via an admin account, go to pingvin "User Management".
3 - Select the new user "John Doe" and go to the Update User page. Enable "Admin privileges", and click Save.
4 - An error will be presented: "Username can only contain letters, numbers, dots and underscores"

### 👍 Expected behavior

Expected behavior could be in one of two ways:

Option 1 - Pingvin could permit whitespaces in usernames.
Option 2 - If Option 1 is not feasible, then when pingvin creates a new Google user any whitespaces should be replaced with _. For example, "John_Doe" instead of "John Doe"

### 👎 Actual Behavior

Described above.

**Comment by stonith404** [comment]
Thanks for the report. This should be fixed in the latest version. The users that have been created already have to change the username manually though.
