### ISSUE TITLE
🐛 Bug Report: OpenID redirect button directs to container internal port

### ISSUE THREAD

**Issue by sprjr** [stonith404/pingvin-share#612]
### 👟 Reproduction steps

I have assigned a non-standard external port to my Pingvin container that I am running through docker. After configuring OpenID settings and ensuring that OpenID is enabled, when I attempt to click on the "OpenID" button to authenticate on the login screen, it incorrectly redirects.

### 👍 Expected behavior

Direct me to the correct "Redirect URI" for my public subdomain.

### 👎 Actual Behavior

It redirects to "localhost:3000" instead of the re-assigned public address (again, using a different port). Manually entering the "correct" address (a public subdomain) correctly redirects me to my OIDC provider, but it fails as it is unable to reach the redirect URI as it doesn't exist in a public sense.

**Comment by stonith404** [comment]
Did you set the app url in the admin settings (`/admin/config/general`)?

**Comment by sprjr** [comment]
Thanks, that was it. I had recently migrated from another device and didn't move my administrative settings over.
