### ISSUE TITLE
🐛 Bug Report: Upload Failed, crashes system.

### ISSUE THREAD

**Issue by kbkozlev** [stonith404/pingvin-share#617]
### 👟 Reproduction steps

To reproduce the issue, try to upload a file that will overflow the disk size.

For example, for a test, I set up a container with 20GB of storage. Inside pingvin I set up that the max upload size is 50 GB and I tried to upload a file larger than 20 GB. The result was that pingvin crashed, but before crashing it constantly tried to re-upload the file again and again,

![2024-09-25_22-47](https://github.com/user-attachments/assets/578789ef-7b83-4ea2-9359-75b8c214427f)

Why is this important: → If I have pingivn running on a 100GB disk for example, but I have multiple people using it can happen that one of the uploads will go above the max capacity of the disk. This will crash the system.

### 👍 Expected behavior

Once the maximum capacity has been reached, or even for any other reason, the upload failed. Pingvin should try to reupload 2-3 times and then stop in such a way the failed files could be removed as well as all other that do not "fit" and the share can be created.

### 👎 Actual Behavior

The system keeps on trying and finally crashes. The share is not actually created and is not seen in my shares to be able to be removed, but could be found on the disk and takes on space.

**Comment by stonith404** [comment]
Does the container actually crash or are you just not able to upload files anymore?

**Comment by kbkozlev** [comment]
> Does the container actually crash or are you just not able to upload files anymore?

It crashed, it actually crashed the whole proxmox server and I had to restart.

**Comment by stonith404** [comment]
Ok thanks. There is an open pull request #619 that will fix the issue by returning an error if not enough space is left. This should be fixed as soon as the PR gets merged.
