### ISSUE TITLE
🐛 Bug Report: LDAP Password Reset

### ISSUE THREAD

**Issue by regiolis** [stonith404/pingvin-share#626]
### 👟 Reproduction steps

Pingvin let me reset the password for a LDAP account.

### 👍 Expected behavior

It shouldn't.

### 👎 Actual Behavior

It let me do it

**Comment by dnielso5** [comment]
i have a basic understanding of LDAP but my guess is that the account you are using to search your LDAP is also an account with admin permissions. by giving pingvin the username/password with admin access it has write access and can do a password change. i would say that by creating a "service account" in your LDAP with only read access the password reset would fail.

**Comment by stonith404** [comment]
A LDAP user now cannot reset its password anymore.
