### ISSUE TITLE
🐛 Bug Report: username and password is not trimmed when checking

### ISSUE THREAD

**Issue by alexlehm** [stonith404/pingvin-share#629]
### 👟 Reproduction steps

paste a password or username with a space at the end, this happens in copy-paste in Windows for example

### 👍 Expected behavior

the strings should remove spaces at start or end before the account is checked

### 👎 Actual Behavior

the login fails because the username is compared with the space

**Comment by stonith404** [comment]
Fixed in `v1.2.1`
