### ISSUE TITLE
🐛 Bug Report: Can NOT change to dark mode - NO place to set that up.

### ISSUE THREAD

**Issue by aryehassbian** [stonith404/pingvin-share#63]
### 👟 Reproduction steps

Dark mode is not available and it runs only with light mode.

### 👍 Expected behavior

It should give a way to chose dark or light mode from the user drop down menu that way it can be done with one click.

### 👎 Actual Behavior

stay light mode no way to change to dark mode.

### 🌐 Browser

chrome

**Comment by stonith404** [comment]
Currently Pingvin Share uses the system theme. Would you recommend to add an option to manually change the theme?

**Comment by stonith404** [comment]
Ability to change color theme manually added ef21bac59b11dc68649ab3b195dcb89d2b192e7b

**Comment by aryehassbian** [comment]
Yes, That would be great.

**Comment by stonith404** [comment]
Added in v0.5.0 :)
