### ISSUE TITLE
🐛 Bug Report: when defining reverse shares, the error message about not a number for usage count is malformed

### ISSUE THREAD

**Issue by alexlehm** [stonith404/pingvin-share#632]
### 👟 Reproduction steps

When I define a reverse share, when removing the counter number, the resulting error message is malformed and bit confusing

### 👍 Expected behavior

The error message should say, the field must to contain a number between 1 and 1000

### 👎 Actual Behavior

the error message is this:

![image](https://github.com/user-attachments/assets/06eea763-879a-4a99-927b-b2a9d3a754ec)

this seems to be generated by adding strings together without spaces, not sure where this comes from, I didn't find the string in the messages list

**Comment by stonith404** [comment]
Fixed in `v1.2.1`.
