### ISSUE TITLE
🚀 Feature: Allow LDAP fields to be configured for use in outgoing email

### ISSUE THREAD

**Issue by dnielso5** [stonith404/pingvin-share#633]
### 🔖 Feature description

hello @WolverinDEV and @stonith404, now that LDAP has been enabled would it be possible to map LDAP fields for email use?

Seeing as the "username" gets pulled and mapped to the {creator} variable it would be nice to be able to specify another attribute to pull in as well for the users real name. in our environment it would be the "cn" or "name" and map that to a new variable {name}

Secondly being able to add an {email} variable as we are using a generic email "no.reply@domain.com" to send out the emails. it would be nice to add the users email to the message who created the link to the bottom of the email.

### 🎤 Pitch

When we use the email option we are only able to use the {creator} variable which in our case is a unique set of letters and numbers. this means the email looks like:

"Hey!

sp003422 shared some files with you"

It would look much cleaner/less confusing to see something like this:

"Hey!

john smith shared some files with you"

**Comment by dnielso5** [comment]
@WolverinDEV hate to bug you on this, but any chance this is something that can be done?

**Comment by WolverinDEV** [comment]
Hey ho,
sorry I must've missed the notification last time.

I fully support the idea behind this feature request, but I think it might not be an easy implementation. Since the LDAP user entry is only processed at login, these variables would need to be stored along with the general user data within Pingvin Share.

A few things that come to mind:
1. What would these variables look like if the user isn’t connected to an LDAP account?
2. Sending from different "from" addresses might require authentication for each address on the SMTP server.

**Comment by dnielso5** [comment]
1) i would think it could be something the user could modify in their profile, but I'm not a programmer so who knows

2) we don't need to send with a different email address i was hoping to be able to add a line such as:

"This came from a non monitored email account, please send questions to [share creator email address variable]"

which would look like this to the user:

"This came from a non monitored email account, please send questions to user.1@domain.com"

**Comment by dnielso5** [comment]
@WolverinDEV I hate to be a thorn, but any thoughts on this? Its the only thing we need added to make this fully functional.

**Comment by WolverinDEV** [comment]
> email address is already stored in the user profile

Well, that's right and is already done as I just noticed https://github.com/stonith404/pingvin-share/blob/main/backend/src/user/user.service.ts#L192 😆 

> I was hoping to be able to add a line such as:

As I understood now, adding the email as a message variable is way different then using it as a from address. Variable support seems beneficial and way more convenient to me.  
This can be easily done by adding a corresponding line [here](https://github.com/stonith404/pingvin-share/blob/main/backend/src/email/email.service.ts#L73) and [here](https://github.com/stonith404/pingvin-share/blob/main/backend/src/share/share.service.ts#L153).

This should be fairly easy to implement: @stonith404 may can add them on the fly as I'm quite busy rn :)

**Comment by stonith404** [comment]
I've added the "creatorEmail" in `v1.4.0`.
