### ISSUE TITLE
🐛 Bug Report: Clicking on done in the reverse share upload will have unexpected results

### ISSUE THREAD

**Issue by Juliaria08** [stonith404/pingvin-share#645]
### 👟 Reproduction steps

When I opened my reverse share link, uploaded something, and clicked "Done" on the `Share ready` section, it redirected me to the login screen, (when not logged in), and would've made it use the normal share process when logged in.

### 👍 Expected behavior

It should either inform the user they can't do more uploads, or redirect them to the landing page, or redirect them to the same page we're on so they can do more uploads if the link supports more uploads.

### 👎 Actual Behavior

It redirected me to the login screen, because it tried accessing `<pingvin-share>/_next/data/<snip>/upload.json`, and I got a `x-nextjs-matched-path`:`/upload` on the response (when logged in), and `x-nextjs-redirect`:`/auth/signIn?redirect=%2Fupload` when not, which causes it to go to my social login.

### 📜 Logs

It's likely that this is handled by the SW, as in FF, I see transferred: service-worker.

**Comment by stonith404** [comment]
Fixed in `v1.3.0`.
