### ISSUE TITLE
🚀 Feature: Persistent Login

### ISSUE THREAD

**Issue by mochman** [stonith404/pingvin-share#65]
### 🔖 Feature description

A user shouldn't have to log in every time they visit the page.  

There could be an option to "keep me logged in" when initially logging in that would create a cookie or JWT that would store the session.

### 🎤 Pitch

This would make uploading/downloading files easier for registered users, since they won't have to log in every time they access the page.

**Comment by stonith404** [comment]
You should actually stay signed in for 3 months. Which browser do you use?

**Comment by mochman** [comment]
I have tried this using Chrome for Windows, Firefox for Windows, and Chrome for Android.  I have this behind a reverse proxy, but I've tested it using the reverse proxy and without it.  Are there any specific settings that need to be used when using a reverse proxy?

Checking the cookies after I login, both the refresh_token and access_token expire at the end of the session vs a date 3 months from now.

**Comment by stonith404** [comment]
Yep that's the issue, the token lasts for 3 months but the cookie gets deleted because it's a session cookie. I barely close my browser so I haven't noticed it.

**Comment by stonith404** [comment]
fixed in e5b50f855c02aa4b5c9ee873dd5a7ab25759972d

**Comment by mochman** [comment]
Just built the image with your edits and it all works now.  Thank you!

**Comment by stonith404** [comment]
Fixed in v0.5.0 :)
