### ISSUE TITLE
🚀 Feature: Generate share link based on the origin of the current pingvin browser tab/window by default

### ISSUE THREAD

**Issue by gambit-dross** [stonith404/pingvin-share#653]
### 🔖 Feature description

The idea is to show the current origin in the share link (and make that the link that gets copied), instead of "http://localhost:3000/" when the App URL is not set specifically. Or at least give an option to copy the URL based on current origin in the final window.

### 🎤 Pitch

Imagine not having to copy the share URL and modify it based on the URL on your browser before sharing when you're using different ports on docker / port forwarding / reverse proxies / external URLs in conjunction with local URLs / or any other deployment techniques.

**Comment by stonith404** [comment]
Fixed in `v1.3.0`.
