### ISSUE TITLE
🐛 Bug Report: Unable to open LDAP session when password < 8 characters

### ISSUE THREAD

**Issue by Steve-Hubert** [stonith404/pingvin-share#658]
### 👟 Reproduction steps

Hello,
I have configured an LDAP server that works correctly.
However, when a user who has an LDAP password of less than 8 characters (even if it is not recommended ...), the connection is blocked because the password does not reach the minimum 8 characters of the form.

Reproduction step : 
- Configure LDAP server with Active Directory
- Set password less than 8 characters on a user (for example 7 characters)
- Try to connect on Pingvin

### 👍 Expected behavior

The connection should be successful because the LDAP password is correct

### 👎 Actual Behavior

The form requires a minimum of 8 characters to be submitted.

### 📜 Logs

No logs in console because form is not send.
Error message : "Must be at least 8 characters"

![image](https://github.com/user-attachments/assets/3fb9d0c0-1c11-4e2e-b6f3-94e15f419101)

**Comment by stonith404** [comment]
Thanks for reporting, this should be fixed in `1.2.4`.

**Comment by Steve-Hubert** [comment]
> Thanks for reporting, this should be fixed in `1.2.4`.

Hi,
Thanks for quick support
I just tested the new version with a non-existent LDAP user in the database, and I have a popup that appears at the bottom of the page still indicating this error.

![image](https://github.com/user-attachments/assets/84929da1-c2f8-46b2-9bd3-5c1ec41c50e2)
