### ISSUE TITLE
🐛 Bug Report: Email Recipients does not show up

### ISSUE THREAD

**Issue by adispy** [stonith404/pingvin-share#66]
### 👟 Reproduction steps

When I share a file, I don't get the **Email Recipients** box to put in the emails to whom I want to send the share link.

I have test it with Opera (main browser), Chrome and Edge.

### 👍 Expected behavior

An email box to show up so I can type the destination email addresses to send the share link

### 👎 Actual Behavior

The email box does not show up

### 🌐 Browser

Opera, Chrome, Edge

**Comment by adispy** [comment]
Damn... I don't know how I missed that. Sorry for the issues, it is working now.

Thank you, much appreciate it.

**Comment by stonith404** [comment]
Nice, have fun with Pingvin Share:)
