### ISSUE TITLE
🚀 Feature: Thank you for such a great project. Can you help me solve my problem

### ISSUE THREAD

**Issue by shidahuilang** [stonith404/pingvin-share#662]
上传文件的名称已经改成Docker映射目录了，比如我上传一个中文名的文件，目录中的文件就改成11372f4a-bc96-4a26-9fa1-ead55d05c1b8这种名字，我想在目录中看到上传时候的真实名称。因为不这样的话，在映射目录中根本看不到是什么文件！都是一排数字名称？是不是我的设置有问题？

**Comment by stonith404** [comment]
I can't speak Chinese. For support please join our [Discord](https://discord.gg/wHRQ9nFRcK) an ask your question in English there.

**Comment by shidahuilang** [comment]
The name of the uploaded file has been changed to the Docker mapping directory. For example, when I upload a file with a Chinese name, the file in the directory is changed to a name like 11372f4a-bc96-4a26-9fa1-ead55d05c1b8. I want to see the real name when uploading in the directory. Because otherwise, you won't be able to see what file it is in the mapping directory! Are they all a row of numerical names? Is there a problem with my settings?
