### ISSUE TITLE
🚀 Feature: Thank you for such a great project. Can you help me solve my problem

### ISSUE THREAD

**Issue by shidahuilang** [stonith404/pingvin-share#663]
### 🔖 Feature description

The name of the uploaded file has been changed to the Docker mapping directory. For example, when I upload a file with a Chinese name, the file in the directory is changed to a name like 11372f4a-bc96-4a26-9fa1-ead55d05c1b8. I want to see the real name when uploading in the directory. Because otherwise, you won't be able to see what file it is in the mapping directory! Are they all a row of numerical names? Is there a problem with my settings?

### 🎤 Pitch

The name of the uploaded file has been changed to the Docker mapping directory. For example, when I upload a file with a Chinese name, the file in the directory is changed to a name like 11372f4a-bc96-4a26-9fa1-ead55d05c1b8. I want to see the real name when uploading in the directory. Because otherwise, you won't be able to see what file it is in the mapping directory! Are they all a row of numerical names? Is there a problem with my settings?

**Comment by simono41** [comment]
@shidahuilang I think it's intentional that the files are saved in directory names that consist of UUIDS.
