### ISSUE TITLE
🐛 Bug Report: Srpski and "Српски" languages are mixed up/bugged

### ISSUE THREAD

**Issue by returnedinformation** [stonith404/pingvin-share#664]
### 👟 Reproduction steps

When I set the language to "Srpski", which should be Serbian in Latin, it shows the app in Serbian Cyrilic
When I set the language to "Српски", which should be Serbian in Cyrilic, it shows the app in English

I could really use Serbian Latin, thank you!

### 👍 Expected behavior

When I set the language to "Srpski", which should be Serbian in Latin, it shows the app in Serbian Cyrilic
When I set the language to "Српски", which should be Serbian in Cyrilic, it shows the app in English

I could really use Serbian Latin, thank you!

### 👎 Actual Behavior

When I set the language to "Srpski", which should be Serbian in Latin, it shows the app in Serbian Cyrilic
When I set the language to "Српски", which should be Serbian in Cyrilic, it shows the app in English

I could really use Serbian Latin, thank you!

**Comment by stonith404** [comment]
This fix won’t have a separate release but will be included in the next one. Currently, Serbian Latin appears in English because it hasn’t been translated yet. If you’d like to help with the translation, your contribution would be greatly appreciated :)

**Comment by returnedinformation** [comment]
I see, you're missing one translation, I can help with that, at least by explaining how even you can do it.
But first you need to understand...

As it is right now
you have: _"Srpski"_ and **"Српски"**
Which implies that those are _Serbian Latin_ and **Serbian Cyrilic** (in that order)
But your _"Srpski"_ doesn't set the language to _Serbian Latin_, but sets the language to **Serbian Cyrilic**

Here is a tool that can transliterate between Serbian Latin and Cyrilic, so basically my help isn't even needed
https://latinicaucirilicu-rs.translate.goog/?_x_tr_sl=sr&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

**Comment by stonith404** [comment]
Thanks for clarifying. I switched to labels that when you click "Српски" you get Serbian Cyrillic and when you click "Srpski" you get Serbian Latin (which is currently only English as nothing was translated yet). This is correct, right?

Regarding the translation from Serbian Cyrilic to Serbian Latin, I don't do translations in Pingvin Share, this is done by the community. Feel free to contribute to the project by filling out the Serbian translation strings on [Crowdin](https://crowdin.com/project/pingvin-share), Crowdin doesn't require any programming skills :)

**Comment by returnedinformation** [comment]
> This is correct, right?
Yep, that's correct now!
I'll help out on Crowdin then, will come back here once I finish both

**Comment by returnedinformation** [comment]
I've translated to Serbian Cyrilic and then ran a script over it to transliterate to Latin and have uploaded it for Serbian Latin.

I'm attaching a python script I've used to transliterate it. "pip install transliterate" is required.
[cyr-lat.zip](https://github.com/user-attachments/files/17776022/cyr-lat.zip)
