### ISSUE TITLE
🐛 Bug Report: login form

### ISSUE THREAD

**Issue by serviciimedianet** [stonith404/pingvin-share#670]
### 👟 Reproduction steps

When i try to login, after typing the corect credentials, and pressing Sign In, it doen nothing.
I have rebooted the container.

### 👍 Expected behavior

It should display the page where i could upload files.

### 👎 Actual Behavior

![image](https://github.com/user-attachments/assets/ecc41190-0e62-446e-9efa-e5f4ce7020dc)

### 📜 Logs

[Pingvin-Share.csv](https://github.com/user-attachments/files/17728306/Pingvin-Share.csv)

**Comment by jwdoll** [comment]
v1.1.2 enabled secure cookies if the site url starts with https. Unfortunately it breaks simple http connections over LAN.

**Comment by stonith404** [comment]
Fixed in `v1.3.0`. As @jwdoll has recommended, I've added a configuration variable where you can manually set if secure cookies should be used.
