### ISSUE TITLE
🚀 Feature: UI Change for better experience

### ISSUE THREAD

**Issue by kbkozlev** [stonith404/pingvin-share#673]
### 🔖 Feature description

Change the size input fields from bytes into something more user-friendly. 
This is also relevant for the “Chunk Size” field, and all others where this is relevant.

### 🎤 Pitch

I suggest having 2 input fields, one for integers and the other a dropdown selection for Bytes, MB, GB, TB etc.

All conversions can be done in the background automatically. This will simplify the user experience. 

![image](https://github.com/user-attachments/assets/6a60a91e-1524-4f93-9587-d23d2c444e29)

**Comment by jwdoll** [comment]
Personally, I prefer bytes because it's platform independent and is an administrative feature that needn't be changed often.

**Comment by tippfehlr** [comment]
@jwdoll how are the other options not platform independent? there is only the distinction between eg. gigabyte (1000³) and gibibyte (1024³), and only gibibytes would be reasonable imo.

**Comment by jwdoll** [comment]
Mac uses base 10 gigabytes, and bandwidth is typically quoted in base 10, at least in the US - my router reports that way as well, but takes settings in bytes to avoid ambiguity. Personally, I'm a gibibyte preferrer, but in this context, I'd assume base 10. Or are you proposing the integer and unit fields as in addition to the byte field as a helper to fill it in?

**Comment by jwdoll** [comment]
That said, I do think it would be worthwhile to format the byte boxes with commas (or I suppose periods, depending on localization).

**Comment by kbkozlev** [comment]
I was proposing to replace the byte fields with the integer and unit fields, but the idea was that they will be converted to bytes in the background anyways. This will only be a a UI/UX change for the end user. Besides the "value" fields can start from byte, Mib, Gib etc. So if a user prefers to use bytes he can use them as it was until now. 

The question for me would be if the conversion should be done from MB, GB or Mib, GiB.
