### ISSUE TITLE
🌐 Language request: missing french translation for {expires} variable

### ISSUE THREAD

**Issue by Moody-Styley** [stonith404/pingvin-share#674]
### 🌐 Language name (native)

French

### 🌐 Language code

fr-FR

**Comment by Moody-Styley** [comment]
Hello,

When Pingvin Share send an email and replaces the {expires}, the french translation is missing and the date is written in english.
For example, it writes 'in a day' instead of 'dans 1 jour', even for 'in 14 days' instead of 'dans 14 jours'

My Pingvin Share is installed on a Synology NAS Server and I cannot access configuration files directly to change it manually.

Regards

**Comment by stonith404** [comment]
Thanks, this has already been reported in #351. I'm closing this because of that.
