### ISSUE TITLE
🚀 Feature: Make "Password Protection" for shares mandatory

### ISSUE THREAD

**Issue by mztiq** [stonith404/pingvin-share#68]
### 🔖 Feature description

It would be great to have the option (i.e. in Administration settings) to make the "Password Protection" field for shares mandatory.

### 🎤 Pitch

This way it would be possible to force your users to set Passwords for every share they create.

**Comment by mztiq** [comment]
I'm using Pingvin to share pictures with family and friends and a lot of those users are not very tech-savvy.
This results in shares with personal photos being created without any security options (like password protection) set, that's why I was wondering if `Password Protection` could be defined as mandatory.  

I know this is more of a "personal problem" so I'd understand if that's not a feature you see for your app, but I wanted to give it a try anyway 😉

**Comment by stonith404** [comment]
Okay yeah this makes sense. Generally I implement features for Pingvin Share if I personally need them or multiple users want it, so I'll wait to implement this. If somebody else wants to see this feature feel free to upvote (👍) this issue.

I hope you understand that :)
