### ISSUE TITLE
🐛 Bug Report: Default share ID length

### ISSUE THREAD

**Issue by COMPLEXWASTAKEN** [stonith404/pingvin-share#685]
### 👟 Reproduction steps

When you set the Default share ID length on the new update if your not the best at coding and you set it to 111111 or 999999 to make them really long it throws' a really big error when trying to upload 

this was to test if there was a limit sense the max is 50 for a share id 

### 👍 Expected behavior

it should throw a error when you try to save the config its more then 50

### 👎 Actual Behavior

it lets you save config 

### 📜 Logs

![image](https://github.com/user-attachments/assets/af44b4a0-b702-416d-93b4-800b1382f802)

**Comment by stonith404** [comment]
Thanks for reporting, this should be fixed in `v1.6.0`.
