### ISSUE TITLE
🌐 Language request: Croatian

### ISSUE THREAD

**Issue by returnedinformation** [stonith404/pingvin-share#688]
### 🌐 Language name (native)

Hrvatski

### 🌐 Language code

hr-HR

**Comment by returnedinformation** [comment]
I'll do the translation for it, it's similar to Serbian Latin

**Comment by stonith404** [comment]
Added. Thanks for your contribution :)

**Comment by returnedinformation** [comment]
Finished! I hope to see it soon :D
