### ISSUE TITLE
🐛 Bug Report: Issue with File Upload Resulting in HTTP 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by byroblesh** [stonith404/pingvin-share#689]
### 👟 Reproduction steps

1.	Go to the file upload page at https://sharing.hugorobles.com/upload.
2.	Drag and drop a file with a size of approximately 175.3 MB (e.g., IMG_0302.MOV).
3.	Observe the upload process in the UI.
4.	Check the browser console for any error messages.

![CleanShot 2024-11-26 at 17 07 24@2x](https://github.com/user-attachments/assets/59ce9d4f-8cb7-4685-a154-1f2ebfdaa579)

### 👍 Expected behavior

The file should upload successfully as the UI specifies support for file sizes up to 10 GB.

### 👎 Actual Behavior

•	An error message appears in the UI:
"Error: No se pudo cargar 1 archivos. Intentando nuevamente."
•	The browser console logs multiple failed POST requests with the error:
413 (Request Entity Too Large).

**Comment by byroblesh** [comment]
Hello @stonith404 

Yes, I have Nginx configured as a reverse proxy in front of the application.

Let me know if you need details about the configuration file or specific directives.

I appreciate your time to help us, and congratulations on the great work done with Pingvin!

**Comment by byroblesh** [comment]
@stonith404 

I restarted the Portainer stack with the environment variable TRUST_PROXY=true, but the result was the same:

![CleanShot 2024-11-26 at 18 25 08@2x](https://github.com/user-attachments/assets/560dbd78-1ec4-459a-8d8f-bae619c602a7)


Thanks for your support. I’m sure this situation will help other people as well!

**Comment by stonith404** [comment]
Thanks. You have to set `client_max_body_size 10M;` in your Nginx configuration. See [this article](https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/) for more information.

**Comment by byroblesh** [comment]
Issue Resolved:

I have updated my /etc/nginx/nginx.conf file with the following configuration:

`# Global configuration for large file uploads and timeouts
client_max_body_size 12G;
client_body_timeout 600s;
keepalive_timeout 600s;
send_timeout 600s;`

After applying these changes, everything is working as expected.

@stonith404  Thank you for your assistance and attention to this matter!
