### ISSUE TITLE
🐛 Bug Report: Unable to change the logo

### ISSUE THREAD

**Issue by Craftingcat99** [stonith404/pingvin-share#693]
### 👟 Reproduction steps

Try to change the logo on a running pingvin instance

### 👍 Expected behavior

Logo should be changed to the newly uploaded file

### 👎 Actual Behavior

Logo remains original (uploaded  ~1y ago) file

### 📜 Logs

Haven't got any logs, cause I don't know where they are, but I already tried:
 
-waiting multiple hours after uploading 
-clearing browser cache 
-restarting docker container
-rebuilding docker container 
-restarting host vm
-uploading logo.png manually to /data/images/logo.png 
-updating pingvin to the newest version

**Comment by stonith404** [comment]
Are the images in `/data/images/` the new logo or the default one?

**Comment by Craftingcat99** [comment]
i can't check the image directly, cos I only have shell access, but the file gets the current date in the "last modified" field, everytime I upload a new logo, so I would assume the upload works

**Comment by Craftingcat99** [comment]
Found a way to access the images folder and downloaded the logo.png file and it is indeed the correct "new" one, but the file on the page, still hasn't updated

**Comment by stonith404** [comment]
Okay thanks. Can you share your docker-compose.yml? What if you try it in a private browser window?

**Comment by Craftingcat99** [comment]
My docker-compose file is basically the standard one from the guide without ClamAV and weirdly enough, if I open the site in a private window in works, indicating, the logo is cached in my browser, but disabling the cache doesn't work... I use firefox btw

**Comment by Craftingcat99** [comment]
Yes, that actually fixed the issue... 
Can't believe I'm apparently to stupid to clear the cache in my browser. Thanks very much for the help XD
