### ISSUE TITLE
🚀 Feature: Add a way to manage admins through groups in Authelia

### ISSUE THREAD

**Issue by weriomat** [stonith404/pingvin-share#695]
### 🔖 Feature description

I did not find a way when using Authelia as an OpenID Connect provider to set a role for admin access. Authelia does have the concept of [groups](https://www.authelia.com/integration/openid-connect/introduction/#groups), but I did not find a way to use them for authentication. There is 'Path to roles in OpenID Connect token', but when I set this to 'groups' it gives an Error of 'ERROR [OidcProvider] Roles not found at path groups in ID Token' although the scope of 'groups' is set in Authellia.
This might a problem with me not understanding Oidc.
Any help would be appreciated.

### 🎤 Pitch

Setting roles especially the admin role is a great feature of this app, which should be usable with this authentication provider

**Comment by stonith404** [comment]
You probably have to set "OpenID Connect scope" in Pingvin Share to `openid email profile groups` because Authelia only returns this claim if you request it with the scope.

**Comment by weriomat** [comment]
In my instance (v. 1.1.3) there is no option to configure the scope on the web UI. I only have the options of 'OpenID Connect', 'OpenID Connect Discovery URI', 'OpenID Connect username claim', 'Path to roles in OpenID Connect token', 'OpenID Connect role for general access', 'OpenID Connect role for admin access', 'OpenID Connect Client ID' and the option 'OpenID Connect Client secret'. 
It should be under the tab 'Social Login' right? 
Thank you for your help :)

**Comment by stonith404** [comment]
Oh, you need version 1.6.0. It's generally recommended to update Pingvin Share as often as possible. For exampld in v1.4.0 a critical vulnerability was fixed.
