### ISSUE TITLE
🚀 Feature: Ability to add different storage locations

### ISSUE THREAD

**Issue by icefrosch** [stonith404/pingvin-share#698]
### 🔖 Feature description

Being able to add a different storage source destination, like a NAS or something, would be sick. 

### 🎤 Pitch

Right now I have it installed on my normal Proxmox which doesn't have that much storage.  Would be sick if I could just define that it should store all uploaded files on the NAS rather than on the Server, so I don't need to install pingvin on the NAS itself to make it have enough storage.

**Comment by stonith404** [comment]
This is already possible with the `DATA_DIRECTORY` environment variable. See the [docs](https://stonith404.github.io/pingvin-share/setup/configuration#backend). Or if you use Docker you can just change the mounts:

```
      - "/path-to-your-nas/pingvin-share-uploads:/opt/app/backend/data/uploads"
      - "./data/pingvin-share.db:/opt/app/backend/data/pingvin-share.db" # Create this file before you start the container e.g touch pingvin-share.db
      - "./data/images:/opt/app/frontend/public/img"
```
