### ISSUE TITLE
🚀 Feature: Show version in GUI & alert when a new release is available

### ISSUE THREAD

**Issue by jl-678** [stonith404/pingvin-share#70]
### 🔖 Feature description

You are doing excellent work enhancing Pingvin, and it would be helpful to be able to view the currently running version to ensure that you are running the latest. At the same time, it would be great if Pingvin could display a banner alerting you if there is a new version.  To minimize annoyance maybe this could appear in the admin or config section?

Edit: to further reduce annoyance, you could combine these two concepts. (e.g. show a version a number at the bottom of one of the sections mentioned above and then maybe an "update available" icon next to it when appropriate.)

### 🎤 Pitch

I am new to Pingvin and am enjoying it. You just released a new version, and I upgraded with Docker and nothing seems to be different.  I think that maybe I pulled the old one, but realized that I could not find any information about the version I am running anywhere in the GUI.  It would be helpful to include this somewhere maybe in the admin or configuration section.

The upgrade banner is helpful to remind people to upgrade to the newest version.

**Comment by stonith404** [comment]
Added in 71658ad39d7e3638de659e8230fad4e05f60fdd8 and will be released in the next release
