### ISSUE TITLE
🐛 Bug Report: stonith404/pingvin-share:latest container does not disable registration anymore

### ISSUE THREAD

**Issue by kartone** [stonith404/pingvin-share#700]
### 👟 Reproduction steps

I'm running the latest Docker container with this docker-compose:

```dockerfile
services:
  pingvin-share:
    container_name: pingvin
    image: stonith404/pingvin-share:latest
    restart: unless-stopped
    environment:
      - TRUST_PROXY=true # Set to true if a reverse proxy is in front of the container
      - ALLOW_REGISTRATION=False
    volumes:
      - "./data/pingvin-data/:/opt/app/backend/data"
      - "./data/pingvin-data/images:/opt/app/frontend/public/img"
networks:
  default:
    external: true
    name: npm-bus
``` 
    
    However the registration is still allowed.

### 👍 Expected behavior

It should not let new registrations.

### 👎 Actual Behavior

It actually let any user to register himself.

**Comment by stonith404** [comment]
The option to configure Pingvin Share using environment variables was removed two years ago in `v0.3.0`. You can now disable registration directly from the admin page at `/admin/config/share`.

**Comment by kartone** [comment]
Feeling so stupid now! Thank you!
