### ISSUE TITLE
🐛 Bug Report: latest container image is still running as root even though `PUID=` and `PGID=` variables are set to non-root user

### ISSUE THREAD

**Issue by alvitali** [stonith404/pingvin-share#704]
### 👟 Reproduction steps

Updated container to v1.7.0 and set `PUID=1000` and `PGID=1000`. However container seems to still be running as root with the UID 0.

All mapped directories are owned by docker:docker, docker logs show no errors.

### 👍 Expected behavior

Container should be running as docker user with the UID 1000

### 👎 Actual Behavior

Container is running as root. Do I need to do sth else? According to the docs, setting UID & GID is all that's needed

### 📜 Logs

Happy to provide

**Comment by stonith404** [comment]
The `root` user still exists in the container, however all processes are configured to run under the `pingvin-share` user, which corresponds to the specified `PUID` and `PGID`.

The container starts as a root user, creates a new user with the defined `PUID` and `PGID`, changes the permissions of a few files and then starts the the backend, frontend and reverse proxy with the newly created user. You can check this in the [entrypoint script](https://github.com/stonith404/pingvin-share/blob/6771bfdf50d60f0c966fcda3bdd6606c2f557bf9/scripts/docker/create-user.sh).


To check if the processes run with the `pingvin-share` user, you can use the following command: 

```bash
docker compose exec pingvin-share top
```

Additionally, the contents of the mounted data folder should reflect the specified PUID and PGID. You can confirm this by running:
```bash
ls -ln ./data
```

Does this address your concerns, or do you still have any security considerations regarding this approach?

**Comment by alvitali** [comment]
Sorry for my concerns, that's all right then! I had only looked at the Dockerfile and didn't inspect further.

Thank you! 
und schöni wiehnachte ig
