### ISSUE TITLE
🚀 Feature: Set minimum expiry server side

### ISSUE THREAD

**Issue by jimz011** [stonith404/pingvin-share#706]
### 🔖 Feature description

I would like to set a minimum default expiry (e.g. 7 days) for new uploads. It now defaults to 1 day, which wouldn't be a problem if people would actually read and select something. Most people however are way to lazy to read and just click on upload, the problem is that the default time is so low (1 day) that most of the data is already gone when we actually need it. Telling people to upload it again is usually not really loved by them.

### 🎤 Pitch

Make it so that we can choose the minimum expiration defaults (so that we can choose 7 days for example or even permanent!)

**Comment by stonith404** [comment]
There is already a request (#454) that suggests to customize the default share expiration. Is that what you would suggest or do you want to force the users that they can't for example set an expiration below 7 days?

**Comment by stonith404** [comment]
I'll close this in favor of https://github.com/stonith404/pingvin-share/issues/454.
