### ISSUE TITLE
🚀 Feature: Add files from networkshare to pingvin-share

### ISSUE THREAD

**Issue by Firebirdss80** [stonith404/pingvin-share#71]
### 🔖 Feature description

This feature would allow the admin to directly add files from his/her existing hard drives to Pingvin without uploading them to the instance.

### 🎤 Pitch

I make mod packs for games, and share photos, and family videos. This would allow me to attach network storage and grab a file on the drive without uploading it directly to Pingvin. I currently employ a Ceph cluster so having 3 copies of a single file on one my nodes is already enough. Adding a new VM and then uploading the file to it would mean I have 6 copies.

I also am no developer so I couldn't tell you how to do this or the complexity of it I just think it would be a neat feature.

**Comment by Albonycal** [comment]
One can mount a network share and then add it to the container?

**Comment by Firebirdss80** [comment]
> One can mount a network share and then add it to the container?

Yes, but when I link a file to share with someone will it just show up or will it move the file and add it to its own folder? That is where I am confused.

**Comment by stonith404** [comment]
> Yes, but when I link a file to share with someone will it just show up or will it move the file and add it to its own folder? That is where I am confused.

I'm not sure if I understand your question, could you please clarify your question a bit more.

**Comment by stonith404** [comment]
Closing this because I think for this use case you should better use a cloud like Nextcloud. The purpose of Pingvin Share is to upload and share files quickly.
