### ISSUE TITLE
🚀 Feature: Allow admin to set global light/dark mode. Removes ability for end user to set theme

### ISSUE THREAD

**Issue by iambarney** [stonith404/pingvin-share#710]
### 🔖 Feature description

There should be a setting within the Administration panel for a permanent override of the light/dark/ssytem theme. Toggling this will remove 'Colour scheme' from all users' My Account panels.

### 🎤 Pitch

Some logos may not look good and/or are difficult to see on light/dark themes. Having this function in place will ensure that the logo the administrator has set will be seen the way they intended.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a new configuration variable for theme override, update the admin configuration page to include this setting, and modify the theme switcher component to respect the admin override.

You can review changes in this commit: https://github.com/jacks-sam1010/stonith404-pingvin-share-710/commit/d1d92fc6896c7afef53e80da1be7d4a6f23d8223.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by stonith404** [comment]
This is similar to #330 because of that I'm closing this issue. Feel free to participate in the discussion there.
