### ISSUE TITLE
🐛 Bug Report: Creating user and group.

### ISSUE THREAD

**Issue by x2358473** [stonith404/pingvin-share#717]
### 👟 Reproduction steps

重新部署最新的版本时，启动docker就卡在Creating user and group

### 👍 Expected behavior

正常应该是要进行下去

### 👎 Actual Behavior

卡住了

### 📜 Logs

Creating user and group...

**Comment by GitNees** [comment]
i dont think this will help in chinese, i use docker compose and could pull the new version and works

**Comment by stonith404** [comment]
Please recreate the issue in English. Thanks :)
