### ISSUE TITLE
🐛 Bug Report: Pingvin Share breaks after upgrading to 0.5.1

### ISSUE THREAD

**Issue by blaine07** [stonith404/pingvin-share#73]
### 👟 Reproduction steps

Upgraded from 0.5.0 to 0.5.1 it quit working

### 👍 Expected behavior

It to work. Is 0.5.1 broke? Tried to downgrade docker to 0.5.0 and didn’t work either. Scratches head

### 👎 Actual Behavior

Doesn’t work; just 502

### 🌐 Browser

Safari

**Comment by blaine07** [comment]
![050E4C7F-D21F-4179-B219-86D881320BA8](https://user-images.githubusercontent.com/63940698/210675401-492b1fb3-1b93-40ee-93ad-622cb61312cd.jpeg)

mph this about failed to migrate database?

**Comment by jl-678** [comment]
I would add that I saw the same thing earlier today when I was playing rebuilding Pingvin.  At the time, I was doing many (bad) things and so I assumed that it was something that I did.

**Comment by Ju17091** [comment]
Since the update, it no longer works for me either. The docker container tries to restart every 10 seconds.

**Comment by Eidenz** [comment]
Yep, same thing here. Dev seems to have made a breaking change in the database.

**Comment by stonith404** [comment]
I've released a hotfix, the newest image works now. If you've already upgraded and ran in this issue please follow this instructions to fix the installation:

1. Install Sqlite first, with apt: `sudo apt install sqlite`
2. Cd into the root directory of Pingvin Share
3. Run the following commands:

```
docker compose down 
sudo sqlite3 data/pingvin-share.db "DELETE FROM _prisma_migrations WHERE migration_name = '20230104145733_v0_5_1'; drop table new_RefreshToken;"
docker compose pull 
docker compose up -d
```

Please let me know if it works for you

**Comment by Eidenz** [comment]
Fix worked just fine on my Unraid instance

**Comment by stonith404** [comment]
closing this because it should be fixed. If you have any issues related to the upgrade to `v0.5.1`, feel free to reopen this issue.
