### ISSUE TITLE
🚀 Feature: Forgotten Password

### ISSUE THREAD

**Issue by jl-678** [stonith404/pingvin-share#74]
### 🔖 Feature description

You already have integrated mail functionality, it would be awesome to have the ability to reset a password in case the original is lost/forgotten.  Sadly, I had this problem today.

### 🎤 Pitch

Most sites offer this, and it seems like it would be a good idea.

Question to think about: How would this impact 2FA? Does resetting 2FA upon a forgotten password (probably the simplest approach) reduce the security of 2FA too much?

**Comment by stonith404** [comment]
Good idea👍 I would recommend that the user needs to provide the 2FA token, to reset the password. What do you think?

**Comment by jl-678** [comment]
Yes, that works. TY!

**Comment by stonith404** [comment]
Released in v0.10.0. SMTP must be enabled to use this feature.
