### ISSUE TITLE
Can't change user password

### ISSUE THREAD

**Issue by victorpahuus** [stonith404/pingvin-share#77]
I dont know, if im just blind, or if there is a real problem.

When im signed in as a user, and try to change the users password, and it says "saved".
Then im not able to login with the new password, but the old is still working.

There are no problems, when i change the password in the User Management as admin.

**Comment by stonith404** [comment]
That's actually an issue. I've fixed it in 74e895610642552c98c0015d0f8347735aaed457 and it will be released in the next release.

**Comment by stonith404** [comment]
Fixed in `v0.6.1`.
