### ISSUE TITLE
🐛 Bug Report: Clicking link icon on "My Shares" ignores APP_URL setting

### ISSUE THREAD

**Issue by jl-678** [stonith404/pingvin-share#78]
### 👟 Reproduction steps

I have one Pingvin instance working on two domains - a private one - pingvin.priv.foo.com and a public one - pingvin.foo.com. APP_URL is configured for pingvin.foo.com.  If I login to Pingvin via either URL, emailing files works properly and shares emailed include the correct public file link using APP_URL - e.g. pingvin.foo.com/share/xxxx

But, if I go to the "My shares" screen and click on the link button, the resulting URL ignores the APP_URL setting and uses whatever domain I am accessing Pingvin with.

Example 1: Access Pingvin via pingvin.foo.com
My shares link: pingvin.foo.com/share/xxxx <-- Correct

Example 2: Access Pingvin via pingvin.priv.foo.com
My shares link: pingvin.priv.foo.com/share/xxxx <--Wrong

**Analysis:**
I think that there is an error where APP_URL is not referenced when creating the share link in "My shares."  The part after the / is correct (e.g. "/share/xxxx") in all cases, and so it seems that Pingvin is just using whatever URL is being used to access the system when creating the link instead of referring to APP_URL configuration.

Further edit. The problem is here in shares.tsx.
                              `${window.location.origin}/share/${share.id}`

### 👍 Expected behavior

The link button should always follow the APP_URL setting and so in this case all URLs should start with pingvin.foo.com to match APP_URL.

### 👎 Actual Behavior

Pingvin ignores APP_URL when clicking the link button and uses whatever domain is being used to access the system.

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Fixed in f1b44f87fa64d3b21ca92c9068cb352d0ad51bc0 and is waiting for release.

**Comment by stonith404** [comment]
Fixed in `v0.6.1`
