### ISSUE TITLE
🐛 Bug Report: When a share expires, the local directory remains.

### ISSUE THREAD

**Issue by lfac76** [stonith404/pingvin-share#79]
### 👟 Reproduction steps

When I create a share with expire, after the time the share on Pingvin Site is deleted but the local directory and files still on disk (data/uploads/shares/...".

### 👍 Expected behavior

It should delete the local directory too.

### 👎 Actual Behavior

Create a share with 10 minutes expiration:

![Pingvin01](https://user-images.githubusercontent.com/83482904/211891261-3ff38eb8-df59-4b12-804c-104f8d9736bc.png)

The local directory:

![Pingvin02](https://user-images.githubusercontent.com/83482904/211891323-14a46c0e-7248-4bc5-a29f-ffb546d0a18b.png)

The share was deleted:

![image](https://user-images.githubusercontent.com/83482904/211892485-1e110a89-3bb4-4626-b2ec-3d296684625a.png)

But the local directory remains:

![image](https://user-images.githubusercontent.com/83482904/211892564-87c35f48-e49e-4fed-9da2-73d26100f1d8.png)

### 🌐 Browser

Brave

**Comment by stonith404** [comment]
There is a [job](https://github.com/stonith404/pingvin-share/blob/main/backend/src/jobs/jobs.service.ts#L15) that runs every hour and deletes all files of expired shares. Can you check if your files are deleted now?

**Comment by lfac76** [comment]
Hi Elias,

I didn't know that. Yes, the files are deleted.

Thanks a lot!

Em qua., 11 de jan. de 2023 às 18:29, Elias Schneider <
***@***.***> escreveu:

**Comment by stonith404** [comment]
Nice! I'll close the issue, feel free to create other issues if you encounter other bugs :)
