### ISSUE TITLE
Expiration date of "Never"

### ISSUE THREAD

**Issue by stautonico** [stonith404/pingvin-share#8]
It would be nice if there was an expiration date of "never" so that the share can be used at any time and manually deleted when no longer needed. If this is a feature you'd approve of, I wouldn't mind forking and creating a PR to implement it.

**Comment by stonith404** [comment]
Hey, yeah that feature sounds necessary! If you don't mind it would be nice if you create a PR? I hope you understand my code, if you have any questions, I'm here :)
