### ISSUE TITLE
I moved my pingvin stuff to another drive and now it's not working. 

### ISSUE THREAD

**Issue by GLaDOS-lab** [stonith404/pingvin-share#87]
I copy pasted docker-compose.yml, the Data folder, and pingvin-share-main.zip to a separate drive, so I have more space on Pingvin. However, now when I try to run docker-compose.yml, I get the following:

Removing pingvin_pingvin-share_1
Recreating be19dae47c82_pingvin_pingvin-share_1 ... 
Recreating be19dae47c82_pingvin_pingvin-share_1 ... error

ERROR: for be19dae47c82_pingvin_pingvin-share_1  Cannot start service pingvin-share: driver failed programming external connectivity on endpoint pingvin_pingvin-share_1 (7e387f1794a39faa2d68958c16b72a977952793c07e41c255f3de86446877051): Bind for 0.0.0.0:3000 failed: port is already allocated

ERROR: for pingvin-share  Cannot start service pingvin-share: driver failed programming external connectivity on endpoint pingvin_pingvin-share_1 (7e387f1794a39faa2d68958c16b72a977952793c07e41c255f3de86446877051): Bind for 0.0.0.0:3000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

Any ideas here?

**Comment by GLaDOS-lab** [comment]
When copying back the files, all that happens when I run docker-compose up -d is I get an output saying it's up to date.

**Comment by stonith404** [comment]
> (7e387f1794a39faa2d68958c16b72a977952793c07e41c255f3de86446877051): Bind for 0.0.0.0:3000 failed: port is already allocated

This error tells you that something is already running on port 3000. This might be because you didn't run `docker compose down` before you moved the files.

To fix this:
1. Run `docker ps` and you see all containers, it looks like this:
```
CONTAINER ID   IMAGE       COMMAND                  CREATED         STATUS         PORTS                                      NAMES
74b5477185a4   postgres    "/bin/sh -c /code/do…"   3 minutes ago   Up 3 minutes   0.0.0.0:8030->8000/tcp, :::8030->8000/tcp  postgres_1
aea2c2b552f4   nginx:1.19  "/docker-entrypoint.…"   17 hours ago    Up 17 hours    0.0.0.0:8054->80/tcp, :::8054->80/tcp      nginx_1
```

2. Spot the container that is using port 3000 and copy the container id
3. Run `docker kill container-id && docker rm container-id`
4. Start Pingvin Share again with `docker compose up -d`

**Comment by GLaDOS-lab** [comment]
Thanks for the help!

I'm having some other issues as well. My password is not currently working for the file share. Is there a way to change it or go into a file/folder and change it manually?

Secondly, I'm using this through cloudflare. It works great until I actually want to download a file. I am able to get to the page, but when clicking download, it auto-redirects to my IP instead of the URL. If I manually switch the IP to the URL, it downloads. What should I do there?

**Comment by stonith404** [comment]
@GLaDOS-lab  Which password? The admin account password?

For the second issue, could you share what you've entered for the App url in the configurations?

**Comment by GLaDOS-lab** [comment]
So, update. As a troubleshooting step, I’ve reset the URL to the default ”./“. I've reset my Cloudflare key and re-installed Cloudflare. Now, I can’t seem to access it at all except on my local network. Cloudflare is saying that the tunnel is fine, but I just have no idea what I’m doing here lol. I managed to figure out the password, thankfully.

**Comment by stonith404** [comment]
@GLaDOS-lab Which URL did you change? With my comment above, I meant the App Url on the Pingvin Share configuration page.

**Comment by GLaDOS-lab** [comment]
I have reset everything to a point where it now works again, with the same issue of downloading. The URL is pingvinfileshare.totallytechsupport.com. The URL I have in the pingvin settings is localhost:3000.

**Comment by stonith404** [comment]
You have to set the "App Url" to "https://pingvinfileshare.totallytechsupport.com". This should fix the issue.

Btw. thank you very much for your sponsorship :)

**Comment by GLaDOS-lab** [comment]
Thanks, that did it! And no problem. Least I could do with all the help you've given me. Plus, this was FAR easier to set up and use compared to NextCloud. Tutorials on that are like 40 minutes a piece.

**Comment by GLaDOS-lab** [comment]
@stonith404 just to double check http://pingvinfileshare.totallytechsupport.com/share/Lemongrab

**Comment by stonith404** [comment]
@GLaDOS-lab Nice, it works now, doesn't it?
