### ISSUE TITLE
🐛 Bug Report: Unable to find log files in "backend"

### ISSUE THREAD

**Issue by dnielso5** [stonith404/pingvin-share#89]
### 👟 Reproduction steps

Unable to find log files in "backend" as stated by the error message

trying to set up my email information and get an error to check log files in "backend"

### 👍 Expected behavior

Find a log file in folder "backend"

### 👎 Actual Behavior

No long file created

### 🌐 Browser

not a browser issue

**Comment by stonith404** [comment]
Hey, just run `docker compose logs` in the folder where you've stored the `docker-compose.yml`.

**Comment by dnielso5** [comment]
Thanks, got the errors, though it leads me to another question. im trying to use a email server i run but get this error:


pingvin-share-pingvin-share-1  | [Nest] 232  - 01/27/2023, 9:30:28 PM   ERROR [ExceptionsHandler] self-signed certificate
pingvin-share-pingvin-share-1  | Error: self-signed certificate
pingvin-share-pingvin-share-1  |     at TLSSocket.onConnectSecure (node:_tls_wrap:1545:34)
pingvin-share-pingvin-share-1  |     at TLSSocket.emit (node:events:513:28)
pingvin-share-pingvin-share-1  |     at TLSSocket._finishInit (node:_tls_wrap:959:8)
pingvin-share-pingvin-share-1  |     at ssl.onhandshakedone (node:_tls_wrap:743:12)

**Comment by stonith404** [comment]
@dnielso5 Maybe you've entered the wrong credentials. Can you confirm that it works with the same credentials on the following website: https://www.smtper.net ?

**Comment by dnielso5** [comment]
I was able to redo my certs so they are no longer self signed by my email. i am able to use the email option now.
