### ISSUE TITLE
🐛 Bug Report: Issue with external drive

### ISSUE THREAD

**Issue by GLaDOS-lab** [stonith404/pingvin-share#90]
### 👟 Reproduction steps

I have all of my Pingvin data on a separate drive. For some reason, said drive doesn't mount on startup. Basically, when pingvin runs on startup it creates a folder at the mount point called BackupHDD, and the drive automatically changes its name to BackupHDD1, causing all sorts of havoc on my plex server. 

### 👍 Expected behavior

Refreshes every few seconds to check if the drive is mounted

### 👎 Actual Behavior

creates a new folder, which means I have to go and stop pingvin, delete the old folder, unmount the drive, remount the drive, and then start pingvin again at every startup.

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
This isn't really an issue of Pingvin Share. We just use [Docker volumes](https://docs.docker.com/storage/volumes/) to persist the database and the uploads. Maybe you will find a way how to wait until the drive is mounted with Docker volumes.

I would recommend you to set up an auto mount like in [this tutorial](https://www.linuxbabe.com/desktop-linux/how-to-automount-file-systems-on-linux) or just comment out `restart: unless-stopped` in the Docker Compose file and start Pingvin Share manually after you've mounted your drive.
