### ISSUE TITLE
🐛 Bug Report: Small UX issue with setting up SMTP

### ISSUE THREAD

**Issue by gogo199432** [stonith404/pingvin-share#91]
### 👟 Reproduction steps

Setup SMTP info and click on "Send test email"

### 👍 Expected behavior

Test email is sent without having to first click on save, or disable the test email button till saved

### 👎 Actual Behavior

500 error, "SMTP not enabled"

After clicking on "Save" then "Send test email" it works.

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Fixed in `v0.9.0` :)
