### ISSUE TITLE
🚀 Feature: Custom branding

### ISSUE THREAD

**Issue by stonith404** [stonith404/pingvin-share#93]
### 🔖 Feature description

Custom branding allows the admin to customize Pingvin Share. This could include:
- Custom logo
- Custom name
- Custom color

To implement this, the configuration page needs a rework to prevent a confusing configuration page. I thought about a sidebar where you can choose the different configuration categories.

### 🎤 Pitch

This allows individuals or companies to fit Pingvin Share to their brand.

**Comment by Macthepig** [comment]
How can I customize Pingvin Share?

**Comment by stonith404** [comment]
@Macthepig Currently not as it is not implemented yet.

**Comment by stonith404** [comment]
Released in `v0.11.0`
