### ISSUE TITLE
🚀 Feature: Additional variables for e-mail template

### ISSUE THREAD

**Issue by Hukuma1** [stonith404/pingvin-share#94]
### 🔖 Feature description

Adding additional variables similar to `{shareUrl}` and `{creator}`. Can we please also add `{desc}` for the description of share and `{fileList}` of the list of files and sizes? And `{expires}` could show when it would expire.

### 🎤 Pitch

This would bring it on parity with WeTransfer sent e-mails even more I believe. And this way you could personalize the e-mail subject even more by having the `{desc}` in it, for example.

e.g. instead of the subject constantly being generic "Files shared with you" you could make it "Download: {desc}" and make it turn into "Download: Michael's photos from prom"

**Comment by iUnstable0** [comment]
@stonith404 i'll work on this

**Comment by Hukuma1** [comment]
Thanks for this, @iUnstable0!

Would it be possible to add a `files` variable too? Here is a WeTransfer e-mail for reference to show what I mean:

<img width="476" alt="wetransfer" src="https://user-images.githubusercontent.com/54511555/226389450-2b8b5e25-be64-46c5-a4bf-76b6ec0975ed.png">

**Comment by iUnstable0** [comment]
sure that sounds fun!
