### ISSUE TITLE
🚀 Feature: Reverse share link - no expiry link

### ISSUE THREAD

**Issue by victorpahuus** [stonith404/pingvin-share#96]
### 🔖 Feature description

It could be cool if you were able to share a link, to a group of people. So everyone can upload files from the same link, so you don't have to send a unique link to everyone.

### 🎤 Pitch

The feature could be useful for small and medium teams. For example, where everyone has to upload 1-2 files each, but it is not relevant who uploaded the file.

It would be a great feature for events where visitors could upload images to the same link.

**Comment by stonith404** [comment]
Released in v0.10.0. You can now configure how many times the link can be used.
