### ISSUE TITLE
🚀 Feature: Version number on admin page or website footer 

### ISSUE THREAD

**Issue by dnielso5** [stonith404/pingvin-share#97]
### 🔖 Feature description

Version number on admin page or website footer 

### 🎤 Pitch

when there are only back end changes its hard to know that everything updated, would be nice to have a confirmation of what version is running via the admin panel or on the bottom footer of the website

**Comment by stonith404** [comment]
![image](https://user-images.githubusercontent.com/58886915/218175677-ec3ef3e8-e55f-4788-8485-27b3f7b5d0bb.jpeg)

The version should be displayed on the admin page. Can you see it?

**Comment by dnielso5** [comment]
Welp, looks like i got egg on my face.

Thanks. haha
