### ISSUE TITLE
Access from hostname different from localhost

### ISSUE THREAD

**Issue by coaz** [stonith404/pingvin-share#99]
I have a dreamhost server in wich I already install pingvin-share but I cannot acces from my site http:mysite:3000 neither http://localhost:3000  Do you know how to do this?

**Comment by stonith404** [comment]
You can't access localhost from another machine. Do you point a domain to your server? Do you have a firewall, if yes is the port 3000 open?

**Comment by coaz** [comment]
Im using Dreamhost VPS and yes, I tryed to access from http://node.alamoguate.com:3000/ and get nothing. The port is open. Have I to change anything in the pingvin share configuration to access from this url?

**Comment by stonith404** [comment]
When I visit the site I get an internal server error. Can you share what the command `docker compose logs` results?

**Comment by coaz** [comment]
thank you stonith. I didnt install it via docker, I made a stand alone installation but php error log is giving me this:

[12-Feb-2023 17:31:59 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'lib-ssh2.so' (tried: /usr/local/php74/lib/php/extensions/no-debug-non-zts-20190902/lib-ssh2.so (/usr/local/php74/lib/php/extensions/no-debug-non-zts-20190902/lib-ssh2.so: cannot open shared object file: No such file or directory), /usr/local/php74/lib/php/extensions/no-debug-non-zts-20190902/lib-ssh2.so.so (/usr/local/php74/lib/php/extensions/no-debug-non-zts-20190902/lib-ssh2.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
[12-Feb-2023 17:31:59 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'ssh2.so' (tried: /usr/local/php74/lib/php/extensions/no-debug-non-zts-20190902/ssh2.so (/usr/local/php74/lib/php/extensions/no-debug-non-zts-20190902/ssh2.so: cannot open shared object file: No such file or directory), /usr/local/php74/lib/php/extensions/no-debug-non-zts-20190902/ssh2.so.so (/usr/local/php74/lib/php/extensions/no-debug-non-zts-20190902/ssh2.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by stonith404** [comment]
Ah okay, could you run `pm2 logs pingvin-share-backend` and `pm2 logs pingvin-share-frontend` and share the output because that's definitely an issue with Pingvin Share.

**Comment by coaz** [comment]
Backend log

[TAILING] Tailing last 15 lines for [pingvin-share-backend] process (change the value with --lines option)
/home/gt251/.pm2/logs/pingvin-share-backend-out.log last 15 lines:
1|pingvin- | 
1|pingvin- | No pending migrations to apply.
1|pingvin- | Running seed command `ts-node prisma/seed/config.seed.ts` ...
1|pingvin- | 
1|pingvin- | > pingvin-share-backend@0.10.0 prod
1|pingvin- | > prisma migrate deploy && prisma db seed && node dist/src/main
1|pingvin- | 
1|pingvin- | Prisma schema loaded from prisma/schema.prisma
1|pingvin- | Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
1|pingvin- | 
1|pingvin- | 13 migrations found in prisma/migrations
1|pingvin- | 
1|pingvin- | 
1|pingvin- | No pending migrations to apply.
1|pingvin- | Running seed command `ts-node prisma/seed/config.seed.ts` ...

/home/gt251/.pm2/logs/pingvin-share-backend-error.log last 15 lines:
1|pingvin- | npm ERR!     /home/gt251/.npm/_logs/2023-02-12T17_24_25_106Z-debug-0.log
1|pingvin- | npm ERR! Missing script: "prod"
1|pingvin- | npm ERR! 
1|pingvin- | npm ERR! To see a list of scripts, run:
1|pingvin- | npm ERR!   npm run
1|pingvin- | 
1|pingvin- | npm ERR! A complete log of this run can be found in:
1|pingvin- | npm ERR!     /home/gt251/.npm/_logs/2023-02-12T17_24_25_699Z-debug-0.log
1|pingvin- | npm ERR! Missing script: "prod"
1|pingvin- | npm ERR! 
1|pingvin- | npm ERR! To see a list of scripts, run:
1|pingvin- | npm ERR!   npm run
1|pingvin- | 
1|pingvin- | npm ERR! A complete log of this run can be found in:
1|pingvin- | npm ERR!     /home/gt251/.npm/_logs/2023-02-12T17_24_26_337Z-debug-0.log

0 verbose cli /home/gt251/.nvm/versions/node/v17.9.1/bin/node /home/gt251/.nvm/versions/node/v17.9.1/lib/node_modules/pm2/lib/ProcessContainerFork.js
1 info using npm@8.11.0
2 info using node@v17.9.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/gt251/.nvm/versions/node/v17.9.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/gt251/nodeny/frontend/.npmrc Completed in 0ms
10 timing config:load:project Completed in 9ms
11 timing config:load:file:/home/gt251/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/gt251/.nvm/versions/node/v17.9.1/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 21ms
19 timing npm:load:configload Completed in 21ms
20 timing npm:load:mkdirpcache Completed in 4ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm run prod
23 verbose argv "run" "prod"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 4ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/home/gt251/.npm/_logs
28 verbose logfile /home/gt251/.npm/_logs/2023-02-12T17_24_25_699Z-debug-0.log
29 timing npm:load:logFile Completed in 8ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 42ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing command:run Completed in 10ms
36 verbose stack Error: Missing script: "prod"
36 verbose stack
36 verbose stack To see a list of scripts, run:
36 verbose stack   npm run
36 verbose stack     at RunScript.run (/home/gt251/.nvm/versions/node/v17.9.1/lib/node_modules/npm/lib/commands/run-script.js:97:13)
36 verbose stack     at async module.exports (/home/gt251/.nvm/versions/node/v17.9.1/lib/node_modules/npm/lib/cli.js:78:5)
37 verbose cwd /home/gt251/nodeny/frontend
38 verbose Linux 4.9.207-vs2.3.9.11-vs-2+
39 verbose node v17.9.1
40 verbose npm  v8.11.0
41 error Missing script: "prod"
41 error
41 error To see a list of scripts, run:
41 error   npm run
42 verbose exit 1
43 timing npm Completed in 66ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /home/gt251/.npm/_logs/2023-02-12T17_24_25_699Z-debug-0.log

0 verbose cli /home/gt251/.nvm/versions/node/v17.9.1/bin/node /home/gt251/.nvm/versions/node/v17.9.1/lib/node_modules/pm2/lib/ProcessContainerFork.js
1 info using npm@8.11.0
2 info using node@v17.9.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/gt251/.nvm/versions/node/v17.9.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/gt251/nodeny/frontend/.npmrc Completed in 4ms
10 timing config:load:project Completed in 13ms
11 timing config:load:file:/home/gt251/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/gt251/.nvm/versions/node/v17.9.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 27ms
19 timing npm:load:configload Completed in 28ms
20 timing npm:load:mkdirpcache Completed in 2ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm run prod
23 verbose argv "run" "prod"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 4ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/home/gt251/.npm/_logs
28 verbose logfile /home/gt251/.npm/_logs/2023-02-12T17_24_25_106Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 44ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing command:run Completed in 7ms
36 verbose stack Error: Missing script: "prod"
36 verbose stack
36 verbose stack To see a list of scripts, run:
36 verbose stack   npm run
36 verbose stack     at RunScript.run (/home/gt251/.nvm/versions/node/v17.9.1/lib/node_modules/npm/lib/commands/run-script.js:97:13)
36 verbose stack     at async module.exports (/home/gt251/.nvm/versions/node/v17.9.1/lib/node_modules/npm/lib/cli.js:78:5)
37 verbose cwd /home/gt251/nodeny/frontend
38 verbose Linux 4.9.207-vs2.3.9.11-vs-2+
39 verbose node v17.9.1
40 verbose npm  v8.11.0
41 error Missing script: "prod"
41 error
41 error To see a list of scripts, run:
41 error   npm run
42 verbose exit 1
43 timing npm Completed in 65ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     /home/gt251/.npm/_logs/2023-02-12T17_24_25_106Z-debug-0.log

**Comment by coaz** [comment]
Forntend log:

[TAILING] Tailing last 15 lines for [pingvin-share-frontend] process (change the value with --lines option)
/home/gt251/.pm2/logs/pingvin-share-frontend-out.log last 15 lines:
0|pingvin- | 
0|pingvin- | > pingvin-share-frontend@0.10.0 start
0|pingvin- | > next start
0|pingvin- | 
0|pingvin- | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
0|pingvin- | 
0|pingvin- | > pingvin-share-frontend@0.10.0 start
0|pingvin- | > next start
0|pingvin- | 
0|pingvin- | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
0|pingvin- | 
0|pingvin- | > pingvin-share-frontend@0.10.0 start
0|pingvin- | > next start
0|pingvin- | 
0|pingvin- | ready - started server on 0.0.0.0:3000, url: http://localhost:3000

/home/gt251/.pm2/logs/pingvin-share-frontend-error.log last 15 lines:
0|pingvin- |       [Symbol(corked)]: 0,
0|pingvin- |       [Symbol(kOutHeaders)]: [Object: null prototype]
0|pingvin- |     },
0|pingvin- |     _currentUrl: 'http://localhost:8080/api/configs',
0|pingvin- |     [Symbol(kCapture)]: false
0|pingvin- |   },
0|pingvin- |   cause: Error: connect ECONNREFUSED 127.0.0.1:8080
0|pingvin- |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16) {
0|pingvin- |     errno: -111,
0|pingvin- |     code: 'ECONNREFUSED',
0|pingvin- |     syscall: 'connect',
0|pingvin- |     address: '127.0.0.1',
0|pingvin- |     port: 8080
0|pingvin- |   }
0|pingvin- | }

**Comment by stonith404** [comment]
That looks strange. You may have switched directories between these installation commands. Can you try a fresh installation? Just delete the Pingvin Share folder, run `pm2 delete pingvin-share-frontend pingvin-share-backend` and redo the steps in the stand-alone installation.

**Comment by coaz** [comment]
I run the delete process and create a new instalation on http://nodeny.me:3000/ and get the same result.

**Comment by coaz** [comment]
Sharing logs 
[backend.log](https://github.com/stonith404/pingvin-share/files/10716868/backend.log)
[frontend.log](https://github.com/stonith404/pingvin-share/files/10716869/frontend.log)

**Comment by coaz** [comment]
I sent you an email. Can you please review it from Patrick Allen.

**Comment by coaz** [comment]
I move from dreamhost to AWS and I achieve it. Thank you.
